### ISSUE TITLE
Request: Demo Plugin

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#100]
As a developer I would like to have a demo plugin for PhaserEditor2D, so that we may have an starting entry point for people who would like to contribute to the project.

**Comment by PhaserEditor2D** [comment]
A demo plugin here:

https://github.com/PhaserEditor2D/PhaserEditor2D-v3-extras/tree/main/source/plugins/demoplugin

Check the readme file of the repostory.
