### ISSUE TITLE
Keybind to toggle GameObject's visibility

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#101]
A simple request. I work with scenes that have many containers, and I often hide/show containers to navigate around.
It would be good if I could press V to toggle the GameObject's visibility property.
![image](https://user-images.githubusercontent.com/9307505/105227109-dda2f680-5b2e-11eb-946a-6f9a0a22c165.png)

**Comment by PhaserEditor2D** [comment]
Done, try it: 
[Uploading PhaserEditor2D-3.10.2-next-windows.zip…]()

I think, for the future, we should support "design visibility and alpha". It means, you hide the object in the editor's scene but not in the real scene. What d you think? A separated issue for this?
