### ISSUE TITLE
Feature request: Selecting a project in another folder

### ISSUE THREAD

**Issue by zombiestruck** [PhaserEditor2D/PhaserEditor2D-v3#102]
Would be nice to be able to open existing projects in another directory

**Comment by PhaserEditor2D** [comment]
For the moment, the editor has a workspace concept. A workspace is a folder with all the projects.
If you are running the editor server manually, you can change the workspace like this:

```
$ PhaserEditor2D -ws /path/to/new/workspace
```

If you are running the Electron-based editor, you can change the workspace folder directly in the UI, in the **Projects** dialog:

https://help.phasereditor2d.com/v3/workbench/projects.html#projects-dialog

![image](https://user-images.githubusercontent.com/12187299/105641385-98920380-5e51-11eb-9e12-9186b8a5d462.png)

However, we are thinking on remove the workspace concept, and just allow creating and opening projects at any location.

**Comment by PhaserEditor2D** [comment]
Hi, I implemented this in the last release. You should use Phaser Editor 2D All-in-One.
