### ISSUE TITLE
Prefab naming bug for Typescript

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#104]
## Version
* Phaser Editor 2D Version: v3.10.2

* Operating System: Windows 10

* Web Browser and version: Firefox

## Description

Right now when a prefab is created in the editor, the name of the entity created is the same as the prefab, which results in this being added to the scene create code.

const rectanglePrefab = new rectanglePrefab(this, 496, 752);

## Possible solution

Phaser editor should name prefabs with a short unique id like this library generates
https://www.npmjs.com/package/short-unique-id

const rectanglePrefab_rsf2dg = new rectanglePrefab(this, 496, 752);

**Comment by PhaserEditor2D** [comment]
Hi.

When you add a new object to the scene, a unique variable name is generated (in comparison to the other variable names). We can do a lot of validation and disambiguation but for now, we prefer to provide the user with a way to change the name of the variables and fix the error.

In this case, you can change the name of the `rectanglePrefab` variable to `rectanglePrefab1`, or change the name of the prefab class to `RectanglePrefab`.

However, I will think about this particular case.
