### ISSUE TITLE
Select Texture dialog: allow grouping assets by packages

### ISSUE THREAD

**Issue by trynx** [PhaserEditor2D/PhaserEditor2D-v3#105]
There is a small inconvenient when selecting an assets which have the same name but from different package, as the asset may look the same, but the resolution is different.

e.g.
![image](https://user-images.githubusercontent.com/25723003/106614410-fc17e180-6573-11eb-8589-ef4fa605b22f.png)

Suggestion: To do grouping depend on the assets by package

[Pay user]

**Comment by PhaserEditor2D** [comment]
Done.

You can group the assets by type, asset pack file, or location. Look the new button added to the left corner of the button pane:

![image](https://user-images.githubusercontent.com/12187299/109253326-8c38f780-77bd-11eb-8077-312ece99cdc5.png)


Group by type:

![image](https://user-images.githubusercontent.com/12187299/109253193-3ebc8a80-77bd-11eb-8ded-c4b8210a9d05.png)

Group by asset pack:

![image](https://user-images.githubusercontent.com/12187299/109253243-5e53b300-77bd-11eb-930b-b1609284dca3.png)

Group by location:

![image](https://user-images.githubusercontent.com/12187299/109253277-70355600-77bd-11eb-9891-e960eceaeb3a.png)

**Comment by PhaserEditor2D** [comment]
I removed the button and use the context menu. You can open the context menu with right click or clicking in the new three-dots icon:

![image](https://user-images.githubusercontent.com/12187299/109343419-56d2ef00-783b-11eb-8afc-e69aa9eac461.png)
