### ISSUE TITLE
Packages only show assets on the same or sub folders

### ISSUE THREAD

**Issue by trynx** [PhaserEditor2D/PhaserEditor2D-v3#107]
When having a package on a subfolder in `assets`, it will only show assets of the current or sub folders depend on the package directory.
There isn't any indication saying so or a way to add assets from other folder which are still under `assets`.

**Comment by PhaserEditor2D** [comment]
I will create settings for this. To show the files from other folders. To show all files no matter if are used in other packs.

**Comment by PhaserEditor2D** [comment]
Done.

Now the Inspector view shows a Blocks section with a parameter for showing all files in the Blocks view:

![image](https://user-images.githubusercontent.com/12187299/116117541-59f72980-a68a-11eb-8669-116248527f3c.png)

Also, I added a Settings option to the context menu of the editor.
