### ISSUE TITLE
Support for SVG files?

### ISSUE THREAD

**Issue by johanlindfors** [PhaserEditor2D/PhaserEditor2D-v3#11]
I've noticed that I can add SVG files to the pack.json, however I can't figure out how to reference or add these files to the actual scene. Is this even supported?

**Comment by PhaserEditor2D** [comment]
Done, now you can import an SVG file as an Image in the asset pack file. The Blocks view of the Scene Editor will show the imported SVG image so you can drop it in the scene.

![image](https://user-images.githubusercontent.com/12187299/84698634-1d14bf00-af1e-11ea-8e92-681a166effc7.png)
![image](https://user-images.githubusercontent.com/12187299/84698689-3584d980-af1e-11ea-8e1d-4cfb46859788.png)
