### ISSUE TITLE
Inconsistent support for .svg images

### ISSUE THREAD

**Issue by gwichman-zynga-com** [PhaserEditor2D/PhaserEditor2D-v3#110]
## Version

* Phaser Editor Version: 3.10.2

* Operating system: Mac O/S

## Description

Trying to use SVG format for image files is problematic.  Parts of the editor seem fine with them, but most don't:
- When adding assets to an asset pack, SVG files appear in the Blocks section and display correctly.  I can add them to the pack and they show up in an SVG section, but they don't render correctly within the pack (see image 1)
- When creating an image object, and selecting a texture, SVG images do not show up in the texture selector
- I can work around this by editing the .scene file by hand.  The image name appears in the inspector, but the image is not rendered in the editor (see image 2)
- The image renders fine in the Phaser game when you run it.

## Possible solution
The fact that SVG's do render correctly in the Blocks section indicates that the capability exists in the software to render them, I think it just needs to be supported more generally throughout.

The workaround of hand-editing the .scene file is pretty unsatisfactory, since you can't actually see the image in the editor.  Of course I could work around it by converting all my SVGs to PNGs, but there are good reasons to use SVGs.  I could also work around it by using PNGs for development then writing a script to swap out the PNGs with SVGs in production builds, which is what I will probably do if the issue can't be addressed soon... but I think full SVG support would be desired.
![Screen Shot 2021-02-17 at 8 32 27 AM](https://user-images.githubusercontent.com/3675834/108237902-38fbe080-70fd-11eb-9515-3e3456f961d5.png)
![Screen Shot 2021-02-17 at 8 34 20 AM](https://user-images.githubusercontent.com/3675834/108237946-45803900-70fd-11eb-85b6-3c20a9008ed0.png)

**Comment by PhaserEditor2D** [comment]
Hi @gwichman-zynga-com 

Yes, the Scene Editor does not support SVG images. Actually, @ItsGravix needs this too. I will work on this.

**Comment by PhaserEditor2D** [comment]
By the way, you can add SVG files as images. Try importing the SVG file as an image in the asset pack and then add it to the scene.
The advantage of importing it as an SVG is that you can pre-scale it, but using it as a simple image is fine too.

**Comment by PhaserEditor2D** [comment]
Done.

Now it renders well in the Asset Pack editor:

![image](https://user-images.githubusercontent.com/12187299/108319597-a48e8e00-718f-11eb-96d5-f208ba6e75c9.png)

It is shown in the Blocks view of the Scene Editor:

![image](https://user-images.githubusercontent.com/12187299/108319672-bd973f00-718f-11eb-928e-65784dff17b6.png)

And the selecting texture dialogs too:

![image](https://user-images.githubusercontent.com/12187299/108319827-f6cfaf00-718f-11eb-886d-ba30baab72a0.png)

Phaser allows pre-scaling SVG images in the loader. If you do it with the Asset Pack editor, it will work on the game, but not in the Scene Editor. Pre-scaling an image and associating different images (with different scales) with the same file requires a couple of changes in the way we deal internally with image caching, so it is a bit harder to implement. If you need this, you can create a separate issue.

**Comment by PhaserEditor2D** [comment]
If you like to test these changes, you can follow Build Guide:

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/master/BUILD.md
