### ISSUE TITLE
Add support for scenes in user components

### ISSUE THREAD

**Issue by DanLCD** [PhaserEditor2D/PhaserEditor2D-v3#111]
While user components are extremely useful when used within game objects, their reachability can be extended to scenes as well to provide shared behavior between scenes, though this should be implemented as a variant for consistency.

**Comment by PhaserEditor2D** [comment]
I will implement this with a new ObjectScript.

**Comment by PhaserEditor2D** [comment]
Now we have the script nodes. You can add a script node to the scene, a game object, or another script node.
