### ISSUE TITLE
Skipping spritesheet's frame names

### ISSUE THREAD

**Issue by AxelCompte** [PhaserEditor2D/PhaserEditor2D-v3#112]
## Version

* Phaser Editor 2D Version: v3.10.2 (Premium)

* Operating System: Windows 10

* Web Browser and version: Google chrome v88.0.4324.190 (64-bit)

## Description

In the process of frame generation when setting up a spritesheet it randomly jumps the frame's name (for example "8, 9, 10, 12, 13...). This affects colateral wrong behaviours when the user creates an animation with those frames: the frame index animation's json variable will be set using the frame's name and, in this case, the frame 11 (called by editor "12") will be skip directly.

## Possible solution

The workaround is counting those skipped frames and make the animation selecting all animation's frames MINUS missing named frames, but doing it you'll be missing some between frames. 

The cleanest solution is overwritte manually de json and fix de "frame: XX" index variable yourself.

**Comment by PhaserEditor2D** [comment]
Thanks! Fixed.
