### ISSUE TITLE
Allow changing the context in which relative file paths are resolved

### ISSUE THREAD

**Issue by Connor800** [PhaserEditor2D/PhaserEditor2D-v3#113]
The way file paths are resolved right now limit how a project is structured, as the project root is used to resolve them.
A project setting to change the root in which files should be resolved from would be useful and allow for more project structures.

**Comment by PhaserEditor2D** [comment]
As a note to myself, this happens in Pack Files.

**Comment by PhaserEditor2D** [comment]
Also in the built-n http server.

**Comment by PhaserEditor2D** [comment]
Implemented in previous version of the editor. I forgotten to close this :)
https://help.phasereditor2d.com/v3/asset-pack-editor/public-root.html
