### ISSUE TITLE
On assets can use the same unique ID

### ISSUE THREAD

**Issue by trynx** [PhaserEditor2D/PhaserEditor2D-v3#114]
## Version

* Phaser Editor 2D Version: v3.12

## Description

Have 2 assets which can hold the same unique ID, the editor doesn't info about it.

The game object in the canvas will always show the first asset it found, doesn't matter if trying to change to the other asset.

![image](https://user-images.githubusercontent.com/25723003/113322642-9c447980-931d-11eb-866e-61d7bb7a9047.png)

## Possible solution

Info the user about ID conflict

**Comment by PhaserEditor2D** [comment]
I should create a Problems view in the editor. It will show the errors or warnings detected in each file (scene, pack, animations, ..).
