### ISSUE TITLE
[FeatureRequest] Add scope to components properties (constructor parameters)

### ISSUE THREAD

**Issue by trynx** [PhaserEditor2D/PhaserEditor2D-v3#117]
Hi :)

When creating a component we can add properties, for now the properties that are created are always with `public` access modify. 
![image](https://user-images.githubusercontent.com/25723003/116809946-9246ae00-ab49-11eb-90bd-e40985a4de8a.png)

Is it possible to add the `scope` option like when creating objects in the scenes?
![image](https://user-images.githubusercontent.com/25723003/116809962-b3a79a00-ab49-11eb-8748-a4b9bcea18a6.png)

Thanks, have a great day :D

**Comment by PhaserEditor2D** [comment]
Hi!

Why do you need a private properties? The properties of components and prefabs should be accesible in other scenes. If you need private properties, you can "write it by hand", in the user code section of the component. Am I missing something?

**Comment by trynx** [comment]
For cases that I want a property exposed in the editor but not allowing the change of the data from sources outside the class it self, as I'm doing only a hacky `get` function for the property.

Doing it by hand it would contradict the point of using the help of the editor and components, at least for this particular case.

If you want an example I will write one.

**Comment by PhaserEditor2D** [comment]
The editor generates code. Exposing a property to the editor is the same of exposing the property to the code.
When you add a component to an object, you are creating an instance of the component in the context of a scene (or a prefab). So the property should be public.

> If you want an example I will write one.

An example would be great.

**Comment by trynx** [comment]
Ah I understood your point.

Amm...thinking about cases where the dev would prefer to keep the property encapsulated in the component or when it should be open to change (public). About the first case of keeping it encapsulated, which is what I try to do, they way to initialize the component with a property should be done through the constructor.

e.g.
```
constructor(gameObject: Phaser.GameObjects.Image, position: Number) 
```

Let say if the scope is `private`, it the `position` won't be exposed and only used in the component, if the scope is only exposed without modify, then create only a `get` function, and if the scope is `public`, well it's like right now without any change.

If something isn't clear just say so :)

**Comment by PhaserEditor2D** [comment]
Yes, as constructor parameters it has sense. But it just complicates things. Maybe in the future I will implement it.

**Comment by PhaserEditor2D** [comment]
Thinking about this issue again. That's no possible to use constructor parameters in components when are part of a prefab.
The thing is, that if a prefab has a component with a constructor parameter, then you cannot change that parameter in the prefab instance.

So, we will have two different classes of parameters and it will make the whole thing more complicated. Encapsulation is good but in this case not required (I think).
