### ISSUE TITLE
4K display support

### ISSUE THREAD

**Issue by oliver9696** [PhaserEditor2D/PhaserEditor2D-v3#118]
![QQ截图20210502222136](https://user-images.githubusercontent.com/56241978/116816502-c4313200-ab94-11eb-9447-acdcba7f866c.jpg)
There are many same problems

**Comment by PhaserEditor2D** [comment]
Hi @oliver9696!

Please, press `Ctrl+3` and `Ctrl+4` for changing the tab's size. Or you are talking about other problem?

**Comment by oliver9696** [comment]
![QQ截图20210502233606](https://user-images.githubusercontent.com/56241978/116818685-4292d180-ab9f-11eb-9e52-e48d1565dfa9.jpg)
For example, the font size is too small

**Comment by PhaserEditor2D** [comment]
Ok I will take a look to the font size.

**Comment by PhaserEditor2D** [comment]
Hi @oliver9696 what's your OS. I want to send you a new version for you to try.

**Comment by oliver9696** [comment]
Win10 20H2 
thanks
yplpf96@gmail.com

**Comment by PhaserEditor2D** [comment]
Added commands to increment/decrement/reset the font size of the viewers:

![image](https://user-images.githubusercontent.com/12187299/119686707-9ac29980-be14-11eb-8c9e-dd9a175c6d1e.png)

You can open the Command Palette with `Ctrl+K`.

**Comment by PhaserEditor2D** [comment]
Please, you can test these commands with this Windows binaries:

https://drive.google.com/file/d/1GmRIKcWw5twxvWxn4QV4DrhzQcNqFqUT/view?usp=sharing
