### ISSUE TITLE
License server cant be reached....

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#122]
Hi, trying to activate my editor but it pops cannot connect:

![image](https://user-images.githubusercontent.com/850854/118430579-f13e2280-b706-11eb-8c6f-34c9fd45ded2.png)

tried a few times and still the same, not sure what happened.

**Comment by PhaserEditor2D** [comment]
Any log in the server side?

**Comment by jcyuan** [comment]
where is the log? i didn't see anything.

**Comment by PhaserEditor2D** [comment]
Just look the PhaserEditor2D.exe file output. The text it outputs.

**Comment by jcyuan** [comment]
fixed, so close
