### ISSUE TITLE
SERVER HOSTING

### ISSUE THREAD

**Issue by quantumgames-studios** [PhaserEditor2D/PhaserEditor2D-v3#125]
just a question, but how are you hosting the editor on https://play.phasereditor2d.com ?

**Comment by PhaserEditor2D** [comment]
Hi @quantumgames-studios 

I don't get the question. In the end, the editor is just a website and it can be hosted as any other website.
The editor in the cloud service uses a backend for multiple users. The editor for the desktop has a backend for a single user.

**Comment by quantumgames-studios** [comment]
ok but how did you set up the server to run all the java stuff? in the source code, i don't see any html

**Comment by PhaserEditor2D** [comment]
What Java stuff? v3 of the editor is all web, there isn't Java. And it does not have HTML files because all the DOM elements are created using JavaScript :)

**Comment by quantumgames-studios** [comment]
ok

**Comment by PhaserEditor2D** [comment]
Hi @quantumgames-studios! In any case, that's great you are interested in knowing how the editor works behind the scenes. If you want to talk more about it we can chat in the editor's discord channel: https://discord.gg/CPcESpQHth
