### ISSUE TITLE
change the ip

### ISSUE THREAD

**Issue by quantumgames-studios** [PhaserEditor2D/PhaserEditor2D-v3#126]
when i was running this, i kept getting the error: connection refeused. i looked it up, and i am going to try to change the ip adress that it sends me to to a different one. how would i do that?

**Comment by PhaserEditor2D** [comment]
Hi,

I don get it. When do you get the error? When you activate the editor? When you create a project?

**Comment by quantumgames-studios** [comment]
when i try to launch the editor, and it launches in the browser. i have checked my firewall, my internet, everything.

**Comment by PhaserEditor2D** [comment]
Can I see a screenshot?

**Comment by quantumgames-studios** [comment]
![Screenshot 2021-06-17 8 33 38 AM](https://user-images.githubusercontent.com/80978486/122417639-dd285380-cf46-11eb-9f67-e3a343464f41.png)

**Comment by PhaserEditor2D** [comment]
Hi @quantumgames-studios 

Why in port 8080? By default, the server listens in port 1959.

**Comment by quantumgames-studios** [comment]
because i tried first port 1959, then a number of other ports. look, i just want to know in what script is the server code where it tells the program to launch it on the ip, so i can change it.

**Comment by PhaserEditor2D** [comment]
Hi!

What's your OS? Just run `PhaserEditor2D.exe` and it will launch the default browser.

To see all options, run `PhaserEditor2D.exe -help`

I invite you to join our Discord channel for supporting you better:

https://discord.com/invite/4DdpMMD
