### ISSUE TITLE
the scroll height is wrong when a section is opened by default

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#127]
![image](https://user-images.githubusercontent.com/850854/122705034-7d53e480-d287-11eb-858b-48fd37358929.png)

as you can see, if the JSON section is opened (it's opened by default when i open the efx-pack.json), then the scrollbar does not have enough height to scroll, it seems it's calculated with a folded height.

**Comment by jcyuan** [comment]
![image](https://user-images.githubusercontent.com/850854/122725270-645b2b80-d2a7-11eb-9822-9c315f7c7f46.png)

emmm, annoying.........   i need to always guess which is which at the bottom lol once the focus jumps back to this frame ....

**Comment by PhaserEditor2D** [comment]
Hi! What version of the editor are you using?

**Comment by jcyuan** [comment]
> Hi! What version of the editor are you using?

newest v3.14.0

**Comment by PhaserEditor2D** [comment]
Can you check please if there is any error in the DevTools console?

**Comment by PhaserEditor2D** [comment]
And please, tell me if you resize the view it gets fixed.

**Comment by PhaserEditor2D** [comment]
Ok, I can reproduce it in the pack editor!

**Comment by PhaserEditor2D** [comment]
In the meantime, you can use the Outline view for browsing all the assets.

**Comment by PhaserEditor2D** [comment]
Hi @jcyuan 

Please, try this build and tell me if the bug is fixed: http://updates.phasereditor2d.com/v3.14.0-next/PhaserEditor2D-3.14.0-next-windows-2021-06-23.zip

**Comment by jcyuan** [comment]
> Hi @jcyuan
> 
> Please, try this build and tell me if the bug is fixed: http://updates.phasereditor2d.com/v3.14.0-next/PhaserEditor2D-3.14.0-next-windows-2021-06-23.zip

it works like a charm! thanks a lot Arian.
