### ISSUE TITLE
give a chance to still import as XML

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#128]
when i select an XML file, IDE detects that it's a bitmapFont xml, yes it's right,
but actually my logic is, merge all my bmpfont frames into a single atlas, and then load seperated xml files then do this:

    const fontData = Phaser.GameObjects.BitmapText.ParseXMLBitmapFont(font, frame);  // font is the node read from the loaded XML cache, and frame is the atlas frame
    if (frame && fontData) {
        console.info(`:: ${ faceName }`);
        this.sys.cache.bitmapFont.add(faceName, { data: fontData, texture: texKey, frame: faceName });
    }

so i wanna load the XML as just an XML but not a bitmapFont. but IDE does not provide a chance to import it as an XML:
![image](https://user-images.githubusercontent.com/850854/122705825-0b7c9a80-d289-11eb-8a53-e05d2c8449a9.png)

thanks

**Comment by jcyuan** [comment]
![image](https://user-images.githubusercontent.com/850854/122740028-287b9280-d2b6-11eb-9aef-afba0b53d642.png)

emmmm i'm stuck here now..
as mentioned above, my font xml are all merged into a big xml, and all bmp frames are all merged into an atlas too, then with some logic to manually create them later in the main logic, so now in PE i can't create a bitmapFont because there is no selectable items in the dialog...

**Comment by PhaserEditor2D** [comment]
Hi!

First, for loading the bitmap font file as a simple XML, try with the **Add File** button:

![image](https://user-images.githubusercontent.com/12187299/122754975-5505bf00-d262-11eb-875b-a1058b8f136d.png)

Then, select the XML type:

![image](https://user-images.githubusercontent.com/12187299/122755019-6353db00-d262-11eb-9dcd-dfda1d7c682a.png)

For making it possible to use it in the Scene Editor, you should import the bitmap font files in the pack files. It is required. However, you can create a pack file to be used only by the editor, just don't load it in the game.

**Comment by jcyuan** [comment]
> Hi!
> 
> First, for loading the bitmap font file as a simple XML, try with the **Add File** button:
> 
> ![image](https://user-images.githubusercontent.com/12187299/122754975-5505bf00-d262-11eb-875b-a1058b8f136d.png)
> 
> Then, select the XML type:
> 
> ![image](https://user-images.githubusercontent.com/12187299/122755019-6353db00-d262-11eb-9dcd-dfda1d7c682a.png)
> 
> For making it possible to use it in the Scene Editor, you should import the bitmap font files in the pack files. It is required. However, you can create a pack file to be used only by the editor, just don't load it in the game.

1, ah, sorry i did not notice in the pack editing window there is a Add file button on top of it...  ok got it
2, ok yep, seems have to do so, create a 'temp' pack for only editing and ignore them when running.
