### ISSUE TITLE
[feature request] instantly preview a scene

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#129]
Hi, Arian,

Thanks for your efforts always, 
Till now i feel the editor should have a preview scene functionality which will make the work more efficent.
Not like the Launch button it will launch the whole project, the preview only launches the scene you wanna check whether it works or not, without this functionality, i need to switch a lot of times between scenes especially when my game logic is complex.

thanks a lot man!

**Comment by PhaserEditor2D** [comment]
Hi! I think we can make this if you include the Phaser Editor DevTools in your game.

The Phaser Editor DevTools is just an idea, for now. But it's exciting and I will add it to the TODO list with medium priority.

**Comment by PhaserEditor2D** [comment]
Thinking again about this. It could be very complicated to do. Just think if you are using webpack or typescript... I think an option is to launch the game like the "play" button but with a query parameter to indicate to the game to switch to the scene at the startup. Something like this:

`http://localhost:8080?start=Level`

Sure, you should add a bit of code in your Preloader scene so as soon it loads all the game assets then it reads the query parameters and goes to the given scene. Sure, we should make it only available in a development setup.

I should think more about this.

**Comment by PhaserEditor2D** [comment]
I liked this so much that I implemented it! Now, with `Ctrl+0` you can run the game and start the current scene. Sure, it requires your game to get the `start` URL parameter and jump to the given scene. However, I included this logic in the webpack starter template.

The command is also available in the Scene menu:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/12187299/234200419-d2512ee9-c414-4754-a526-a325f304ef89.png">

It opens the game like this:

<img width="615" alt="Screenshot 2" src="https://user-images.githubusercontent.com/12187299/234200958-68eefea6-5617-4e08-8b2d-b6b9a23990de.png">
