### ISSUE TITLE
[Feature request] Automatic word wrap toggle

### ISSUE THREAD

**Issue by jorgeovi** [PhaserEditor2D/PhaserEditor2D-v3#131]
Would be great to have a checkbox on the text field properties pallette, to enable / disable automatic word wrap. 

Thanks!

**Comment by PhaserEditor2D** [comment]
Hi @jorgeovi I guess you mean this method: https://newdocs.phaser.io/docs/3.55.0/focus/Phaser.GameObjects.Text-setWordWrapWidth

**Comment by jorgeovi** [comment]
Correct. I can't really think a reason why the word wrap width would be different from the actual text field width, so I guess a simple checkbox to enable/disable it would be enough. 

When enabled on the editor, word wrap width would be set to coincide with the text field width. When disabled, it would be set to null.

OR you could add an input box to set a specific word wrap width different from the text field width... but as said above... why would anyone want to do that?

**Comment by PhaserEditor2D** [comment]
Hi @jorgeovi 

Mmm.. it looks a bit complicated. I try to keep the editor close top the Phaser API.

This is what I did, I added the Word Wrap Width and Advanced Wrap parameters:

![image](https://user-images.githubusercontent.com/12187299/124514906-1d435f00-ddac-11eb-8b0e-4018505f5d72.png)

Then, the compiler generates this code:

![image](https://user-images.githubusercontent.com/12187299/124514976-4f54c100-ddac-11eb-9858-c46d2d79c50f.png)

Do you want to test it? What's your OS?

**Comment by jorgeovi** [comment]
I can test on windows 10 and probably on an old macbook I have lying around at the office. It's a bit late already in spain but I can test it first thing in the morning :)

**Comment by PhaserEditor2D** [comment]
Hi! Thanks, please, if you can test this Windows buildÑ [PhaserEditor2D-3.14.0-next-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/6767333/PhaserEditor2D-3.14.0-next-windows.zip)

**Comment by jorgeovi** [comment]
Just tested it, works perfectly ;)

You forgot to add the tooltip help text:

![image](https://user-images.githubusercontent.com/6459471/124560801-81623380-de3d-11eb-9ba9-87b45f79194a.png)

**Comment by PhaserEditor2D** [comment]
Great! Thanks! I will fix the tooltip.
