### ISSUE TITLE
IDE generates an component event for prefab

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#133]
PE version: v3.15.0

![image](https://user-images.githubusercontent.com/850854/125247356-6ef86600-e325-11eb-90c2-85504b05e71a.png)

as you can seem in the picture, the IDE generates 2 events for the prefab and i think it should not generate `components-awake` event for it.

what i did is:

last time i have added a `AwakeComponent` for each of my prefabs as the older version does not have `prefab-awake` event.
so now in new version, i have directly removed the `AwakeCompoent.ts` and from the `Behaviors.compoments` file too.
but it seems the PE remembers that my prefab has this compoment still?

BTW:
I think what causes the problem is the deletion order? remove component file and definition in the *.component file first will cause this problem? if so, then after deleting i'm unable to remove the component from my prefab instance, because they disappear from the detail frame.

anyway i can re-create my prefabs and PE won't create that event. fortunately i don't have too many prefabs.

**Comment by PhaserEditor2D** [comment]
Hi @jcyuan 

If you remove the AwakeComponent from the prefab, you should re-compile all the scenes using the affected prefab, press `Ctrl+Alt+B`.

**Comment by jcyuan** [comment]
> Hi @jcyuan
> 
> If you remove the AwakeComponent from the prefab, you should re-compile all the scenes using the affected prefab, press `Ctrl+Alt+B`.

i have tried re-compile all project, but the component-awak event are still generated.

**Comment by PhaserEditor2D** [comment]
And the prefab hasn't any component? Please, can you check the prefab scene and the scene where the prefab is added?

**Comment by jcyuan** [comment]
steps:
1, drag my prefab to the main scene
2, select the prefab -> detail -> add compoment -> add a component (whatever component)
3, save, compile, now in the main scene coude it has both component event & prefab event which is correct
4, delete the component from Behavirous.components
5, select the prefab from the main scene and in the detail frame there is no component now (so i can't remove them)
5, ctrl+alt+b / or from menu -> build project
6, still components-awake event generated, but no new TestComponent(prefab) now.

**Comment by PhaserEditor2D** [comment]
In `v3.20.0-alpha.1` I removed the `prefab-awake` and `components-awake` events.
Now the editor generates a `this.events.emit("scene-awake");` line at the end of the `editorCreate()` method.

This simplifies event handling a lot. It breaks backward compatibility but it could be migrated with a minor of effort.

1- Re-create the `UserComponent.js` file. It will listen to the new event and call the `awake()` method of the component.
2- If you have a prefab instance listening to the `prefab-awake` event, then change it for listening the `scene-awake` event of the scene:
```javascript
// delete this
this.once('prefab-awake',  this.awake, this);

// add this
this.scene.events.once(`scene-awake`, this.awake, this);
```

You can test the latest changes here: 

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.20.0-alpha.1

**Comment by jcyuan** [comment]
> In `v3.20.0-alpha.1` I removed the `prefab-awake` and `components-awake` events.
> Now the editor generates a `this.events.emit("scene-awake");` line at the end of the `editorCreate()` method.
> 
> This simplifies event handling a lot. It breaks backward compatibility but it could be migrated with a minor of effort.
> 
> 1- Re-create the `UserComponent.js` file. It will listen to the new event and call the `awake()` method of the component.
> 2- If you have a prefab instance listening to the `prefab-awake` event, then change it for listening the `scene-awake` event of the scene:
> 
> ```js
> // delete this
> this.once("prefab-awake",  this.awake, this);
> 
> // add this
> this.scene.events.once("scene-awake", this.awake, this);
> ```
> 
> You can test the latest changes here:
> 
> https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.20.0-alpha.1

got it! thanks

**Comment by PhaserEditor2D** [comment]
Good, I'm closing this. If there is any issue you can re-open again.

**Comment by PhaserEditor2D** [comment]
Good, I'm closing this. If there is any issue you can re-open again.
