### ISSUE TITLE
Creating a list in the editor results in an initialized array in the generated code 

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#134]
* Phaser Editor 2D Version: 3.15
* Operating System: Mac Big Sur 10.15.7
* Web Browser and version: N/A

## Description

When adding a list to a scene, a list variable is created but not initialized in the definition or in the constructor resulting in a typescript compiler error.

Generated code that has the error
```
	editorCreate() {
		
		// rectangle
		const rectangle = this.add.rectangle(153, 145, 128, 128);
		rectangle.isFilled = true;
		
		// rectangle_1
		const rectangle_1 = this.add.rectangle(602, 433, 128, 128);
		rectangle_1.isFilled = true;
		
		// lists
		const speechBubbles = [rectangle, rectangle_1]
		
		this.speechBubbles = speechBubbles;
	}
	
	private speechBubbles: Phaser.GameObjects.Rectangle[];
         //          ^^^^^^^^^^ this is not defined
```

## Possible solution

It seems the codegen should set the value to an empty list or allow for undefined.  Empty list is slightly better to still allow typechecking to work as expected.

**Comment by jrabek** [comment]
In typescript it is possible to have `strictNullChecks: false` in the config but that is not the default config generated by the tsconfig file that Phaser Editor generates.

Also, disabling strictNullChecks means a lot of issues will go uncaught which means the help from the compiler is lost.

**Comment by jrabek** [comment]
From https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/132#issuecomment-875619070 it seems like `| undefined` is the standard approach with the editor's codegen.

**Comment by PhaserEditor2D** [comment]
Yes, it should use the `| undefined` expression in the type declaration. In the context of a prefab scene, it doesn't need it, because the list is initializaed in the constructor.

**Comment by PhaserEditor2D** [comment]
The case of an empty list also generates compiler errors. I fixed it:

Wrong:

```
const list = [];
```

Right:

```
const list: Array<any> = [];
```
