### ISSUE TITLE
Prefabs: constructor ordering of custom definition props and START-USER-CTR-CODE

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#136]
* Phaser Editor Version: 3.15
* Operating system: Mac Big Sur

## Description
Note that while technically this is a bug, it is more about a bigger issue of the data update model in prefabs.

This came about due to a related change in https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/132#issuecomment-876707383.

Currently in the constructor the ordering of data init is:
1) codegen of Phaser objects created in the editor
2) custom definition of props
3) USER-CTR-CODE

The issue is that any custom objects (i.e. ones that Phaser Editor does not have a representation for) are created in the USER-CTR-CODE section which means that props with setters will not be applied to custom objects. It also means that every custom setter must have guard code to check if the custom objects have been created yet just to handle the constructor sequencing since the custom objects will be defined after the constructor returns.

## Possible solution

There are a couple possible solutions:
1) Have two sections of prop definitions in the constructor: One before the USER-CTR-CODE and one after.  The one before is for props that do not have custom setters and can be used in custom object init, and the other will be for props with custom setters that may apply to the custom objects.

2) A single section of custom definition props that appears after USER-CTR-CODE.  That way the custom setter can apply values to the custom objects.  This is simpler than (1) since the custom setters must apply the values anyway so easier to just assume that the values get set in the setter rather than in the custom object init.

The application of props without custom definitions would need to happen in a `start` method that can be triggered via a generated event handler.
```
this.scene.events.once(Phaser.Scenes.Events.UPDATE, this.start, this);
```

## Bigger discussion

There are currently `components-awake` and `prefab-awake` events that are fired in the prefab's editor generated `create` handler.   There are a few issues with this approach.

1) Pollution of scene with 3 lines per each prefab in the scene.  Double that if the prefab has components.
For a scene with even a modest number of prefabs (i.e. ~20) the majority of the scene becomes event emitter lines.

2) `prefab-awake` encourages a polling data model

`prefab-awake` was added so that custom props can be applied to objects.  The problem is that if the properties change later there is no way to know unless a previous value is checked or if they are updated in every single `update` call.  Neither is efficient.

It would be better to eliminate the `prefab-awake` and force the use of setters. Note that phaser itself does this so that property updates are properly reflected in the objects (e.g. https://github.com/photonstorm/phaser/blob/5c8ecbcf999e6f328d21884e877c9e5935d2d350/src/gameobjects/text/Text.js#L1321).

Some properties like position are handled during the render cycle and don't need immediate update, but many property updates trigger a one time change in the object.  Either can be handled by a custom setter.

## Question about components
It seems `component-awake` should be handled entirely within the component itself.  In the component constructor an event handler can be added so that the code currently in `awake` would be executed there instead.

The component already has a reference to the gameObject which has a reference to the scene so the following can be placed in the constructor:
```
this.gameObject.scene.events.once(Phaser.Scenes.Events.UPDATE, this.start, this);
```

**Comment by PhaserEditor2D** [comment]
Hi!

> The issue is that any custom objects (i.e. ones that Phaser Editor does not have a representation for) are created in the USER-CTR-CODE section which means that props with setters will not be applied to custom objects.

A real example can help me understand this issue. There is something critical here on changing the order of the code generation: backward compatibility with games where that order is relevant.

> `prefab-awake` was added so that custom props can be applied to objects. The problem is that if the properties change later there is no way to know unless a previous value is checked or if they are updated in every single update call. Neither is efficient.

The awake event is for performing any actions when all properties are set in the scene generated by the editor.  For example, maybe you want to start an animation that depends on the values set in properties. It is not only about updating the state of the prefab.

> It would be better to eliminate the prefab-awake and force the use of setters.

I'm not convinced about it. I think custom setters are different things. The awake event is about the lifecycle of the prefab. The setters are about to update the prefab's state.

> Pollution of scene with 3 lines per each prefab in the scene. Double that if the prefab has components.

I agree. I think I had to include a flag for enabling the generation of this event. In many cases, prefabs are only objects only with data and no logic.

> . Note that phaser itself does this so that property updates are properly reflected in the objects

Yes, but sometimes Phaser uses a public attribute and extra getter/setters for updating an object. For example, the `TextStyle.setMaxLine` method (https://github.com/photonstorm/phaser/blob/6ac656da3288486aa497321e6cacbedff5c1e5ba/src/gameobjects/text/TextStyle.js#L1037).

There are cases where you have only-data attributes, and accessors that sets the attributes and performs other update actions.

> It seems component-awake should be handled entirely within the component itself....

I don't get it. Are you proposing removing the `components-awake` event? The `awake` event is not the same of the `start` event. You need both. Again, I can add a flag to the component definition for disable firing that event.

**Comment by jrabek** [comment]
Hey! Thanks for the quick response. And apologies in advance since I am a bit rusty in my phaser development and am relearning some things.  Your responses have been super helpful!  If there are alternate patterns I should use I am definitely happy to switch to not fight Phaser and/or Phaser Editor.

> A real example can help me understand this issue. 

So here is a constructor for a prefab that is a mix of an editor created Image for an icon and a custom BBCodeText for a text box.

The image is initialized in the constructor first and has the values from the editor.

Then the custom props are initialized.  Note that some of them could be setters that apply to the image.

Then finally the a custom object, BBCodeText, is added in the `USER-CTR-CODE` section.  Note that the setters can't change the properties on this object since it is initialized after the setters.

It is possible that the `text` setter could check for the existence of the `textObject` first and also store an internal value that the textObject could then use for init but it would be duplicate data since the `textObject` already stores that internally.  Also it means that some objects are initialized one way and others another way.

In general it just seems less error prone to always use setters to be aware of changes instead of normal properties.

I did reach out in the Phaser Beginner's Discord and PhotonStorm responded (https://discord.com/channels/244245946873937922/636143808769163274/865007816727855114).  Seems like setters are the usual way?

```
    constructor(scene: Phaser.Scene, x: number, y: number) {
        super(scene, x, y);
        
        // image
        const image = scene.add.image(0, 1, "logo0002");
        this.add(image);
        
        // custom definition props
        this.text = "Default Text";
        this.anchorX = 0.5;
        this.anchorY = 0.5;
        this.layoutBehavior = "scaleText";
        
        /* START-USER-CTR-CODE */
        const textStyle = {
            color: "#000000",
            fontFamily: "Chisel Mark",
            fontSize: "36px",
            stroke: "#000000"
        };
        this.#textObject = new BBCodeText(scene, 0, 0, '', textStyle);
        this.add(this.#textObject);
        this.#bounds = new Phaser.Geom.Rectangle();
        this.scene.events.addListener(Phaser.Scenes.Events.UPDATE, this.update, this);
        /* END-USER-CTR-CODE */
    }

   // Other methods
   // ...

    set text(value: string) {
        this.#textObject.text = value;
        this.#isDirty = true;
    }
```


> The awake event is for performing any actions when all properties are set in the scene generated by the editor.

Yeah, I was mainly trying to avoid having the extra code lines in every scene.ts file that used the prefab and seeing if it can be moved inside the prefab.ts.

I was wondering if something like this would work (note checking for this.awake works in js but not ts).

```
export default class AvatarButton extends AvatarRenderer {
    
    constructor(scene: Phaser.Scene, x: number, y: number, texture?: string, frame?: number | string) {
        super(scene, x, y, texture, frame);
        
        // this (prefab fields)
        this.emit("prefab-awake");
        
        // this (components)
        new PushOnClick(this);
        
        if (this.awake) {
            this.on(Phaser.GameObjects.Events.ADDED_TO_SCENE, this.awake, this);
        }

        /* START-USER-CTR-CODE */
        this.setInteractive()
            .on('pointerdown', () => this.onClicked && this.onClicked());
        /* END-USER-CTR-CODE */
    }
    
    public onClicked: () => void = () => {};
    
    /* START-USER-CODE */
    /* END-USER-CODE */
}
```

That way you can set all the property values and then add the gameObjec to the scene last. You still get the `awake` behavior without having to add extra code to the scene.ts.

> I'm not convinced about it. I think custom setters are different things. The awake event is about the lifecycle of the prefab. The setters are about to update the prefab's state.

Got it.  Yeah, I misunderstood.  From https://twitter.com/PhaserEditor2D/status/1414242488936804359 it sounded like the "custom init" was to apply the property values to the prefab not that all prefab values had been set.

> I don't get it. Are you proposing removing the components-awake event? The awake event is not the same of the start event. You need both.

I am mostly unsure of what should be done in which phase and looking to avoid having extra code in the scene :) 

Is it possible to use a built in event that is already fired? For example instead of using `prefab-awake` could use `ADDED_TO_SCENE`?


```
         if (listenAwake) {
(remove)   gameObject.once("components-awake", this.awake, this);
(add)      gameObject.once(Phaser.GameObjects.Events.ADDED_TO_SCENE, this.awake, this);
         }
```

```
        // avatarButton_1_1_3
        const avatarButton_1_1_3 = new AvatarButton(this, 1280, 736);
        this.add.existing(avatarButton_1_1_3);   // Original Position
        avatarButton_1_1_3.scaleX = 0.4;
        avatarButton_1_1_3.scaleY = 0.4;
        this.add.existing(avatarButton_1_1_3);   // New Position
```

This way you get the awake behavior that is separate from the start behavior.  I am unsure of the implications of adding to the scene after the setting of properties since my understanding adding to the scene adds the gameObject to the update and render lists which seems like it should be fine here?

**Comment by jrabek** [comment]
> I can add a flag to the component definition for disable firing that event.

That works as well.  I was mostly thinking of ways to have the best of both worlds: get the benefit of `awake` without the extra code in the scene.ts file.

**Comment by PhaserEditor2D** [comment]
Hi!

If you look in the code of a scene, the user properties of prefabs and components are set at the end of the scene. I did it that way because it is possible that a property is a reference to another object in the scene, so, it first creates all the objects, and at the end, it sets the properties. For example, a `Dog` prefab has a `rabbitToFollow` property. In the scene, the rabbit object may be created after the dog prefab. The ADDED_TO_SCENE event is fired when the object is added to the scene, so at that time, the `rabbitToFollow` property is undefined. Actually, in TS it may generate a compiler error.

I think there are so many cases, that is hard to find a solution for everything.

> So here is a constructor for a prefab that is a mix of an editor created Image for an icon and a custom BBCodeText for a text box...

Thanks for writing an example! I think I understand now. Well, I think that case is not the rule. Maybe you can use a black-box prefab for creating the BBCodeText objects. If it is something you are going to use in other projects, then you can consider making an editor plugin. Yes, I know right now it is not documented, but it will in the future.

What do you think?

**Comment by PhaserEditor2D** [comment]
> > I can add a flag to the component definition for disable firing that event.
> 
> That works as well. I was mostly thinking of ways to have the best of both worlds: get the benefit of `awake` without the extra code in the scene.ts file.

I'm liking the idea of the flag for enabling the awake events in prefabs and components. Actually, I think I will disable it by default in prefabs.

**Comment by jrabek** [comment]
Thanks for all the responses.  I totally get you have a lot of use cases to satisfy.

I'll revisit my code and see if I can come up with some other patterns that don't conflict as much with what is already there.

I think what may be helpful is a short guide on a few common coding patterns that would be used alongside the editor.  It would be opinionated but would help guide people in the right direction and you would have fewer use cases to support.

The guide could include how properties / setters should interact with the prefabs.  And how the scene would interact with the prefabs.

I imagine the guide could cover building scenes and prefabs:
1) With no 3rd party or custom components
2) A mix of editor generated and custom objects.
3) Entirely black box approach.

> If it is something you are going to use in other projects, then you can consider making an editor plugin.

That would be super cool to explore!  I already downloaded the phaser editor source and made some changes to try out some of the topics from this thread.

**Comment by jrabek** [comment]
> If you look in the code of a scene, the user properties of prefabs and components are set at the end of the scene. I did it that way because it is possible that a property is a reference to another object in the scene, so, it first creates all the objects, and at the end, it sets the properties.

So this is exactly why I thought it made sense to set the properties after the `USER-CTR-CODE` in the constructor.  

If you are going to have setters anyway then you might as well create all the objects in the scene and then set the properties at the end of the constructor so that the setters can modify any of the objects (created by the editor or user created).  Since some of the properties may even modify editor generated objects.

So I think ultimately would make sense in ordering in the constructor would be:
```
    constructor(scene: Phaser.Scene, x: number, y: number) {
        super(scene, x, y);
        
        // 1. Editor generated objects with values from the editor
        // image
        const image = scene.add.image(0, 1, "logo0002");
        this.add(image);

        // 2. USER-CTR-CODE 
        this.#textObject = new BBCodeText(scene, 0, 0, '', textStyle);
        this.add(this.#textObject);

        // 3. custom definition props
        // Note this text applies to the textObject
        this.text = "Default Text";        
    }
```

Note that if the props do *not* have custom definitions they are already defined when they are declared as public properties:
```
public text: string = "Default Text";
```
Which means they are already available in the constructor for use in init.

So it doesn't seem like having the `custom definition props` before the `USER-CTR-CODE` prevents anything but it does allow those props to be applied to the objects.

Also not sure if you read the convo with PhotonStorm I referenced (https://discord.com/channels/244245946873937922/636143808769163274/865007816727855114) but it seems like the general approach for GameObjects is to use setters for properties.  It seems that using normal javascript properties for prefab properties again means they are only useful for object init since if the scene changes the value later the prefab would need to constantly check the property in order to apply the change.

Any tips if I want to try out this change locally?

I saw that reordering the constructor is mostly straightforward except for the position of the `USER-CTR-CODE` section since it is created in `JavaScriptUnitCodeGenerator.ts` and `custom definition props` and the other code in the constructor is generated in `SceneCodeDOMBuilder.ts`.

**Comment by jrabek** [comment]
Another way to think about the constructor ordering:  How will the properties or setters (i.e. custom definition) be used?

In the case of the properties their values are set when they are declared.  This means they can be used any time in the constructor for object init, or can be changed by the scene in cases where the property change is applied later when an `update` (or some other) method is called and all the property values are applied at once.

In the case of setters, they can be used both in the constructor for setting the initial state of the objects or for changing the object state later.  In both cases the objects they are changing the state of should already be defined.  If default values are desired for object creation in the `USER-CTR-CODE ` section, the user written code can either just pass values to the custom (i.e. non editor created) objects or create private variables with default values (e.g. `#originX: number = 0;`).

I guess I am not clear on any case you would want to have the `custom definition props` before the `USER-CTR-CODE ` that couldn't be better handled by having them after.

Given it is a new feature would it break compatibility to move them to after?

**Comment by PhaserEditor2D** [comment]
Hi @jrabek!

In base the custom definition properties are a very recent addition, I think it is not going to create a compatibility issue. 

Please, can you check the latest changes in the `develop` branch? You can follow the instructions here: https://github.com/PhaserEditor2D/PhaserEditor2D-v3-build-develop

Now the custom definition properties are initialized after the USER-CTR-CODE section. If you need to add custom actions after the custom definition properties are set, then you can listen to the prefab-awake event.

This applies to prefabs and user components.

**Comment by PhaserEditor2D** [comment]
Now you can check the flags Generate Awake Event and Generate Awake Handler.

![image](https://user-images.githubusercontent.com/12187299/126007466-b28e998b-c74d-4cdf-a822-0228b7ff2e9b.png)


Only if the Generate Awake Event is checked, the `prefab-awake` event is fired in the scene. If the Generate Awake Handler is checked, then the prefab compiler registers an event handler and calls the `awake()` method. The `awake()` method should be defined by the user.

![image](https://user-images.githubusercontent.com/12187299/126007524-a0026305-9f34-4c31-9855-3db4f33c38b1.png)

This is available in the `develop` branch. You can test it following the guide I linked in the previous comment.

**Comment by PhaserEditor2D** [comment]
Added the Generate Awake Event flag to the component's parameters:

![image](https://user-images.githubusercontent.com/12187299/126023701-dabc6414-1112-4639-92ec-7fa6b52511b4.png)

in old components, the flag is checked. In new components, the flag is unchecked by default.

**Comment by jrabek** [comment]
This looks awesome @PhaserEditor2D !  Thanks for the quick change.  I'll give it a test out as soon as I can.

**Comment by jrabek** [comment]
Hey! The changes look great!

I noticed one small issue: Insertion of spaces in the `editorCreate` before initialization of each object in the scenes and prefabs
![image](https://user-images.githubusercontent.com/1304735/126146796-9c6b8581-99c7-4fd3-a89f-41d08bd749f0.png)

This completely dirties the project and makes it hard to see what changes were actually made in git.

Maybe because the `\n` is not considered a blank line and so isn't removed (https://github.com/PhaserEditor2D/PhaserEditor2D-v3/commit/8059d6a1e9f62fb28499b9c3943c4332b4c95026)?
```
body.push(new code.RawCodeDOM("\n"));
```

**Comment by jrabek** [comment]
Related to formatting and codegen as well.  Visual studio code puts spaces between variable types.
![image](https://user-images.githubusercontent.com/1304735/126792503-a4bf83bc-9688-4b3c-b0cb-e7ce5e17e46f.png)

**Comment by PhaserEditor2D** [comment]
Hi @jrabek!

I think formatting issues should be moved to a different issue.

**Comment by jrabek** [comment]
@PhaserEditor2D ok.  I can create a separate issue.  I had added it here since it seemed like a regression related to this change.  I'll try out the recent alpha first before opening an issue.

**Comment by PhaserEditor2D** [comment]
> Hi @jrabek!
> 
> I think formatting issues should be moved to a different issue.

Great, thanks. Also, please, can you check if we can close this issue?

**Comment by PhaserEditor2D** [comment]
thanks!
