### ISSUE TITLE
Alignment of typescript formatting between Phaser Editor and Visual Studio Code

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#137]
Since Visual Studio Code is the preferred editor work working with Phaser Editor 2D (https://help.phasereditor2d.com/v3/code-editor/vscode-compatibility.html), it would be nice to have a recommended set of settings or tweak the codegen so that the formatting of the generated code matches the autoformatting that Visual Studio applies to Typescript.

On https://code.visualstudio.com/docs/getstarted/settings look for the following:
```
  // Enable/disable default TypeScript formatter.
  "typescript.format.enable": true,
```

Right now if the TypeScript format on save is enabled in Visual Studio Code, it will make it seem like changes are introduced when they are just formatting changes.  Conversely, every time Phaser Editor generates the project it also makes it seems like the code has changed when in reality Visual Studio just reformatted the file.

**Comment by PhaserEditor2D** [comment]
Yes, formatting is an issue here.

I think I should make an extension for defining different formattings. I mean, a post-code generation formatter that you can plug into the editor. 

I agree at least default VSCode formatting should be respected.

**Comment by PhaserEditor2D** [comment]
Another option is, a VSCode plugin for disabling formatting in sections generated by the editor.

I think the format of the generated code is not so important. What is important is avoiding the git changes because the 
"formatting battle".

**Comment by jrabek** [comment]
Yeah, there isn't a great answer.  I was mostly thinking that the default setup should work out of the box.  Since Visual Studio Code is the larger project it seems that conforming to its default code formatting would be the way to go.  That way no one has to do anything special to setup Phaser Editor since it would "just work" out of the box.

That way you don't have to maintain a visual studio code plugin as well.  It would mean keeping up with any formatting changes that VSC makes though.

Disabling the VSC formatter for generated code doesn't seem like a great idea though since it means that you can't have consistent linting rules either.

**Comment by PhaserEditor2D** [comment]
Yes, the scene compiler, at least, should be compatible with the default VSCode formatting.

**Comment by jrabek** [comment]
Example of formatting differences from another ticket: https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/136#issuecomment-885657715

**Comment by PhaserEditor2D** [comment]
I think this is working. Can I close this issue?

**Comment by jrabek** [comment]
@PhaserEditor2D It is!  Last I checked I wasn't seeing a difference. If I see it again I'll open a new issue so we can close this one.

**Comment by PhaserEditor2D** [comment]
thanks!
