### ISSUE TITLE
[Feature Request] the ellipse shape has a weird appearance when designing in the IDE

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#138]
check these screenshot out:
![image](https://user-images.githubusercontent.com/850854/127814494-7159eeb2-e6bb-4dcd-830d-796c75467371.png)
(designing)

![image](https://user-images.githubusercontent.com/850854/127814514-f586a811-c770-4b3c-8fb0-8ce26881b8ca.png)
(but when running it just has the correct appearance)

**Comment by PhaserEditor2D** [comment]
Latest release of Phaser (3.55.2) fixes this issue.

**Comment by jcyuan** [comment]
thanks!!

**Comment by PhaserEditor2D** [comment]
welcome!
