### ISSUE TITLE
[Feature Request] add type for method in typescript

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#139]
![image](https://user-images.githubusercontent.com/850854/127856072-0f70ae08-7ae3-41fa-bfff-ec712e504c39.png)
please add type for those generated method....

otherwise:
![image](https://user-images.githubusercontent.com/850854/127856172-0da25a7f-1f34-4672-9ca9-0a7e655e4e4d.png)

😱 

thanks!!

**Comment by PhaserEditor2D** [comment]
Done.
