### ISSUE TITLE
Create a prefab with multiple sprites

### ISSUE THREAD

**Issue by Walabrolu4** [PhaserEditor2D/PhaserEditor2D-v3#14]

**Comment by PhaserEditor2D** [comment]
Hi @Walabrolu4, please, can you elaborate a bit more on your request.

**Comment by Walabrolu4** [comment]
Sorry, When I add multiple sprites and save a prefab. its the js file only adds one of them to the world.

**Comment by PhaserEditor2D** [comment]
Yes, it is the expected behavior. The only sprite at the top is considered the prefab object. If you want a prefab with multiple objects then you have to add them to a container.

**Comment by Walabrolu4** [comment]
ok! then im dumb. thank you for the clarification!

**Comment by PhaserEditor2D** [comment]
The documentation of v3 is not public/ready yet!!! You are guessing how it works :)

**Comment by PhaserEditor2D** [comment]
By the way, containers do not work very well in the alpha version, so I wish you a lot of luck!
