### ISSUE TITLE
Spaces inserted when generating code

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#140]
Originally reported here: https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/136#issuecomment-882447022

Breaking it out into a separate issue.

* Phaser Editor 2D Version: From a develop build: https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/136#issuecomment-881663997

## Description

Description in linked comment

## Possible solution

Possible solution in linked comment

**Comment by jrabek** [comment]
This seems to be resolved in 3.16 alpha.1

**Comment by jrabek** [comment]
Nevermind.  I just ran compile project and the spaces are definitely still there.

**Comment by PhaserEditor2D** [comment]
Done. Can you check?

* Removes extra spaces in blank lines
* Adds a space in type unions: before: `string|undefined`, after: `string | undefined`.

**Comment by jrabek** [comment]
For future reference: This works!  Responded in discord but also good if confirmed here :)

**Comment by PhaserEditor2D** [comment]
> For future reference: This works! Responded in discord but also good if confirmed here :)

great, thanks!
