### ISSUE TITLE
Don't change prefab x, y when positioning children in prefab

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#141]
* Phaser Editor 2D Version: v3.16.0-alpha.1

## Description
When editing a prefab and using the "select all objects inside a region" tool to move multiple children at once, it seems the coordinates of the children don't get updated correctly.

And once the coordinates aren't correct then moving individual objects results in the position not matching the coordinates on the grid.

I noticed this when moving all the children in a prefab to have a different origin (since Containers don't have an origin) so that the placement would be easier.

Position of one of the objects in the prefab
![image](https://user-images.githubusercontent.com/1304735/128174251-b53583e3-d5c5-4828-8514-2f2b883b3f65.png)

What the grid shows for the position
![image](https://user-images.githubusercontent.com/1304735/128174273-37316a0f-8f88-4879-9955-a1cbd037d703.png)

It seems that moving all objects as a group causes the Container's x and y to be updated instead of the individual objects.

From the avatar scene file after moving all objects as a group:
```
"displayList": [
        {
            "type": "Container",
            "id": "b6461c26-927e-4760-ac5f-fd6fd15b0063",
            "label": "container_1",
            "components": [],
            "x": 273,
            "y": 182,
```

This seems like a bug since the container x and y aren't used anywhere in the generated code which means it becomes hard to place prefab children without first manually resetting the x and y in the scene file to 0.

## Possible solution
Never update x and y in scene file when moving children in prefab.  Containers don't have an origin and are always assumed  to be 0,0.

**Comment by PhaserEditor2D** [comment]
Please, can you tell me what's the position of the container? I think the position of the child is not matching the grid because the container has a position in the scene.

**Comment by PhaserEditor2D** [comment]
> This seems like a bug since the container x and y aren't used anywhere in the generated code which means it becomes hard to place prefab children without first manually resetting the x and y in the scene file to 0.

That isn't a bug. If you like the children to match the grid values, then move the container to the 0,0 point.

**Comment by jrabek** [comment]
So the container is positioned at 273, 182 within the prefab scene not within the scene that is using the prefab.

It seems like the prefab's scene file should not have an x and y (or they should always be 0)

**Comment by PhaserEditor2D** [comment]
I think that's ok as it is. For example, in the development branch, now you can lock/unlock the position of a prefab. In your case, if you lock the position of the prefab in your game level, the prefab will be shown in the X,Y defined in the prefab scene.

**Comment by jrabek** [comment]
So the problem here is that adjusting the position of the children all at once in the prefab does not result in the position of the children changing it only changes the x,y in the prefab's scene file (not the game level's scene file).  The prefab's x,y recorded in the prefab's scene file is updated but that position does not appear in the generated code.

If I move individual children in the prefab then their position is updated correctly.

It seems that when editing a prefab, the x and y of the prefab in the prefab's scene file should never change.  Otherwise the grid won't match the child's position and positioning the prefab within a game level scene becomes error prone.

**Comment by jrabek** [comment]
https://user-images.githubusercontent.com/1304735/128206891-9e9cddcb-93be-4776-a4db-0983bac688b5.mp4

**Comment by jrabek** [comment]
Check out the video.  In the video you see the position of the avatar is at 183, 183.  I then move all the children of the prefab and the position of the avatar is still 183, 183.  The only thing that changed is the x,y in the prefab scene file which is not in the generated code so no actual change happened.

If I move each child individually it works as expected.

**Comment by PhaserEditor2D** [comment]
I can move this prefab instance around the scene because it has unlocked the position:

![image](https://user-images.githubusercontent.com/12187299/128206581-a813588d-7eff-452a-91c2-c9936d7a555c.png)

But if I lock the position, it will get the same position used in the prefab's scene:

![image](https://user-images.githubusercontent.com/12187299/128206700-744f74fc-3d7e-4cd0-88cc-17645f52aa7a.png)

This is the scene of the prefab:

![image](https://user-images.githubusercontent.com/12187299/128207130-8f06a602-9c4e-405d-8c1f-5cff3bfe0e6b.png)

**Comment by jrabek** [comment]
So I am not talking about the prefab once it is placed in another scene. I am only talking about editing the prefab itself and the position of its children.

**Comment by PhaserEditor2D** [comment]
If you select the objects with the "select region" tool, then it is probable that you are selecting the prefab's container too, so you are not changing only the children position:

![image](https://user-images.githubusercontent.com/12187299/128207963-1410234c-acea-4c64-986a-37677316ad55.png)

**Comment by PhaserEditor2D** [comment]
Just select the children:

![image](https://user-images.githubusercontent.com/12187299/128208115-11278f68-0495-4b3f-af99-fef37247d150.png)

**Comment by jrabek** [comment]
Yeah, I guess it still seems strange to me for a prefab to have an arbitrary position offset (rather than just 0,0).  It seems like any position offset should be entirely handled by the scene that is using the prefab.  Having a position offset for the prefab just makes it more complex to reason about.

It is perfectly normal for individual children to have position offsets within the prefab, but for there to be an overall position offset seems odd.  It it hard to notice in the prefab editor, makes the grid not line up, and then when using the prefab if you want the prefab to be centered you'd have to apply the opposite offset in the scene.  I guess I don't see the purpose at the moment.

Are there examples you've found where it would be useful?

**Comment by jrabek** [comment]
> By the way, thanks to this conversation I realized did not update the container's code dom builder :)
> 
> [d2de78e](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/commit/d2de78ed52831e598167ea42573b25776103ea05)

Glad to hear :)

**Comment by PhaserEditor2D** [comment]
> Are there examples you've found where it would be useful?

Yes, for making "static" prefabs.

Look this scene:

![image](https://user-images.githubusercontent.com/12187299/128210449-bd3c8953-def3-4b43-91f5-2b72fa7435d6.png)

The selected element is a footer that is shown in all the scenes of the game. I can make it using a rect and a text so I don't have to use an image. I make it a prefab and I drop it in all the scenes. If I lock the position, then it will be positioned in the bottom of the scene, where it should be.

Before, I was using a prefab with a layer, for keeping the absolute positions.

Another example may be the HUD of a game.

I know it could be a bit weird at first, but it is more consistent with the way prefab works. Why the position must be the exception to the rule?

**Comment by PhaserEditor2D** [comment]
But the strongest reason is, that it is needed by nested prefabs! When you have a nested prefab, you need to lock/unlock the position of the elements.

**Comment by PhaserEditor2D** [comment]
And yes, maybe also excluding the root container when using tools like the "select region" and "select all". If you want to select the root container, you can do it by pointing it in the Outline view. What do you think?

**Comment by jrabek** [comment]
So I guess the disconnect here is that I see the prefab's container transform related properties as irrelevant when editing the prefab.  They are properties that should be set by the parent of the prefab since they only matter there.  This is the same way that Unity's prefabs work that inspired the Phaser Editor prefabs.

For the nested prefab example, I would structure it so that rather than the child prefab having a baked in position, the parent prefab should position its children where needed.  That way if the child is reused in another nested prefab it isn't as some non 0,0 offset that needs to be accounted for.  It makes prefabs unreusable. 

This is the same way that the other Phaser game objects work. Images don't have a built in offset when placed in the scene. Why should prefabs be any different?

In your example https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/141#issuecomment-892765025 I would structure it so that the footer is a prefab by itself at offset 0,0 and can be inserted into each scene at the bottom but it is possible that the footer is used later as a label in the middle of the scene.  Again the parent should care about placement.

**Comment by jrabek** [comment]
> And yes, maybe also excluding the root container when using tools like the "select region" and "select all". If you want to select the root container, you can do it by pointing it in the Outline view. What do you think?

This would avoid the issue I saw and a user of the editor would have to be more explicit about changing the position of the container which to me is a less common operation.  That said, I still don't understand the benefit of changing the inherent position offset of a prefab.

If you have a clear plan with this one definitely proceed!  I am just raising what I see as an inconsistency with other phaser objects and with prefabs in unity.

**Comment by PhaserEditor2D** [comment]
> In your example #141 (comment) I would structure it so that the footer is a prefab by itself at offset 0,0 and can be inserted into each...

I don't agree with it :). I had to create lot of scenes with that footer and positioning it is disturbing when you know it has always, for ever, an absolute position. But ok, it can be wrapped in a layer and it will get always the same absolute position.

> Images don't have a built in offset when placed in the scene

Yes, it has, at 0,0.You can try this:

```javascript
const img = new Phaser.GameObjects.Image(this);
img.setTexture("dino");
this.add.existing(img);
```
But ok, it isn't declared as optional in typescript.

> For the nested prefab example, I would structure it so that rather than the child prefab...

What is needed for nested prefabs, is the option of locking/unlocking the position of a nested prefab instance:

![image](https://user-images.githubusercontent.com/12187299/128216966-822cad93-246e-48e2-b14d-3264e010376e.png)

> I see the prefab's container transform related properties as irrelevant when editing the prefab...

I agree it is the case in the 99% of the cases. There are operations the editor does when you are working in a prefab. For example, if you have a prefab of an image, but you add a second image, it will create a container for grouping both objects. In the early versions, you had to create the container yourself. My personal preference is to have control of "every" detail, and knowing what's happening at every step. But that's true this kind of automation makes it more friendly to the editor.

In this case, maybe I can do the following:

* When you create a prefab of a container, position it at 0,0.
* Never select the container unless you do it explicitly in the Outline view.

Another option is hiding the container object in the prefab scene, but the problem with it is that maybe you want to add components to the container, or change its scale or angle. I don't know how is it in Unity, maybe all transform properties should be set in the prefab instances and not in the prefab's scene? Maybe I can always hide the transform properties of the prefab scene?

**Comment by jrabek** [comment]
Yeah, I think at this point you have a clearer vision of what you want to do and how it satisfies other needs.

I would still handle the footer as two separate prefabs, one for the footer itself and then a separate one that contains a footer where the footer prefab is placed at the bottom.  That way the footer prefab itself could be reused elsewhere more easily.

I think your suggestion of making it harder to modify the offset of the container when using the multi selection tool is a good one since most of the time you don't want to change the prefab container's position.  An additional future improvement would be to indicate the position of the container so it is obvious when it isn't 0,0.

Good discussion and thanks for the details!

**Comment by PhaserEditor2D** [comment]
> I think your suggestion of making it harder to modify the offset of the container when using the multi selection tool is a good one since most of the time you don't want to change the prefab container's position. An additional future improvement would be to indicate the position of the container so it is obvious when it isn't 0,0.

Good, then I will go for it. In any case, if we find it has other issues, we can go back and improve it. Thanks to you for pushing and explaining your points!
