### ISSUE TITLE
values are restored when you focus to the same item again in the animation editor

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#142]
when i select an animation from the left frame, i can edit its properties now in the right frame, then i change all the values in it, but it seems there will be only one property will be updated in a batch change because when i select this item again, i see only one item was updated.

see this video:

https://user-images.githubusercontent.com/850854/128988422-6d286326-0925-44ea-b4ca-18f43df2de20.mp4

if i need to change these 5 properties, i have to select the same item 5 times....

**Comment by PhaserEditor2D** [comment]
Humm... I will test it tomorrow, but I think the problem is that you are changing the key of the animation and the editor loses the path to it.

**Comment by jcyuan** [comment]
> Humm... I will test it tomorrow, but I think the problem is that you are changing the key of the animation and the editor loses the path to it.

ok, thanks, but i think this is not the point, because i select the changed item again, i still need to change those values one by one.

**Comment by PhaserEditor2D** [comment]
Fixed. You can test it in the `develop` branch:

https://github.com/PhaserEditor2D/PhaserEditor2D-v3-build-develop

**Comment by jcyuan** [comment]
just tested and it seems it was fixed. thanks.

**Comment by PhaserEditor2D** [comment]
Good, thanks.
