### ISSUE TITLE
Copying and pasting bitmap text field between different scenes does not work

### ISSUE THREAD

**Issue by jorgeovi** [PhaserEditor2D/PhaserEditor2D-v3#143]
## Version

* Phaser Editor 2D Version: 3.15.0

* Operating System: Windows 10

* Web Browser and version: Chrome 93.0.4577.82 (Build oficial) (64 bits)

## Description

Easy to reproduce, create a new javascript webpack project, add a second scene, import some bitmap text files, create a bitmap text field on scene 1. Try copying and pasting it to the second scene... does nothing.

Get this error on the console:
![image](https://user-images.githubusercontent.com/6459471/134471098-ad45e207-458a-4786-a6dc-9e55c8bde3d2.png)

**Comment by PhaserEditor2D** [comment]
I can reproduce the error. Thanks!

**Comment by PhaserEditor2D** [comment]
Fixed.

What's your OS? I uploaded here a Windows version with the fix: [PhaserEditor2D-core-3.30.0-next-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/7237497/PhaserEditor2D-core-3.30.0-next-windows.zip)

Please, can you test it?

It also includes the maxWidth property requested #145
