### ISSUE TITLE
More properties for Bitmap Text class

### ISSUE THREAD

**Issue by jorgeovi** [PhaserEditor2D/PhaserEditor2D-v3#145]
I'm missing being able to edit some Bitmap Text properties directly on the editor. I would add

- maxWidth property to define the width at which the lines will wrap.
- setLetterSpacing method to define the kerning

Could not find a property or method to adjust leading (distance between two lines) so maybe this is not possible, but it would also be useful.

**Comment by PhaserEditor2D** [comment]
Good. I will work on this. Thanks.

**Comment by PhaserEditor2D** [comment]
Done

![image](https://user-images.githubusercontent.com/12187299/134938846-9d06ccf9-015a-4f3a-8dbe-bd31625ae6e0.png)

By the way, the `letterSpacing` was there, I just had to implement `maxWidth`.

**Comment by PhaserEditor2D** [comment]
You can download the binaries attached here https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/143#issuecomment-927986585

And test if it works.
