### ISSUE TITLE
Minor formatting issues when generating Typescript code

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#147]
* Phaser Editor 2D Version: 3.30.0
* Operating System: Mac

## Description

Two minor formatting issues when generating Typescript code that differs from how Visual Studio and default eslint Typescript rules format.

Note that the diffs below were from how Phaser Editor generated the project vs how Visual Studio Code did its default formatting.  So the `-` is the Visual Studio Code version and the `+` is what Phaser Editor changed it to.

1) Spacing within an Object declaration:
```
-        text.setStyle({ "align": "center", "fontFamily": "Chisel Mark", "fontSize": "96px" });
+        text.setStyle({"align":"center","fontFamily":"Chisel Mark","fontSize":"96px"});
```

2) Semicolons at the end of list declarations

```
-        const titleButtons = [titleButton1, titleButton2, titleButton3];
+        const titleButtons = [titleButton1, titleButton2, titleButton3]
```

**Comment by PhaserEditor2D** [comment]
Done.
