### ISSUE TITLE
Wrong arguments passed for blackbox prefab based on NinePatch 

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#148]
* Phaser Editor 2D Version: 3.30
* Operating System: Mac

## Description

When creating a [black box prefab](https://help.phasereditor2d.com/v3/scene-editor/prefab-black-box.html) based on a [NinePatch object](https://github.com/PhaserEditor2D/PhaserEditor2D-v3-extras/tree/main/source/plugins/phasereditor2d.extras.ninepatch) in order to add custom fields to the prefab, it seems the arguments passed to the prefab constructor are incorrect.

Here is what the init looks like for a black box prefab that has a type in the prefab scene file of NinePatch.
```
        // scaledTextBox
        const scaledTextBox = new ScaledTextBox(this, 123, 124, 123, 124, undefined, undefined, "button0004");
        this.add.existing(scaledTextBox);
```

Here is a NinePatch created as just a NinePatch (no prefab involved).
```
        // ninepatch
        const ninepatch = this.add.ninePatch(674, 478, 373, 216, "button0004");
        ninepatch.setOrigin(0, 0);
```

In the case of the prefab the x,y coordinates are repeated twice and there are two unknown `undefined` parameters and then the texture key.  The width and height are not passed in.

**Comment by jrabek** [comment]
@PhaserEditor2D Ah perfect.  Yeah I have only recently been digging into the Phaser Editor code more deeply so I wasn't completely sure!  

And your fix makes total sense.  I actually was curious why a new width and height property was needed but what you are saying makes sense.

When building the auto scaling text box since scaling the text is expensive, I use the `dirty` flag approach and only do any sort of update on the next `update` call all at once to avoid expensive recalculations / redraws.

Thanks for the quick turn!

**Comment by PhaserEditor2D** [comment]
Good. Yes, I should do something similar to the `dirty` flag in the editor implementation of the ninepatch object. In the ninepatch class provided to the user, maybe it is a strategy the user can implement himself. I think the code is pretty straight forward and you can change the internals. Only the public interface should remain the same.
