### ISSUE TITLE
Copying a Container does not rename children GameObjects

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#149]
## Version

* Phaser Editor 2D Version: v3.30.0

* Operating System: Windows 11

* Web Browser and version: Chrome 94.0.4606.81

## Description
When you copy a container, it does not add `_1` to its children, and the names remain the same, causing errors that people might miss until they look at the JavaScript.

![image](https://user-images.githubusercontent.com/9307505/137881527-429c0763-280b-41b9-96cb-15ec7f694998.png)

## Possible solution
This can be fixed by adding a number after Container children that are copied.

**Comment by MerlinEl** [comment]
There will also help some type of macro. That can rename selected items in batch.

**Comment by PhaserEditor2D** [comment]
Done.
