### ISSUE TITLE
Blurry Text

### ISSUE THREAD

**Issue by NickChowHK** [PhaserEditor2D/PhaserEditor2D-v3#15]
![image](https://user-images.githubusercontent.com/10241183/81694321-c71ea880-9493-11ea-90fd-4d23ebee2fea.png)

I am using Macbook Pro 16", no idea why there is some Blurry Text displayed as above picture.

**Comment by PhaserEditor2D** [comment]
Hi, I missed this issue.

Please, can you tell whats the resolution of your screen?

Try with a lower resolution, with 1920x1080, just to see if it is a resolution problem.

**Comment by NickChowHK** [comment]
![image](https://user-images.githubusercontent.com/10241183/81953353-23bbc800-963a-11ea-920e-7eab69557e63.png)
The above image captured from the resolution (1792 X 1120). It seems the issue is not relative to the screen resolution.

**Comment by PhaserEditor2D** [comment]
I see... Please, what's your browser? I should do a research about it. The blurry texts you see are painted in a canvas element, they are not HTML texts.

**Comment by NickChowHK** [comment]
My browser: Google Chrome, Version 81.0.4044.138 (Official Build) (64-bit)
Please let me know the answer. I also facing the same problem in my Phaser Game. The temporary solution for me is text.setResolution(2) and text.setScale(2).

**Comment by PhaserEditor2D** [comment]
Please, can you open the Chrome DevTools console and type `devicePixelRatio`:

![image](https://user-images.githubusercontent.com/12187299/82038180-2685df80-9671-11ea-84ba-a000521d3302.png)

I think we have this problem: https://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by PhaserEditor2D** [comment]
Hi @NickChowHK 

Regarding your Phaser game, for now, you should do it yourself. You can read about it in this DevLog of Phaser: https://phaser.io/phaser3/devlog/123

**Comment by NickChowHK** [comment]
> Please, can you open the Chrome DevTools console and type `devicePixelRatio`:
> 
> ![image](https://user-images.githubusercontent.com/12187299/82038180-2685df80-9671-11ea-84ba-a000521d3302.png)
> 
> Tell me your value. I think we have this problem: https://www.html5rocks.com/en/tutorials/canvas/hidpi/

The console show devicePixelRatio = 2

**Comment by PhaserEditor2D** [comment]
Hi @NickChowHK 

I did several changes to support HiDPI, please, can you test this release:

[PhaserEditor2D-3.0.0-macos.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/4636248/PhaserEditor2D-3.0.0-macos.zip)

**Comment by PhaserEditor2D** [comment]
When you open the browser, please, ensure you clear the cache, to get the latest version of the files.You should see this message in the console:
![image](https://user-images.githubusercontent.com/12187299/82082228-a2098000-96b5-11ea-9a6e-eee91cab36a2.png)

**Comment by NickChowHK** [comment]
![image](https://user-images.githubusercontent.com/10241183/82105504-3aebda00-974e-11ea-9eb5-48e559e6827c.png)

@PhaserEditor2D Many Thanks. The editor displays the text much clearly now.

**Comment by PhaserEditor2D** [comment]
Great @NickChowHK 

I will close this issue. Please, if you find any other issue, for example with the position of the dialogs, or the size of icons in the UI, you can open another issue.
