### ISSUE TITLE
feat: A way to change the default "game url" 

### ISSUE THREAD

**Issue by vlladislav45** [PhaserEditor2D/PhaserEditor2D-v3#156]
It will be great UX to us like developers to have a way to run directly our games  in the editor instead to use browsers everytime when we use webpack-dev-server.

**Comment by PhaserEditor2D** [comment]
Done.

Now you can set the "playUrl" in the `phasereditor2d.config.json` file.

```json
{
  "playUrl": "http://localhost:4200/"
}
```

This file is something new for the next release. It should be created at the root of the project and provides other settings like plugins, file filtering, server flags...
