### ISSUE TITLE
Uploading a file fails with an `invalid-name`.

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor2D-v3#160]
(Issue reported in Discord server by Cold Cut Charlie)

## Version

* Phaser Editor 2D Version: 3.31.0

* Operating System: Windows

* Web Browser and version: Chrome

## Description

I have a puzzle for anyone willing to help me solve it. I'm on a windows machine and when first opening PhaserEditor2D and creating a project it clones one of the templates into the folder I created and then closes. As long as that new template folder is in place the Application will start with a white screen and then quickly close. I can however then using the terminal change directory to the folder with the server instance of the editor and run the project using the -project flag. The editor opens in the browser, but will not accept any changes can not add files can not delete when I do attempt to add an image for example the console states, "Copying file C:\Users\JAMESK~1\AppData\Local\Temp\phasereditor-upload-051835975.tmp to invalid-name". It seems like it is a read write permission issue but what do I know, have tried giving all users full read write permission to the template folder same results... Anyway Any help would be appreciated :).

**Comment by PhaserEditor2D** [comment]
Hi. I made a version of Core that prints some debug messages. Please, try to reproduce the error and show me the output.

[PhaserEditor2D-core-3.31.0-next-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/7674951/PhaserEditor2D-core-3.31.0-next-windows.zip)

**Comment by Bellusterra** [comment]
=> Open the web browser at http://127.0.0.1:1959/editor

2021/12/08 19:50:11 No updates available.
2021/12/08 19:50:11 Opening browser at http://127.0.0.1:1959/editor
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\dino.png
C:\PhaseEditor2D-3.31.0-Test
2021/12/08 19:50:11 open invalid-name: The system cannot find the file specified.
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\guapen.png
C:\PhaseEditor2D-3.31.0-Test
2021/12/08 19:50:11 open invalid-name: The system cannot find the file specified.

**Comment by PhaserEditor2D** [comment]
Hum. It looks like an encoding issue. Please, can you test again with the binaries and paste here the output?

[PhaserEditor2D-core-3.31.0-next-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/7685413/PhaserEditor2D-core-3.31.0-next-windows.zip)

**Comment by Bellusterra** [comment]
=> Open the web browser at http://127.0.0.1:1959/editor

2021/12/10 07:14:52 Opening browser at http://127.0.0.1:1959/editor
2021/12/10 07:14:52 No updates available.
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\dino.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\guapen.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\dino.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\src\scenes\Level.js
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\src\scenes\Level.scene
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false

This works! I mean I'm able to remove the file and change the scene, save it and have the changes show up when I run the game.

**Comment by Bellusterra** [comment]
Uploading Images works as expected too.

**Comment by PhaserEditor2D** [comment]
Hi @Bellusterra 

That's great.

I think it is an encoding problem. Please, can you do this test? Use the same binaries I provided in the previous comment.

* Open the CMD
* Change the directory to the root of your project
* Launch the editor server in this way:
```
PhaserEditor2D.exe -project .
```
* Make the same thing: upload a file, etc.... and show me the output.

Thanks!

**Comment by Bellusterra** [comment]
=> Open the web browser at http://127.0.0.1:1959/editor

2021/12/11 07:13:39 No updates available.
2021/12/11 07:13:39 Opening browser at http://127.0.0.1:1959/editor
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\dino.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\guapen.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\assets\dino.png
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\src\scenes\Level.js
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false
ConvertToProjectPath:
C:\\PhaseEditor2D-3.31.0-Test\src\scenes\Level.scene
C:\PhaseEditor2D-3.31.0-Test
HasPrefix:  false

**Comment by PhaserEditor2D** [comment]
Ok thanks!
