### ISSUE TITLE
Input can't be focused.

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#161]
i can't remember if this existed before in the older IDE (my last project)
for the IDE i'm now using: V3.31.0

F2 to rename, create object as prefab with the selected object, etc anyway if there is the text input on the dialog,
you can't foucs to it, double click will select the text in the input:
![image](https://user-images.githubusercontent.com/850854/145187076-31683421-e7eb-4e40-ae32-c6c2e3b48308.png)
(when the problem appears, the input does not have the orange rectangle, this image is a working normal screenshot)

i can't remember how to reproduce.. sometimes it appears, but i know how to solve it: just send the whole IDE to background and then switch back, the input on the dialog will be focused....

**Comment by PhaserEditor2D** [comment]
Hi.

Are you running All in One or Core? Are you running the editor in what browser?

**Comment by jcyuan** [comment]
> Hi.
> 
> Are you running All in One or Core? Are you running the editor in what browser?

All in one version

**Comment by PhaserEditor2D** [comment]
Probably it is an Electron issue.

Check it happens after an "alert" message appears.

**Comment by jcyuan** [comment]
> Probably it is an Electron issue.
> 
> Check it happens after an "alert" message appears.

i will update this issue about how to reproduce later when i encounter it again.

**Comment by PhaserEditor2D** [comment]
If you can record a small video will be great. Thanks.

**Comment by jcyuan** [comment]
> If you can record a small video will be great. Thanks.

ok! i will later

**Comment by jcyuan** [comment]
i didn't see this issue recently after i reported it, strange.

what i can recall only is my PC was very very slow...  not sure if it's the case.

let me close this for now, if it appears again later i will reopen this. thanks.
