### ISSUE TITLE
wrong coord value generated for a prefab

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#162]
newest version v3.31.0 all in one

![image](https://user-images.githubusercontent.com/850854/145390528-5bdb2c12-973c-4028-8592-4e03329c1eff.png)

this is the coord generated, i don't know where does this -17 come from.

in IDE:

![image](https://user-images.githubusercontent.com/850854/145390703-575ac12c-dcd9-4fc0-854e-fc0c22a3d2f2.png)

it's x=0, y=0, but the position seems not right.

**Comment by jcyuan** [comment]
> Hi!
> 
> The second image is the prefab scene or is it another scene with a prefab object? Also, please, select the object and show me the X, Y values in the Transform section of the Inspector view.

that's my prefab scene.

and these xy values in the transform section is still 0:

![image](https://user-images.githubusercontent.com/850854/145514266-5a2ca5b5-50a9-44c4-83b9-f45f8e99d19c.png)

**Comment by PhaserEditor2D** [comment]
That's strange. Please, can you show me here the content of the `Block.scene` file? Also please re-compile the scene and show here the `Block.ts` content.

**Comment by jcyuan** [comment]
in the Block scene there are only 2 block images:
![image](https://user-images.githubusercontent.com/850854/146160336-c8d761c8-6566-4afe-b825-8924671c2b50.png)

and Block.ts content:
![image](https://user-images.githubusercontent.com/850854/146160453-fef8fd7f-4617-4bf0-bf37-7eca275c47fa.png)

the IDE somehow generates a -17 for the y coordinate i don't know why.

**Comment by PhaserEditor2D** [comment]
Click on the container (Block) in the Outline view. Check the Transform properties, it has X=0, Y=-17.

**Comment by jcyuan** [comment]
> Click on the container (Block) in the Outline view. Check the Transform properties, it has X=0, Y=-17.

😅 yes, i'm so sorry, you are right, i found it....

**Comment by PhaserEditor2D** [comment]
great!
