### ISSUE TITLE
about the TS declaration the IDE generated for the items.

### ISSUE THREAD

**Issue by jcyuan** [PhaserEditor2D/PhaserEditor2D-v3#164]
for now the declaration is like this:

    private obj: Phaser.GameObjects.Image | undefined;

this is actually good, for a user class, if you don't initialize your member at the constructuring time, you have to define it as `?: Type` (optional member, or `: Type | undefined`, the are the same), and later you need to always check your member if it's whether undefined or not:

      obj?.foo();    // if it's undefined, don't call foo
      obj!.foo();    // i'm sure obj is defined, just call foo for me

but for PE2D, those objects created from IDE, they are absolutely always defined, because they will be always initialized in the `create` function, so, suggest that directly define them as `!: Type`, so that later we don't need to always call `obj!.foo` with an unnecessary `!` check symbol, but just directly call `obj.foo()`, this i personally think is better.

see anyone have other thoughts, welcome.

thanks.

**Comment by PhaserEditor2D** [comment]
Done. Thanks!
