### ISSUE TITLE
Add Object Tile Map doesn't work

### ISSUE THREAD

**Issue by crapthings** [PhaserEditor2D/PhaserEditor2D-v3#165]
![image](https://user-images.githubusercontent.com/1147704/146669752-8a66f703-4b42-43f7-8a1c-510dac3a4b3e.png)

after clicking next, it shows an empty modal

![image](https://user-images.githubusercontent.com/1147704/146669755-058b0aa8-f5c1-4dab-93e8-53cefbd6b213.png)

then click next again, I can't finish add tilemap layer

![image](https://user-images.githubusercontent.com/1147704/146669788-f1bc425a-c533-466d-90e9-e0696a9bc7db.png)

**Comment by PhaserEditor2D** [comment]
Hi. Please, can you check in the DevTools of the browser if there is any error?

**Comment by crapthings** [comment]
it works for now

maybe some conditions trigger bug, but I've check again it works.
