### ISSUE TITLE
Down Arrow in Command Palette closes palette, moves select Image in Scene Editor

### ISSUE THREAD

**Issue by michaelgundlach** [PhaserEditor2D/PhaserEditor2D-v3#168]
## Version

* Phaser Editor Version: 3.31.2

* Operating system: WSL on Windows 10

## Description

In Scene Editor, select an Image.
Press Ctrl-K to open Command Palette.
Type "origin"
Press down arrow key two times.

Expected: highlight the 3rd item in the palette search results (Set Origin To Bottom/Center)
Actual: 2nd down arrow key closes the Command Palette and increments the .y value of the selected Image. 

## Possible solution

Use the mouse (or the numpad if I had one on my laptop ;)

**Comment by PhaserEditor2D** [comment]
I can reproduce this, thanks.

**Comment by PhaserEditor2D** [comment]
Done.
