### ISSUE TITLE
Consistent use of "Import" throughout editors

### ISSUE THREAD

**Issue by michaelgundlach** [PhaserEditor2D/PhaserEditor2D-v3#170]
...because the action is already called "Import" in the Asset Pack Editor Inspector, as in "Import Image".

I suggest "Import File To Asset Pack" rather than "Import File", because when my eyes wander to the top of the screen and see that command, I don't know what context it is in -- am I importing to the project?  The asset pack?  The scene? -- without checking elsewhere on the screen to see which Editor is active.  (If the menu bar contained the name of the editor, e.g. "*Asset Pack Editor  >*  + Import File", that would also clarify it, but that's a harder change.)

**Comment by michaelgundlach** [comment]
I'll send a PR.

**Comment by PhaserEditor2D** [comment]
> I'll send a PR.

Yes.

**Comment by michaelgundlach** [comment]
PR ready - after lots of thought and exploration of the UI and code, I went the other direction, replacing "Import" in the UI with "Add" to align with the other editors' use of Add (Add Component, Add Object.)

**Comment by michaelgundlach** [comment]
I'll take a crack at the docs PR as well

**Comment by michaelgundlach** [comment]
Fixed in the PR
