### ISSUE TITLE
Clicking a method in Code Editor Outline view focuses the method

### ISSUE THREAD

**Issue by michaelgundlach** [PhaserEditor2D/PhaserEditor2D-v3#173]
Right now, clicking e.g. "editorCreate" in the Outline view for Preload.js does nothing, instead of taking you to the code.

**Comment by PhaserEditor2D** [comment]
Hi. Is it using all in one or core? And what project template it used? I need to reproduce the bug here locally.

**Comment by michaelgundlach** [comment]
Oh, I didn't realize this was a bug, I thought it was a feature request lol.

Core, Phaser Editor v3.31.2-next, JS project template.  Repro:

Load editor
Double click PushToClick.js in Files view
Click or double click "awake" in Outline view

Expected: focus "awake" in Script Editor
Actual: "awake" is selected orange (in Dark theme) in Outline view upon click but the Script Editor does not move

**Comment by PhaserEditor2D** [comment]
But Core doesn't provide any Outline content:

![image](https://user-images.githubusercontent.com/12187299/148401530-015722dd-b684-4bed-8b1c-a57463617619.png)

In Core, it only uses a basic CodeMirror editor for syntax highlighting. The Monaco editor (the one with advanced features) is only available in All in One.

I guess you are running the editor using the develop branch and pointing to the editor's source code with the `-editor` flag?
In that case, you should ignore the code mirror editor plugin or the monaco plugin, using the `-disable-plugins` flag.
Something like `PhaserEditor2D -editor /path/to/editor -disable-plugins phasereditor2d.codemirror`.

**Comment by michaelgundlach** [comment]
Yep, that was my problem!  Two questions

1) Is there a reason to exclude the Monaco editor from Core?  Like a licensing reason or something?  I get that VSCode is better, but for those of us who would like to code inline, Monaco is so much nicer.

2) Shall I send a PR updating the BUILD.md to tell users to use `-disable-plugins`?

**Comment by PhaserEditor2D** [comment]
> 
>     1. Is there a reason to exclude the Monaco editor from Core?  Like a licensing reason or something?  I get that VSCode is better, but for those of us who would like to code inline, Monaco is so much nicer.

The Monaco editor adds a lot of extra work on the client-side. It parses all js files. I excluded it from Core because there are better options. Core is for advanced uses, like developing in the cloud or installing the editor as a versioned dependency of the project (via npmjs https://www.npmjs.com/package/phasereditor2d-launcher). You can use vscode locally or vscode remotely (GitHub Spaces, etc...).

I just included Monaco in the All in One distribution thinking more on the users who want to code the game with vanilla javascript and don't want to use any other third-party tool. But for making a professional or a bigger game the recommendation is using a modern stack like vscode + webpack + typescript.

> 
>     2. Shall I send a PR updating the BUILD.md to tell users to use `-disable-plugins`?

**Comment by PhaserEditor2D** [comment]
> Hmm... I used -disable-plugins and still got the Monaco editor.
> 
> ![image](https://user-images.githubusercontent.com/5141333/148411531-986d7f50-b572-4976-aac8-9156a5e5a503.png)
> 
> ![image](https://user-images.githubusercontent.com/5141333/148411722-d305e07f-ac0f-4d30-8a48-f59b733c2dc7.png)
> 
> Strangely, when I went to get the screenshot I found that I _COULD_ click the Outline view to move around the script file, but then when I tried to get a repro for you the behavior stopped (I'm back to no movement).

I think you missed to write `-disable-plugins phasereditor2d.code`.

**Comment by PhaserEditor2D** [comment]
Yes, please, update the BUILD.md file.

I have here in my internal TODO a task for implementing plugin profiles. So the server can load a profile like Core or All in One. But it is not a priority right now.

Thanks!

**Comment by michaelgundlach** [comment]
Filed #177.

Closing this Issue
