### ISSUE TITLE
Setting User Component superclass after creation breaks compiler

### ISSUE THREAD

**Issue by michaelgundlach** [PhaserEditor2D/PhaserEditor2D-v3#178]
## Version

* Phaser Editor 2D Version: 3.31.2

* Operating System: Windows 10 WSL

* Web Browser and version: Chrome 96

## Description

Repro:
Create a new project called 'breakout' using the Basic Typescript template.
```
cd breakout
npm install
npm run watch  # Start typescript compiler
```

Start the editor:
```
cd breakout
npm run editor
```

In the editor:

Double click Behaviors.components to open the Components Editor.
Press A to create a new class "Component".
Press Ctrl-S to save.
Click the Superclass field in the Property pane.
Choose "User Component" from the dropdown to cause Component to inherit from User Component.
Press Ctrl-S to save.
Look at the `npm run watch` console.

Expected: success.

Actual: game.js lists `class Component` before `class UserComponent`, so we get this error:
![image](https://user-images.githubusercontent.com/5141333/148445833-04245339-53d1-4fb9-872f-4415fb8a949f.png)

## Possible solution

I don't think this is me being new to TypeScript, because I haven't touched a line of code or changed any of the default settings.

**Comment by michaelgundlach** [comment]
It's even simpler than I thought, which makes me worry that I *must* be doing something wrong.  I can clone the Basic Typescript template, run `npm run install && npm run build && npm run editor`, press A in Behaviors.components, choose the UserComponents superclass for the new `Component` class, press Ctrl-S to save, and run `npm run build` again.  Same error.

![image](https://user-images.githubusercontent.com/5141333/148449372-5948bfd0-40f3-4a7d-b784-8e3c4fc72200.png)

**Comment by PhaserEditor2D** [comment]
You have to "import" the `UserComponent.ts` file using the `reference` three slash directive:

https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

**Comment by PhaserEditor2D** [comment]
Add this in the first line:

```javascript
/// <reference path="./UserComponent.ts"/>
```

**Comment by michaelgundlach** [comment]
That's not in the tutorial - should I add it to the tutorial or open a bug report to have the compiler generate that line when it generates Component.ts?

**Comment by PhaserEditor2D** [comment]
The compiler should not generate that line because you can write there any class, placed in any file, and it is way too complex to know what file should be imported.

Also, in the JS world, there are many "module" implementations, ES modules, CommonJS modules, typescript namespaces, etc...

Maybe mentioning it in the docs has more sense but yet there are so many options that I think teaching all of them is out of the scope of the editor. Knowing OOP, TS, JS, Phaser, is a requirement for working with the editor.

**Comment by michaelgundlach** [comment]
OK, fair enough, thanks for the explanation :)

**Comment by PhaserEditor2D** [comment]
welcome!
