### ISSUE TITLE
Improve generation of TypeScript scene variables

### ISSUE THREAD

**Issue by ksmit799** [PhaserEditor2D/PhaserEditor2D-v3#180]
Bit of a small nit-pick, but makes for more readable TypeScript code. Currently, scene components in TypeScript are generated as follows:
```typescript
private backButton: Phaser.GameObjects.Rectangle | undefined;
private createButton: Phaser.GameObjects.Rectangle | undefined;
private forgotButton: Phaser.GameObjects.Rectangle | undefined;
```

TypeScript has a shorthand (cleaner) way of marking variables as possibly undefined. **The optional operator (?)**:
```typescript
private backButton?: Phaser.GameObjects.Rectangle;
private createButton?: Phaser.GameObjects.Rectangle;
private forgotButton?: Phaser.GameObjects.Rectangle;
```

**Comment by PhaserEditor2D** [comment]
Hi!

Is this the same case of #164?

**Comment by ksmit799** [comment]
> Hi!
> 
> Is this the same case of #164?

Yes! That's a better solution then defining it as `undefined`.
