### ISSUE TITLE
A Color type for user properties

### ISSUE THREAD

**Issue by ksmit799** [PhaserEditor2D/PhaserEditor2D-v3#181]
Currently, default values for number prefab properties only accept base-10. The current workaround is to create a new expression property and set the expression type as a number (see below).
![unknown](https://user-images.githubusercontent.com/3006587/149455180-45077a0b-7355-4baa-899b-78b0097de87a.png)

**Comment by PhaserEditor2D** [comment]
Yes, we need an hex number type, to keep the hex format.

But tell, do you need it for a color? Because a Color property type has a lot of sense.

**Comment by ksmit799** [comment]
> Yes, we need an hex number type, to keep the hex format.
> 
> But tell, do you need it for a color? Because a Color property type has a lot of sense.

Yes, it's for a color. A color type would definitely be helpful.

**Comment by PhaserEditor2D** [comment]
I think a color property type has more sense. Maybe a Number Color and an HTML Color property.

**Comment by PhaserEditor2D** [comment]
Done. We have now a Color property type.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/12187299/162605726-fac93fcf-3080-4f7e-acc6-d462f6ea3e30.png">
