### ISSUE TITLE
Component Option Type Scroll Issue

### ISSUE THREAD

**Issue by talhaozdemir** [PhaserEditor2D/PhaserEditor2D-v3#183]
## Version
* Phaser Editor 2D Version: v3.32.0

* Operating System: Windows 10

* Web Browser and version: Google Chrome 97.0.4692.99 (64 bit)

## Description
If I add many strings to the option type in component menu, some options are not visible on the screen, and I cannot scroll the option area also.

## Possible solution
A scrollbar can be added.

![unknown](https://user-images.githubusercontent.com/37840852/151191322-12c58bb8-6fe2-4f3a-966d-70a06ef240a7.png)

**Comment by PhaserEditor2D** [comment]
Done.

I will release a beta version soon, so you can test it. Please, follow the releases of the repo.

![image](https://user-images.githubusercontent.com/12187299/155075615-6171d047-a9c8-49f8-bb6a-16345f813563.png)

**Comment by PhaserEditor2D** [comment]
Hi. I just released PhaserEditor2D v3.32.1-beta.1 with the fixes for this issue.

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.32.1-beta.1

**Comment by PhaserEditor2D** [comment]
Great!
