### ISSUE TITLE
Cannot save game when cursor is active

### ISSUE THREAD

**Issue by talhaozdemir** [PhaserEditor2D/PhaserEditor2D-v3#184]
When filling a form like in the attachment, if I don't click outside of the input area, I cannot save the game, please add saving when cursor is active also.

![Untitled](https://user-images.githubusercontent.com/37840852/151654789-521b70c1-35ad-47d2-b026-90bf28e3ed43.png)

**Comment by PhaserEditor2D** [comment]
I can save it. This is an old issue that maybe we fixed in a previous release of the editor.
