### ISSUE TITLE
Your project exceeded the maximum number of files allowed

### ISSUE THREAD

**Issue by meanbeanmachine** [PhaserEditor2D/PhaserEditor2D-v3#185]
## Version

* Phaser Editor 2D Version: 3.32.0

* Operating System: Linux Mint 20.2 Cinnamon

* Web Browser and version: Mozilla Firefox for Linux Mint mint-001-1.0

## Description

In your docs you claim "With the Premium mode, you can use the IDE without any limitation".  Well, this is clearly not the case, since I am receiving this error for exceeding 1000 files.  I exceeded this file limit because I forgot to add my Tauri folder to "skip" in config.

## Possible solution

Adding my Tauri folder to the "skip" in config corrected the issue.  However, if this 1000 file limit isn't a bug, then you need to update your docs... because stating "without any limitation" is a straight lie.  I don't know if I'll exceed this limit but it is now something I have to be aware of, and so should all your paying customers.

**Comment by PhaserEditor2D** [comment]
No action here. I close this :)

**Comment by PhaserEditor2D** [comment]
Hey, I should add this to the doc. I reopen :)

**Comment by PhaserEditor2D** [comment]
Done. Now it shows a link to the documentation so it will be more clear to the user what's going on and how to "fix" the problem.

![image](https://user-images.githubusercontent.com/12187299/155066911-adedb113-bfe0-46c3-8f54-3745a11fb01a.png)

**Comment by PhaserEditor2D** [comment]
Hi. I just released PhaserEditor2D v3.32.1-beta.1 with the fixes for this issue.

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.32.1-beta.1

**Comment by meanbeanmachine** [comment]
and what about file size?  Today I just discovered you have a a limit of 10mb per file as well.  I don't see any flags to change this like number of files.  Any file over 10mb I have to add manually and update the asset json manually as well.  I'll open a new issue if I need to.

**Comment by PhaserEditor2D** [comment]
There is no limit on the size of files.

Here I use a 14mb image:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/12187299/161468518-668567e5-d619-41d8-9c60-48fa5bc331d8.png">

**Comment by meanbeanmachine** [comment]
This is the response using your "Webpack TypeScript Responsive" and  "Webpack TypeScript" templates:

![fileSizeError](https://user-images.githubusercontent.com/29932473/161537203-03ac935b-ada8-4929-94e5-c62647a00cdf.jpg)

**Comment by PhaserEditor2D** [comment]
Please, can you show me the DevTools log?

**Comment by PhaserEditor2D** [comment]
God! I found it! Does it happen when you try to upload a file, right?

It is a restriction from the times I implemented a shared/online editor.

I just removed it!

In the meantime, you can copy the file to the folder using the OS File manager. Just avoid using the Upload dialog of the editor.
