### ISSUE TITLE
Cannot use max-number-files flag in config file

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#186]
## Version

* Phaser Editor 2D Version: 3.32.0

* Operating System: Windows 11

## Description

Adding this in the phasereditor2d.config.json does not work:
```
"flags": [
    "-max-number-files",
    "10000"
  ]
```

## Possible solution

The only way (that I know) to get the flag to work, is to create a flags.txt file in the `resources\app\server` directory, and add this inside:
```
-max-number-files
10000
```

**Comment by PhaserEditor2D** [comment]
Done. I will release a beta version soon. Please, keep an eye open.
