### ISSUE TITLE
Scene super class should be automatically imported

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#189]
## Version

* Phaser Editor 2D Version: 3.32.0

* Operating System: Windows 11

## Description

When setting the Super Class to a Phaser Scene created by Phaser Editor, it does not get automatically imported.

![image](https://user-images.githubusercontent.com/9307505/153878899-8e9edc43-9138-4556-98bb-58e1c1dccc7b.png)

## Possible solution
Right now I have to import it manually.

![image](https://user-images.githubusercontent.com/9307505/153879302-e174b846-3a52-4e01-8870-7a93bc9acca6.png)

**Comment by PhaserEditor2D** [comment]
Done.
