### ISSUE TITLE
Structuring the generated code so that vscode doesn't add imports to the section that gets overwritten

### ISSUE THREAD

**Issue by PhaserEditor2D** [PhaserEditor2D/PhaserEditor2D-v3#190]
Structuring the phaser editor generated code so that Visual studio doesn't add imports to the section that gets overwritten by the code generation.  Right now visual studio code adds an import after the last import it finds which is in the generated section.  May need to put phaser editor imports at the top followed by a section of user defined imports.

**Comment by PhaserEditor2D** [comment]
Done. It now adds the USER-IMPORTS section.

![image](https://user-images.githubusercontent.com/12187299/154138999-ee662a62-5e65-4c0a-ae40-13c930c87660.png)

**Comment by jrabek** [comment]
Thanks @PhaserEditor2D! 🙇

**Comment by PhaserEditor2D** [comment]
Hi! I'm working on a more automated releasing process, so I can publish beta versions of allInOne, core, and the npm package. So it will be more easy to test the in-development version of the editor. It should be ready this week.

**Comment by PhaserEditor2D** [comment]
Hi. I just released PhaserEditor2D v3.32.1-beta.1 with the fixes for this issue.

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.32.1-beta.1
