### ISSUE TITLE
import preloadPackUrl disapears after changes in Preload.scene

### ISSUE THREAD

**Issue by cashh-money** [PhaserEditor2D/PhaserEditor2D-v3#193]
## Version

* Phaser Editor 2D Version: V3.32.0

* Operating System: Windows 10

* Web Browser and version: Firefox 

## Description

When I'm editing scene Preload.scene ( adding image for example), import preloadPackUrl disapears =>

```typescript
// You can write more code here

/* START OF COMPILED CODE */

import Phaser from "phaser";
import PreloadText from "../components/PreloadText";
import preloadPackUrl from "../../static/assets/asset-pack.json";  => this line disapears

export default class Preload extends Phaser.Scene {
```

## Possible solution

My workaround is to add the lines of import before the compiled code => 

```typescript
// You can write more code here
import preloadPackUrl from "../../static/assets/asset-pack.json";

/* START OF COMPILED CODE */

import Phaser from "phaser";
import PreloadText from "../components/PreloadText";

export default class Preload extends Phaser.Scene {
```

**Comment by PhaserEditor2D** [comment]
Yes, it is what you have to do. Place the import in the compiler-protected sections. There is a section for the imports too. 

http://help.phasereditor2d.com/v3/scene-editor/scene-compiler-user-code.html#editing-the-generated-code

**Comment by PhaserEditor2D** [comment]
Do you mean the project template is wrong? I should check it.

**Comment by cashh-money** [comment]
Hum yes, I think
When I launched new project, I choose template "webpack TypeScript".
In file Preload.ts , I have one line fort import preloadPackUrl.

When I modified the preload.scene, for exemple, I move the guapen picture in scene file.
The import "preloadPackurl" disapear.

**Comment by PhaserEditor2D** [comment]
Fixed! https://github.com/PhaserEditor2D/starter-template-webpack/commit/8d3fc9c9e52315dd32231c14b3129ee8bafd9707

Thanks.
