### ISSUE TITLE
Add support for aseprite

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#194]
As a user I'd like to be able to import aseprite files into the asset pack loader and use them in phaser editor. I'd also like to be able to manipulate them like normal phaser sprite sheet animations within the animation editor.

https://phaser.io/examples/v3/view/animation/aseprite-animation

**Comment by PhaserEditor2D** [comment]
Working on this :)

<img width="657" alt="Screenshot 1" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/12187299/d09cf0f7-5320-4766-ae95-90cc674d2dbe">

Do you have any Aseprite animation I can test with? For now, I'm using those available in the Phaser examples.

**Comment by PhaserEditor2D** [comment]
Btw, I don't understand very well this part:

> I'd also like to be able to manipulate them like normal phaser sprite sheet animations within the animation editor.

Would you like to edit the Aseprite animations with Phaser Editor 2D?

What I have in mind to do is:

- You can load the Aseprite animations in the Asset Pack.
- You can select Asesprite animations from the different animation dialogs in the editor.
- You can preview the Aseprite animations in an Aseprite Preview Editor. It is a read-only editor. If you want to change something about the Aseprite animations, you have to use Aseprite and re-export the animations.

Also, I'm implementing other features that are valid for the Asesprite animations and the built-in Phaser animations.

**Comment by PhaserEditor2D** [comment]
and what do you think about a script for converting an Aseprite file into a Phaser Animations JSON file? It is another step in the workflow but maybe you see some advantages on it. I think the Phaser JSON Animations file supports more Phaser-related parameters, like `delay`, `repeatDelay`, `showBeforeDelay`, `showOnStart`, `hideOnComplete`, `startFrame`, `timeScale`. 

Asesprite supports export templates?

**Comment by PhaserEditor2D** [comment]
Done.
