### ISSUE TITLE
Missing Instance names

### ISSUE THREAD

**Issue by MerlinEl** [PhaserEditor2D/PhaserEditor2D-v3#195]
## Version

* Phaser Editor 2D Version:  3.32.1 AllInOne

* Operating System:

* Web Browser and version: Windows 2011

## Description
-add some prefab instances in to scene
-print one random instance properties in to console > console.dir(instance_01);
 you will see that instance name is an empty string.

## Possible solution
-for now I'm adding a new property "instanceName" which is readable
 (but is double work, why not use names if they are already there ;-)

**Comment by PhaserEditor2D** [comment]
I should think more about this. I previous versions of the editor I added the option of using the Label parameter as the `name` property too. I can do this for this version. Or you can just create `Name` user component.

The way of adding metadata to an object in Phaser Editor 2D is creating user components (or prefab user properties).

**Comment by MerlinEl** [comment]
yes yes , I'm already using an component to achieve this. 
![2022-03-23_13h25_33](https://user-images.githubusercontent.com/15173933/159698686-3eb1cde2-20e5-407c-a644-053a96172da9.png)

but , the real name should be accessible ;-)
also, the names generator is generating names exponentially
that may cause memory overflows. 
![2022-03-23_13h20_41](https://user-images.githubusercontent.com/15173933/159699285-e30eb921-de8e-484a-a159-2b93808a12b9.png)

**Comment by PhaserEditor2D** [comment]
> also, the names generator is generating names exponentially

This one is another issue. Those are the variable names and I agree it is getting too long.

**Comment by PhaserEditor2D** [comment]
I will add a checkbox for enabling using the Variable Name as the game object's `name` value.

**Comment by PhaserEditor2D** [comment]
<img width="273" alt="GOName parameter" src="https://user-images.githubusercontent.com/12187299/160298716-bab5774e-38e8-4850-be99-d8108214aa62.png">

<img width="581" alt="GOName in code" src="https://user-images.githubusercontent.com/12187299/160298802-f33b910c-7261-479d-a9d6-8948c74cd57f.png">

Ok, look if you enable the new *GO Name* checkbox, it will generate as `name` the `"bitmaptext"` value, which is the same of the variable's name.

**Comment by PhaserEditor2D** [comment]
Done.

Please, can you create a new issue about:

> also, the names generator is generating names exponentially
> that may cause memory overflows.

**Comment by MerlinEl** [comment]
the name property is good to use in loops where you need to know :

  1.  name of a button which is pressed (used on switch to perform desired action)
  2.  name of drag and drop item which is dropped on area (compare list of names which is allowed to drop here)
  3.  generally iterate with scene objects

________________________________

**Comment by MerlinEl** [comment]
> <img alt="GOName parameter" width="273" src="https://user-images.githubusercontent.com/12187299/160298716-bab5774e-38e8-4850-be99-d8108214aa62.png">
> 
> <img alt="GOName in code" width="581" src="https://user-images.githubusercontent.com/12187299/160298802-f33b910c-7261-479d-a9d6-8948c74cd57f.png">
> 
> Ok, look if you enable the new **GO Name** checkbox, it will generate as `name` the `"bitmaptext"` value, which is the same of the variable's name.

This one is good. It will be nice to check this option true as default

**Comment by PhaserEditor2D** [comment]
> the name property is good to use in loops where you need to know : 1. name of a button which is pressed (used on switch to perform desired action) 2. name of drag and drop item which is dropped on area (compare list of names which is allowed to drop here) 3. generally iterate with scene objects

Thanks. Yes, I think many users use these kind of techniques so it is fine for me to include the `name` property. Just a reminder, you can create list of objects in the Scene Editor: https://help.phasereditor2d.com/v3/scene-editor/object-list.html

And sure, you can always add metadata to an object using the User Components.

> This one is good. It will be nice to check this option true as default

Well, I think setting this ON by default will generate a lot of code that is not required in most of the cases.
