### ISSUE TITLE
Align tool need fix offset for prefabs

### ISSUE THREAD

**Issue by MerlinEl** [PhaserEditor2D/PhaserEditor2D-v3#198]
## Version

* Phaser Editor 2D Version: 3.32.1

* Operating System: Windows 11

* Web Browser and version: Chrome 99.0.4844.74 (Official Build) (64-bit)

## Description
When using align tool to prefabs, they are placed incorrect.

Create a prefab with some images and drop it in to scene.
Use align tool > center horizontal and center vertical.
The prefab will be moved at wrong position.

![2022-03-18_12h48_51](https://user-images.githubusercontent.com/15173933/159002532-1d4c5bb8-83ed-43d0-8959-19da8091f11f.png)

## Possible solution
I think, the prefab need to be offset at X and Y by half ++ ;-)

![2022-03-18_13h38_35](https://user-images.githubusercontent.com/15173933/159004438-81204c22-e037-4097-ac30-9ba1a27058c1.png)

**Comment by PhaserEditor2D** [comment]
Hi. Please, can you create a small project to reproduce this behavior?

The thing is that you are aligning there a container, and a container doesn't have width/origin. It should be computed or "simulated". So, I want to be sure we are working in the same case.

**Comment by MerlinEl** [comment]
> Hi. Please, can you create a small project to reproduce this behavior?
> 
> The thing is that you are aligning there a container, and a container doesn't have width/origin. It should be computed or "simulated". So, I want to be sure we are working in the same case.

Here is a small project. In one case a prefab works fine in another is not centered.
Both of them are created with same way.
[Editor Test.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/8407851/Editor.Test.zip)

![2022-04-04_09h59_47](https://user-images.githubusercontent.com/15173933/161501041-b987d75d-52b7-4d19-b222-a1e3b9696c94.png)

**Comment by PhaserEditor2D** [comment]
Fixed. Thanks for sharing the project!

You can test it with this Core diet: [PhaserEditor2D-core-3.33.0-beta.0-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/8419475/PhaserEditor2D-core-3.33.0-beta.0-windows.zip)
