### ISSUE TITLE
BitmapText aligned cause NaN position

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#200]
## Version

* Phaser Editor 2D Version: 3.32.1 All on One
* Operating System: OSX 12.2.1

## Description

![image](https://user-images.githubusercontent.com/758680/159923606-2d2e1d37-c002-4fd6-9af5-d1dd25d287fd.png)

* Create a BitmapText
* Click on any align button is the interface.

Font used: [Archive.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/8341721/Archive.zip)

**Comment by PhaserEditor2D** [comment]
Thanks! I can reproduce the error.

**Comment by PhaserEditor2D** [comment]
Done. It was using the properties `displayWidth` & `displayHeight` who are not available for BitmapText 😳!
