### ISSUE TITLE
Allow renaming a nested prefab

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#203]
When I change the name of the Nested Prefab, the prefabs in the scene don't take the modifications of the modified nested prefab.

![image](https://user-images.githubusercontent.com/758680/160670781-3085bf1b-eb12-4d63-a57b-f82a65de797e.png)
![image](https://user-images.githubusercontent.com/758680/160670796-ce155841-7d9d-438c-b9fb-2f318626af61.png)

**Comment by PhaserEditor2D** [comment]
It works for me. You should save the prefab file after renaming the nested prefab.
