### ISSUE TITLE
Show the properties from the base class of a component

### ISSUE THREAD

**Issue by robinheidrich** [PhaserEditor2D/PhaserEditor2D-v3#205]
It would be nice if the properties from the base class of a component were also displayed so that you don't have to add them again in the component.

**Comment by PhaserEditor2D** [comment]
Please, can you explain it more? Are you talking about user components inheritance? Inheritance of properties is always available in prefabs, via prefab variants. User components don't allow inheritance. Yes, you can set a base class for it, but it could be any class, not only a user component class.

**Comment by robinheidrich** [comment]
That's exactly what I mean. That's a pity, couldn't it check in the .components if this class exists as a component and then inherit the properties from there?

It would be really helpful in my opinion.

**Comment by PhaserEditor2D** [comment]
I would like to keep user components simple as it is right now (without inheritance). I plan to release soon a new ScriptGameObject that will be like a non-graphical prefab. It will be a pure logic object (like the user component) but with the prefab's features, like the inheritance.

By the way, please, can you talk me a bit more about this case where you need an hierarchy of user components?

**Comment by robinheidrich** [comment]
I have two components, one that registers pointer events and another that uses this as a base class and applies these pointer events.

In the component with the pointer events I have properties for the callbacks, which I want to use in the other component.

**Comment by PhaserEditor2D** [comment]
Sorry, I don't have it very clear. Please, can you tell me how you use it in a particular case? Also, if you have a base class, I guess you have at least two different sub-classes.

**Comment by robinheidrich** [comment]
As an example if I want to have a button then I use as base class my component with the pointer events.

So in the pointer events component there are pointerover and pointerout, which I use in the button component to set the frame of the game object (default and hover).

This is just something to quickly set up the pointer events without having to do this in every component.

**Comment by PhaserEditor2D** [comment]
And are you going to use the "pointer event" class with any other class different from the "button component" class?
Is not a `Button` user component enough? Why do you need a base class?

**Comment by PhaserEditor2D** [comment]
I will close this. Please, if you think this discussion is not over yet, reopen the issue. Thanks!
