### ISSUE TITLE
Using aliases with Auto Importer

### ISSUE THREAD

**Issue by robinheidrich** [PhaserEditor2D/PhaserEditor2D-v3#207]
I use aliases for my imports and it would be a nice addition if Auto Import used them as well, if possible.

**Comment by PhaserEditor2D** [comment]
Please, can you be more specific?

**Comment by robinheidrich** [comment]
I am talking about [import aliases](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases) that you configure in webpack and jsconfig.

**Comment by PhaserEditor2D** [comment]
Yes, it complicates code generation. It is complicated to parse the typescript config file and it requires extra effort to create a specific configuration for the editor. Thanks!
