### ISSUE TITLE
Open with VSCode

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#208]
Hello, 
It will be cool if we could open .ts or .js file with VS Code. With a double click or with the context menu.
![image](https://user-images.githubusercontent.com/758680/161992140-7078fafd-97ba-46c4-9e0c-9f4f25d8bdfc.png)

**Comment by zombiestruck** [comment]
Will work on implementing opening with system's default text editor.

**Comment by PhaserEditor2D** [comment]
> Will work on implementing opening with system's default text editor.

Well, not the system's default text editor, else VS Code.

**Comment by aunpyz** [comment]
> > Will work on implementing opening with system's default text editor.
> 
> Well, not the system's default text editor, else VS Code.

Does this mean the only external editor is VSCode?

**Comment by PhaserEditor2D** [comment]
Hi @aunpyz 

I can provide the two options, the system text editor and vs code. For now vs code goes first because it is the code editor we better support.

**Comment by PhaserEditor2D** [comment]
Done.

Now you have two commands for enabling/disabling to open coding files in the configured external editor:

![commands](https://user-images.githubusercontent.com/12187299/234609392-036b0893-84ad-4535-b765-eedbcc70dcb9.jpeg)

The coding files are: `.js`, `.ts`, `.html`, `.css`.

You can configure the external editor. By default, it is Visual Studio Code, so probably you don't need to configure another external editor.

Look the `-external-editor-command` server option: https://help-v3.phasereditor2d.com/misc/server-options.html
