### ISSUE TITLE
The content of the editor overlaps with the border

### ISSUE THREAD

**Issue by robinheidrich** [PhaserEditor2D/PhaserEditor2D-v3#209]
## Version

* Phaser Editor 2D Version: 3.32.1

* Operating System: Windows 11

* Web Browser and version: Google Chrome 100.0.4896.75

## Description

This rectangle is positioned at x: 0 and y: 0 and has an origin of x: 0 and y: 0.

As you can see, part of it is outside the border.

![image](https://user-images.githubusercontent.com/23118399/162597826-39322264-d5b5-4dd0-a8fc-fa1a36b1d884.png)
![image](https://user-images.githubusercontent.com/23118399/162597872-b9d58246-77eb-4e09-82bd-055dac3dd973.png)

## Possible solution

Perhaps the black border could be positioned a bit further out.

**Comment by PhaserEditor2D** [comment]
I think it is better now.
<img width="259" alt="Screenshot 6" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/12187299/2c2d0c2f-7927-4e52-b422-95929c9c72df">
