### ISSUE TITLE
GameObject type component property

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#212]
https://docs.unity3d.com/Manual/InstantiatingPrefabs.html

As a Phaser editor 2d v3 user I would like the ability to have a component property for GameObject or prefab types. 

Example: 
 I'd like to have a component field like "bulletType" that allows me to specify the class of whatever bullet prefab I want it to shoot (laser, bullet, homing missiles) I wouldn't want to add those to the scene in the editor, but I'd like to be able to tell my enemy class to instantiate whatever prefab class type is specified in the component's bulletType field. 

Example generated code:  
```

const thisCompBulletSettings = new compBulletSettings(this);
thisCompBulletSettings.bulletType = prefabMissile;
thisCompBulletSettings.bulletSpeed = 200;


onFireBullet() {
    let component = compBulletSettings.getInstance(this);

    let bullet = new component.bulletType(0, 0);
    bullet.speed = component.bulletSpeed;

}
 
 
```

**Comment by PhaserEditor2D** [comment]
Done.

Please, check the new **Object Constructor** property type.

For testing the `develop` branch of the editor. Please, follow these steps:

[Build Guide](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/master/BUILD.md)

**Comment by PhaserEditor2D** [comment]
And now it allows setting the expression type of the property:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/12187299/165367531-601d8555-8e4a-4e59-9a03-e63a7287e078.png">

As you can see in the image, you can set the field's type to something like:

```javascript
bulletCtr!: typeof Fruit & typeof Bomb & typeof Stone;
```

It can help you with auto-completion within VSCode.
