### ISSUE TITLE
Rounded Rectangle origin problem

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#213]
## Version

* Phaser Editor 2D Version: 3.33.0

* Operating System:

* Web Browser and version:

## Description

The coordinates of the game object is always the top left corner whatever the origin X or Y.

* Install Rounded Rectangle plugin https://github.com/PhaserEditor2D/phasereditor2d-roundedRectangle-plugin in the Webpack typescript empty project.
* Add a rounded rectangle in the editor.
* Change the Origin

<img width="610" alt="image" src="https://user-images.githubusercontent.com/758680/165157232-e7b6e564-9e4f-41d0-a9b6-9b7395cf6853.png">

<img width="255" alt="image" src="https://user-images.githubusercontent.com/758680/165157261-f1794414-f6dc-4b10-a10b-1a9387ffc933.png">

**Comment by PhaserEditor2D** [comment]
Fixed.

Please, install the latest version of the plugin:

```
npm install phasereditor2d-roundedrectangle-plugin@latest --save-dev
```

Please, compile all the scene files and check all your RoundedRectangle objects are well-positioned in the editor and the game.

The bug was about to the default origin set by the editor. It was set to 0.5, but now it is to 0 (as it is in Phaser).

**Comment by BenoitFreslon** [comment]
Hello, I got the same problem with this plugin: https://github.com/PhaserEditor2D/phasereditor2d-ninepatch-plugin

**Comment by PhaserEditor2D** [comment]
Did you install the latest version of the plugin?

**Comment by BenoitFreslon** [comment]
Yes I got the last version of the Nine Patch Plugin 1.0.6 https://github.com/PhaserEditor2D/phasereditor2d-ninepatch-plugin

**Comment by PhaserEditor2D** [comment]
Please, can you create a new issue for it?
