### ISSUE TITLE
Do not autoimport classes when they are already added manually

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#214]
If I add a class manually in a scene for example and then I add the class type gameobject in the PhaserEditor the class is imported twice.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/758680/165733433-8fd04ea5-4068-4e80-9b92-18dcfad7286f.png">

**Comment by PhaserEditor2D** [comment]
Hi! Yes, in that case, you should remove the class you added manually. The editor doesn't parse your source code and doesn't know what you added manually. Or, you can disable the auto-import feature, and add all the imports by yourself.
