### ISSUE TITLE
Particle Editor

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#215]
Game Engine IDEs like Unity have a nice particle system editor that allow you to preview the particle effect in the editor itself.  https://docs.unity3d.com/Manual/PartSysUsage.html

There are several online particle editor tools available that allow you to save the particle system as json.
https://phaser-particle-editor.firebaseapp.com/
https://koreezgames.github.io/phaser3-particle-editor/

Phaser itself has a version in its lab site:
https://labs.phaser.io/edit.html?src=src/game%20objects/particle%20emitter/particle%20editor.js

It would be nice to copy this functionality within the editor to
1. Streamline the process of previewing and importing
2. Align with the version of Phaser being used for creating the particle system and rendering it

The resulting json could be added to the asset files and later used like:
```
 const particles = this.add.particles("particles");
```

**Comment by PhaserEditor2D** [comment]
I transferred the issue here. The other repo is for v1 of the editor :)

**Comment by PhaserEditor2D** [comment]
Another advantage of having the emitter as a game object is that you can create emitter prefabs! I see the [ParticleEmitterManager](https://newdocs.phaser.io/docs/3.55.2/Phaser.GameObjects.Particles.ParticleEmitterManager) is a game object.

**Comment by PhaserEditor2D** [comment]
Done, in v4 :)
