### ISSUE TITLE
No Textures are Available to Select from the Select Texture Window When Using Components

### ISSUE THREAD

**Issue by Cartrell** [PhaserEditor2D/PhaserEditor2D-v3#216]
## Version
* Phaser Editor 2D Version: Premium 3.33.0

* Operating System: Windows 10 Home, 64-bit

* Web Browser and version:
  * Firefox 99.0.1
  * Chrome 101.0.4951.41

## Description
When setting up a property on a Component, if its type is Texture Config, it's not showing any textures to assign to that property once the component is added to a game object.
![image](https://user-images.githubusercontent.com/6464920/166167948-5f9be8cb-0a1a-4717-a655-be8ae64f755e.png)

## Possible solution
As a workaround, I'm modifying the property text field manually. The icon on the button that opens the Select Texture window will still update if the text correctly references a texture.
![image](https://user-images.githubusercontent.com/6464920/166167930-382164b1-e870-4560-9940-e91d91897b30.png)

I'm available for additional questions or troubleshooting.
Thanks.

**Comment by PhaserEditor2D** [comment]
Yes, it is a regression. Thanks.

**Comment by arianfornaris** [comment]
Done.

**Comment by Cartrell** [comment]
Thanks, @arianfornaris
