### ISSUE TITLE
Can't create a new user component

### ISSUE THREAD

**Issue by DriesVG-ui** [PhaserEditor2D/PhaserEditor2D-v3#217]
hey therre. I am testing the free Phaer editor and I am now at the part that I want to create a new component for my game. I want t add a component "shoot" to my tank so whenever I click I can shoot a bullet.

Anyway, I am new at this so I might do something I have missed. But I have just added a new component, Called it "shoot" and then started the program. The thing is he keeps on calling that the component is not defined...
I attach the pictures here so you knwo what I am talking about..
![Phaser 1](https://user-images.githubusercontent.com/59870524/166639244-ea70e53a-55c6-4cac-ab69-9bbf19547d8a.png)
![Afbeelding2](https://user-images.githubusercontent.com/59870524/166639273-f97b5b0e-9e21-4152-9ed9-4984fb2d2e0d.png)
![Phaser 3](https://user-images.githubusercontent.com/59870524/166639292-a842fcf3-1463-4cd8-ad55-aaddb3f91c68.png)
![Phaser 4](https://user-images.githubusercontent.com/59870524/166639306-834bbeed-f483-43bc-b652-1dac12a56a60.png)

Could you guys help me out on this?

Thanks

**Comment by PhaserEditor2D** [comment]
Hi!

You should load the `Shoot.js` file on the page. For example, by including it in the `index.html` file. 

What project template did you use for creating the project? Is it all JavaScript?

**Comment by DriesVG-ui** [comment]
Hi,

Of course!! Silly me, I haven't included it in the index file...now everything works ok.

It's full javascript yes.

Thanks!

**Comment by PhaserEditor2D** [comment]
Good. I close the issue. Keep in contact. You can join our discord server: https://discord.com/invite/4DdpMMD
