### ISSUE TITLE
RoundedRectangle strokeColor doesn't change => Have to call redraw() each time.

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#218]
## Version
1.0.2
* Phaser Editor 2D Version: 3.3.1

* Operating System: OSX

## Description

Change the strokColor of a RoundedRectangle gameobject but the color doesn't change.

`this.background.strokeColor = 0x424242;`

## Possible solution

Call the redraw method after changing the color.
```
this.background.strokeColor = 0x424242;
this.background.redraw();
```

![image](https://user-images.githubusercontent.com/758680/167891704-05530568-3272-46c4-bde5-d6feab64ffc3.png)

**Comment by PhaserEditor2D** [comment]
Do you mean, it is not changing in the editor or in the game, at the run time?

**Comment by BenoitFreslon** [comment]
Hello, this appends only in run time.

**Comment by BenoitFreslon** [comment]
Ho ok.
Good to know.
