### ISSUE TITLE
Origin problem with NinePatch Plugin: https://github.com/PhaserEditor2D/phasereditor2d-ninepatch-plugin

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#219]
Hello, I got the same problem with this plugin: https://github.com/PhaserEditor2D/phasereditor2d-ninepatch-plugin

Add a rounded rectangle in the editor.
Change the Origin

<img width="131" alt="image" src="https://user-images.githubusercontent.com/758680/167943415-bb539faa-f772-4cd8-9236-70f421dd7aea.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/758680/167943445-0e54fdb1-2756-4a93-9c13-5bd09b86d80c.png">

_Originally posted by @BenoitFreslon in https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/213#issuecomment-1124254595_

**Comment by PhaserEditor2D** [comment]
Please, can you test with the latest version?

Read the instructions here: https://github.com/PhaserEditor2D/PhaserEditor2D-v3/issues/220#issuecomment-1136733651
