### ISSUE TITLE
Very poor performance with NinePatch and RoundedRectangle plugin on Safari and Android and iOS browser

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#220]
## Version

* Phaser Editor 2D Version: 3.3.1

* Operating System: OSX, Android

* Web Browser and version: Safari 15.4

## Description

The GameObjects NinePatch and RoundedRectangle slow downs Framerate if you use it.
Example : ~100 RoundedRectangle
Safari Vs Chrome on the same Computer
Same problem with Android and iOS
![image](https://user-images.githubusercontent.com/758680/168043172-3e6bf2c8-0f49-48b8-8474-59552380ff2b.png)

With the classic Rectangle GameObject
![image](https://user-images.githubusercontent.com/758680/168044073-ac5f8315-763b-409b-9675-7505464a9d7c.png)

**Comment by PhaserEditor2D** [comment]
Hi,

Please, can you test if the performance improved?

1- Get the latest (beta) release of the editor:

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.33.2-beta.1

2- Install a new **RoundedRectangleGraphics** plugin:

https://github.com/PhaserEditor2D/phasereditor2d-roundedRectangleGraphics-plugin

3- Try with both, the **RoundedRectangleGraphics** & **RoundedRectangleImage** objects. Get the instructions in the readme of the repo of the plugin.

**Comment by arianfornaris** [comment]
The performance was improved with the latest versions of the ninepatch and roundedRectangle plugins.
You can try the new NinePatchContainer or the NinePatchImage implementations. Regarding the rounded rectangle, you can try the new RoundedRectangleImage implementation (https://github.com/PhaserEditor2D/phasereditor2d-roundedRectangleGraphics-plugin).
