### ISSUE TITLE
User Component: Switch to other input works only on 2nd click

### ISSUE THREAD

**Issue by robinheidrich** [PhaserEditor2D/PhaserEditor2D-v3#223]
## Version

* Phaser Editor 2D Version: v3.33.1

* Operating System: Windows 11

* Web Browser and version: Google Chrome 101.0.4951.67

## Description

If you edit the input of User Components and want to switch to another input, you have to click twice on it.

This happens only if the input has been edited, if it has not been edited, you can switch between inputs normally.

![capture](https://user-images.githubusercontent.com/23118399/169670463-2520fe85-4242-43d0-8ab6-70326061034a.gif)

**Comment by PhaserEditor2D** [comment]
Fixed! Now it shows the user components and prefab properties in an individual Inspector view. The DOM elements are generated only once, and not every time an object is selected. 
<img width="306" alt="Screenshot 4" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/12187299/5363252a-87d7-423f-a6ee-33a080db96da">
