### ISSUE TITLE
Undo and Redo doesn't work (OSX)

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#225]
## Version
* Phaser Editor 2D Version: 3.33.2 
* Operating System: OSX 12.3.1

## Description

The **Undo** and **Redo** function doesn't work at all.
Same problem with the shortcut Command + Z and Command + Shift + Z

<img width="274" alt="image" src="https://user-images.githubusercontent.com/758680/172359774-e70faeb7-dc6f-41f5-a2a7-3ea92e444d0b.png">

EDIT : Only the **Undo** on the command palette is working.
![image](https://user-images.githubusercontent.com/758680/172360539-031a8329-8608-42df-8e6f-cb210b318d49.png)

**Comment by PhaserEditor2D** [comment]
Both Undo and Redo work for me. I'm on macOS 12.2.

It doesn't work if you click on the menu, but it works with the keyboard shortcuts.

I will take a look on this.

**Comment by BenoitFreslon** [comment]
UPDATE: 
So I got this problem on several softwares like Spine and RogueEngine.
I have to use CMD + W instead CMD + Z because i'm using an AZERTY keyboard.

**Comment by PhaserEditor2D** [comment]
Hum! I have here in the TODO to allow changing the keys of commands, but it is not yet a priority.

**Comment by robinheidrich** [comment]
I have a similar problem, and that is that for some reason Ctrl+Y does undo and Ctrl+Z does nothing.
