### ISSUE TITLE
Polygon Shape Tool

### ISSUE THREAD

**Issue by wizguin** [PhaserEditor2D/PhaserEditor2D-v3#227]
It would be nice if we could create polygon shapes using the editor. This would be very useful for creating specific shapes without the need for manual calculations, or other software such as PhysicsEditor.

Ideally would just be able to add and remove points (i.e by double clicking), and then adjust each point by dragging, similar to how PhysicsEditor works.

https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Polygon.html

**Comment by PhaserEditor2D** [comment]
We have an issue with the Polygon game object:

https://github.com/photonstorm/phaser/issues/6151

It doesn't allow to change the points. It only allows setting the points when you create the object.

It is not good for the editor, it doesn't allow changing the points of a polygon prefab instance.

Probably you will never need a polygon prefab, so I will think if I implement it but exclude the "points" properties in a prefab instance.

**Comment by wizguin** [comment]
It would be good if we could delete a point by double clicking or with the middle mouse, it's easy to delete the whole shape by accident if your cursor isn't directly on the point

**Comment by PhaserEditor2D** [comment]
Done.
