### ISSUE TITLE
Add ability to select multiple instances for "Object Variable" user defined properties

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#230]
As a Phaser Editor user, I would like the ability to select multiple instances in the scene for an Object Variable user defined property. When the dialog comes up now, it gives the option to select multiple, but does not allow you to click select.

![image](https://user-images.githubusercontent.com/5861090/176387483-9d10019b-e677-4b55-8d1b-062e7f3a5b2d.png)

A general solution that was proposed was to add an "isArray" property onto the user defined properties to better support this functionality across multiple user defined property types.  This is a great solution as it provided typescript type safety and generalizes the functionality. I can see many use cases when you would like to reference an array of Scene keys, animation keys, texture keys, colors, etc. Adding it to the Object Constructor user defined property will also have many use cases. (ex: having a dropTypes property on a box gameObject that spawns multiple types of items when a box is destroyed. Things like items, powerups, coins, etc )

![image](https://user-images.githubusercontent.com/5861090/176387920-153d9f8c-7193-4d66-84b6-6dfb9aa1c78b.png)

**Comment by PhaserEditor2D** [comment]
Now you can do this with the script nodes. If you need to reference multiple game objects in the scene, you can create multiple script nodes each one referencing a different game object.
