### ISSUE TITLE
Input Text

### ISSUE THREAD

**Issue by sahmyooI** [PhaserEditor2D/PhaserEditor2D-v3#235]
It's pretty annoying to have to create the input text boxes manually with the Rex plugin every time I want to add an input option to my game. I'm not sure how possible it'd be, since it's not supported without a plugin in Phaser3 iirc, (pretty sure you did it with nineslicing though?) but it'd be a great help, I keep running into issues with input boxes not being hidden or destroyed properly - positioning and sizing them is a pain too, and having a way to do it in the editor would be amazing. I'd be willing to sponsor and throw you a few more $$ if that'd be something you'd be willing to look into ASAP.

**Comment by PhaserEditor2D** [comment]
Hi. I see two problems here. The implementation of the Input object and the tools in the editor.

Do you think the Rex implementation is fine?

**Comment by sahmyooI** [comment]
The Rex implementation is alright, main issue with it is the destroying / hiding of the input text, but without it being native in phaser any implementation would have that issue I think.

**Comment by PhaserEditor2D** [comment]
What do you mean with hiding it? Overlaping it with another objects? Or just hiding it from the whole scene?

**Comment by sahmyooI** [comment]
Overlapping it with another object is not possible, since it's in html it's always on top. Hiding it from the whole screen sometimes just doesn't work for an unknown reason. It's never happened to me, so I haven't been able to check what causes it, but some other players of my game have reported it.

**Comment by PhaserEditor2D** [comment]
Ok.

**Comment by sahmyooI** [comment]
I suppose alternatively you could create some way to detect if the mouse is over the portion of the screen it's meant to be visible in and otherwise replace it with a phaser text object? Even with this, it'd still appear on top when the user is interacting with it though.

**Comment by PhaserEditor2D** [comment]
I am not sure. For that reason I asked to you if the implementation of the Rex plugin is ok. Then I can focus more on the editor side and less in the input text implementation.

Anyway I will take a look. Whi knows and I end making my own implementation more friendly with the editor. Just like I did with the ninepatch plugin.

**Comment by sahmyooI** [comment]
> I am not sure. For that reason I asked to you if the implementation of the Rex plugin is ok. Then I can focus more on the editor side and less in the input text implementation.
> 
> Anyway I will take a look. Whi knows and I end making my own implementation more friendly with the editor. Just like I did with the ninepatch plugin.

Thanks so much for taking a look! It'll be a great help if you do end up implementing it :))

**Comment by PhaserEditor2D** [comment]
You know... Maybe I will mske my own implementation just as you said. Using a Text and showing up an input only when you click the text.

It would be great if you showme some images of how would you like to see it.

**Comment by sahmyooI** [comment]
Yeah sure. Made a mockup of how it could be used in the editor. Actual positioning and stuff would be very similar to the standard text toool
![image](https://user-images.githubusercontent.com/67554336/187326465-bd99a5e8-d56b-4b10-9af5-7789978c3adc.png)
For the interactivity part, it could be as simple as just cloning the input text as a standard text option, something like
```
const input_text_whatever = new InputTextPlugin(scene, size, position, defaulttext, whatever other options)

export default class InputTextPlugin{
     constructor(scene, size, positition, defaulttext, whatever other options){
          this.phasertext = scene.add.text(size, positition, defaulttext, whatever other options);
          this.phasertext.setInteractive()
          this.textobject = new DOM(whatever the input text is)
          this.phasertext.on('pointerover', function (pointer){
              this.textobject.visibility = "shown"
          }
          this.phasertext.on('pointerout', function (pointer){
              this.textobject.visibility = "hidden"
          }
     }
     
     onTextInput(){
         this.phasertext.text = this.textobject.textContent
     }
}
```

**Comment by PhaserEditor2D** [comment]
Thanks!

And how it should look? I mean, visually? An input text with borders? Rounded borders? I want to see your current input text in your game.

**Comment by PhaserEditor2D** [comment]
Look that if you are going to use a Text object, then you don't need a plugin at all.

You can create an `InputDOM` user component that will listen for the `click` event on the Text object. Then it can hide the object and show the DOM element. And you can positioning, resize, etc... the Text object in the Phaser Editor.

For doing it, you don't need to create a Phaser Editor plugin.

**Comment by PhaserEditor2D** [comment]
You can create a user component or a Text prefab, as you wish.

**Comment by PhaserEditor2D** [comment]
By the way, do you expect it to work on mobile? The mobile keyboard has different challenges. For example, it fills half of the screen, scrolls the page, and focuses on the input text. I don't know how it will work on a Phaser game.

**Comment by sahmyooI** [comment]
> Thanks!
> 
> And how it should look? I mean, visually? An input text with borders? Rounded borders? I want to see your current input text in your game.

It'd be great to have the option to customise that in the editor. The DOM object itself wouldn't really need styling because the phaser text object would handle that.
Here's how one of the input text objects currently looks.
![IMG_20220830_142925](https://user-images.githubusercontent.com/67554336/187450304-a82f489f-9284-482d-a4ef-ddfec1193d7f.jpg)
The DOM object itself only has the text input, the styling is just controlled by a rectangle behind it. This is preferred because in the case there is something else on top of the text object, with a higher depth, styling the DOM object will make it appear as if the text is on the top, which may create an issue with having a logo, like a search icon in the same space as the text object - it would be layered incorrectly.

**Comment by sahmyooI** [comment]
> By the way, do you expect it to work on mobile? The mobile keyboard has different challenges. For example, it fills half of the screen, scrolls the page, and focuses on the input text. I don't know how it will work on a Phaser game.

Whilst mobile compatibility is preferred in anything that can be used in a browser, Phaser's mobile compatibility is notoriously poor, so I'm not sure that'd be too much of a priority for me or others.

**Comment by PhaserEditor2D** [comment]
So, do you think you can implement that user component yourself?

**Comment by sahmyooI** [comment]
> So, do you think you can implement that user component yourself?

Yeah, I can definitely take a look.

**Comment by PhaserEditor2D** [comment]
Good! Let me know when you finish it.

**Comment by sahmyooI** [comment]
> Good! Let me know when you finish it.

I have done so! I decided to use a different approach of not using a DOM element at all, and instead using listeners. Here is the code for the component.

```js
/* START OF COMPILED CODE */

export default class InputText {
    constructor(gameObject) {
        super(gameObject)

        /** @type {Phaser.GameObjects.Text} */
        this.gameObject
        /** @type {boolean} */
        this.multiline = 0
        /** @type {boolean} */
        this.ispassword = false
        /** @type {number} */
        this.charlimit = 0
        /** @type {regex} */
        this.inputfilter
        /** @type {any} */
        this.entercallback = () => {}

        this.gameObject = gameObject
        gameObject['__InputText'] = this

        /* START-USER-CTR-CODE */
        this.input = this.gameObject.scene.input
        this.shift = this.input.keyboard.addKey('SHIFT')
        window.textInput = this
        /* END-USER-CTR-CODE */
    }

    /** @returns {InputText} */
    static getComponent(gameObject) {
        return gameObject['__InputText']
    }

    /* START-USER-CODE */

    start() {
        this.lineWidth = this.gameObject.style.fixedWidth
        this.gameObject.setStyle({fixedWidth: 0})

        this.clickZone = this.gameObject.scene.add.rectangle(this.gameObject.x, this.gameObject.y, this.lineWidth, this.gameObject.height, 0x000000, 0)
        this.clickZone.setOrigin(this.gameObject.originX, this.gameObject.originY)
        this.gameObject.scene.add.existing(this.clickZone)

        this.clickZone.setInteractive({
            cursor: 'text',
            pixelPerfect: false,
        })
        this.clickZone.on('pointerup', (pointer) => this.onUp(pointer))
        this.clickZone.on('pointerover', () => this.onOver())
        this.clickZone.on('pointerout', () => this.onOut())

        this.indicator = this.gameObject.scene.add.rectangle(this.gameObject.x, this.gameObject.y, 1, this.gameObject.height, 0x000000)
        this.indicator.visible = false
        this.gameObject.scene.add.existing(this.indicator)
    }

    onUp(pointer) {
        // If there are multiple input fields, these listeners would be removed straight away by the other one, so we add them with a 0.1 second delay
        setTimeout(() => {
            if (pointer.button != 0 || this.isSelected) {
                return
            }

            if (!this.userClicked) {
                this.userClicked = true
                this.gameObject.text = ''
            }

            this.input.keyboard.on('keydown', (event) => this.onKeyDown(event))
            this.input.once('pointerup', (pointer) => this.onClick(pointer))
            this.isSelected = true
            this.flashIndicator()
        }, 100)
    }

    onClick(pointer) {
        if (!this.isOver) {
            this.input.keyboard.removeListener('keydown', null, this)
            this.isSelected = false
            this.indicator.visible = false
        } else {
            this.input.once('pointerup', (pointer) => this.onClick(pointer))
        }
    }

    onOver() {
        this.isOver = true
    }

    onOut() {
        this.isOver = false
    }

    onKeyDown(event) {
        if (event.key == 'Backspace') {
            this.gameObject.textContent = this.gameObject.textContent.slice(0, -1)
            this.gameObject.text = this.gameObject.text.slice(0, -1)
        } else if (event.key == 'Enter') {
            if (this.shift.isDown) {
                this.text += '\n'
            } else if (this.entercallback) {
                this.entercallback()
                this.input.keyboard.removeListener('keydown', null, this)
                this.selected = false
            }
        } else if (event.key.length != 1) {
            return
        } else if (this.charlimit > 0 && (this.text + event.key).length > this.charlimit) {
            return
        } else {
            let key = event.key
            if (this.shift.isDown || event.getModifierState('CapsLock')) {
                key = key.toUpperCase()
            }
            if (this.inputfilter && !this.inputfilter.test(key)) {
                return
            }
            this.gameObject.textContent += key
            if (this.ispassword) {
                this.gameObject.text += '*'
            } else {
                this.gameObject.text += key
            }

            if (this.gameObject.width > this.lineWidth) {
                if (!this.multiline) {
                    this.gameObject.textContent = this.gameObject.textContent.slice(0, -1)
                    this.gameObject.text = this.gameObject.text.slice(0, -1)
                } else {
                    this.gameObject.textContent = this.gameObject.textContent.slice(0, -1) + '\n' + key
                    // there shouldn't be a password on a multiline input but just in case
                    if (this.ispassword) {
                        this.gameObject.text = this.gameObject.text.slice(0, -1) + '\n*'
                    } else {
                        this.gameObject.text = this.gameObject.text.slice(0, -1) + '\n' + key
                    }
                }
            }
        }
        this.indicator.x = this.gameObject.x + this.gameObject.width
    }

    flashIndicator() {
        if (this.isSelected) {
            this.indicator.visible = true
            setTimeout(() => {
                this.indicator.visible = false
                setTimeout(() => this.flashIndicator(), 500)
            }, 500)
        }
    }

    /* END-USER-CODE */
}

/* END OF COMPILED CODE */

// You can write more code here
```

Parts of it might be a bit overcomplicated, and unfortunately it doesn't work on mobile - if people want to implement it in their own projects they might need to create their own keyboard implementation to support mobile.

Limitations are the fact that ctrl actions do not work, and you can only type at the end of the input text, not select characters from inside it - but hey, I made this in about an hour so not bad work for that kind of timeframe.

Feel free to modify it and build it into the editor if you wish - up to you!

**Comment by PhaserEditor2D** [comment]
Great thanks!

Yes, an InputText is a complex thing, especially on mobile. There are projects that create a complete keyboard simulation on mobile, but that's crazy! Unless you target an specific language like english or spanish.
