### ISSUE TITLE
Enable child prefabs to have an is-a relationship

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#236]
Is it possible to have a prefab derived from another prefab where the relationship is is-a and not has-a?

To clarify with an example:
![BasePrefab](https://user-images.githubusercontent.com/1304735/190405582-9182b50d-3305-4383-8c8a-9549265fc2de.png)

![childPrefab](https://user-images.githubusercontent.com/1304735/190405556-45f0a79c-477f-4f90-a469-35843a337f04.png)

Frequently prefabs end up being containers.  In this particular case I have a BasePushButton which has a NinePatch and some text.  I want to create various prefabs based on it to customize their properties.  This is fine as long as I am modifying game objects that exist in the base prefab (specifically the NinePatch or Text).

However if I add a new object in the derived prefab, for example to add a glowing border then the new prefab is a container that has-a button but is not a button.  In Unity you can add objects in child prefabs anywhere in the hierarchy.  This is important because you may want transforms to operate on all child objects. In this case I want a pulse effect to also apply to the border I am adding.

The other downside of the current has-a approach for child prefabs is that all the button methods need to be exposed on the new object or I make the inner button public but that adds another layer of access to all other code (i.e. trueFalseButton.pushButton.enabled = true).

Given the BasePushButton prefab is just a container it seems I should be able to specify that I want to have a derived class and in the constructor add the border to the existing container rather than creating a nested container.

I can certainly do this in custom code, but then I can no longer use the editor to layout anything in the child prefab.

**Comment by PhaserEditor2D** [comment]
I did this so fast that yet I don't believe it is working.

Please, can you test try this?

(I don't remember what's your OS)

[PhaserEditor2D-core-3.35.0-alpha-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/9576655/PhaserEditor2D-core-3.35.0-alpha-windows.zip)

[PhaserEditor2D-core-3.35.0-alpha-macos.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/9576653/PhaserEditor2D-core-3.35.0-alpha-macos.zip)

Look there is a new parameter "Allow Append Children" in the Children section of the Inspector view. Enable it for allowing adding (appending) objects to a container prefab instance.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/12187299/190445143-52527039-6233-4357-b68f-6fe75f44cd21.png">
 
Please, compile your whole project and check if there are unexpected changes in the generated code. It should not introduces new changes in the code.

**Comment by jrabek** [comment]
Oh nice!  This is great!  👏 Super fast job.  

I'll check this out later today!  Thanks man!

**Comment by jrabek** [comment]
@PhaserEditor2D this works great! Thanks for the quick turnaround!  Definitely looking forward to it in the next release.

This does feel like what should be the default behavior for container based prefabs since usually if I start with an existing prefab I want to extend it (i.e. "Allow Append Children").  If I want to create an entirely new prefab that has one or multiple existing prefabs I would just start with a container (i.e. create a new prefab).   Though I totally get that the existing behavior may be what people expect.

Either way thanks again and this will make things a lot easier for us 🙏

**Comment by PhaserEditor2D** [comment]
I'm glad it is working for you! You are welcome.

> Though I totally get that the existing behavior may be what people expect.

Yes, it is what users expect. So let's respect it. I think it will create less confusion.

By the way, there are some "bugs" with the depth commands (move up, move down, ...). I fixed it but not in the release I sent you. Do you want an updated beta release or you are going to wait for the final release?

**Comment by PhaserEditor2D** [comment]
Updated. Fixed the depth-commands bug. Please, get the latest alpha release:

[PhaserEditor2D-core-3.35.0-alpha.2-macos.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/9599052/PhaserEditor2D-core-3.35.0-alpha.2-macos.zip)
[PhaserEditor2D-core-3.35.0-alpha.2-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/9599060/PhaserEditor2D-core-3.35.0-alpha.2-windows.zip)

**Comment by PhaserEditor2D** [comment]
You can test the beta release: https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.35.0-beta.0
