### ISSUE TITLE
Adding a component to a components file deletes the custom code added to other components.

### ISSUE THREAD

**Issue by glantucan** [PhaserEditor2D/PhaserEditor2D-v3#238]
## Version
* Phaser Editor 2D Version:
3.34.0
* Operating System:
Linux (Pop OS - based on Ubuntu)
* Web Browser and version:
N/A
## Description
After creating a components file (gameObject.components) and adding a component to it (Movement.js). I edited Movement.js code, saved it. Then I add another component to gameObject.components and my custom code I added to Movement.js is deleted. It happens to me every time I try to add a new component (zip file with the project provided)

[memory-match.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/9595108/memory-match.zip)

**Comment by PhaserEditor2D** [comment]
Hi. Please, remember you should write the custom code inside the `START-USER-CODE` and `END-USER-CODE` comments:

```
  /* START-USER-CODE */

  // Write your code here.

  /* END-USER-CODE */
```

I see in your files you are writing the custom code everywhere in the file :)

**Comment by PhaserEditor2D** [comment]
Yes, keep those comments.

**Comment by glantucan** [comment]
Ok, I understand now. Thanks a lot! :)
I understand this is great for beginners and that is maybe necessary to avoid placing compiled code in the wrong place,  but I would like to have more control about the organization of the code even if that means losing some of the convenience of the GUI. Is that possible or are you considering allowing it for any future version?
Thanks again

**Comment by PhaserEditor2D** [comment]
> but I would like to have more control over the organization of the code

Please, can you provide some examples? I don't plan to change the code compiler but I am open to new ideas.

**Comment by glantucan** [comment]
That's actually very nice of you :) Let me get use to the tool and I will try to prepare an example: This will take some time as I'm doing this in my spare time and also been a long time without using Phaser, but I will do.

**Comment by PhaserEditor2D** [comment]
Sure! Please, keep in contact!

**Comment by glantucan** [comment]
Here is a first idea about how to avoid the user code delimiter comments. Forgive me if I don't see the whole picture ;P

What if instead of generating just one class for each component, level, etc. you generate two. Let's say it's for a component called Player. You could generate a base class called _Player that is updated by the GUI compiler and a second one, Player, that extends _Player and doesn't need any comments.
You loose direct sight of the members that are added from the GUI but you have complete freedom to organize the code as you want.
Alternatively you could put those members in comments as a way of documentation in Player but they could be deleted with no further consequences.

**Comment by glantucan** [comment]
Mmm, I just realized that wouldn't work for static methods like `getComponent`, 
but there are alternate patterns for the functionality they provide on each case. yo could generate a resource locator class with a map of the user component types and have there a static `getComponent` with a component type parameter. I believe that's something like what Unity had for finding components in gameObjects.
It's late here so it's possible that this is nonsense XD. I'll stop for today.

**Comment by PhaserEditor2D** [comment]
Hum... it looks like a complex solution. It introduces extra classes and at the end, you have to write a second class all by hand and the idea is the editor generates code by you.

Maybe we should focus on the cases the generated code is limiting you as a programmer, so we can improve it.

**Comment by PhaserEditor2D** [comment]
Hi

Thanks for the kind words. Don't worry, please, share all your ideas, I appreciate it! 

It is an interesting idea. It reduces the amount of "protected" sections but it adds an extra inheritance and I'm pretty sure a lot of users will complain about it. There are projects with a huge amount of prefabs, scenes, and user components. All of these pieces will have an extra class.

I understand so many comments may distract you but yet is the best alternative I found. Who knows, maybe someday JavaScript will get "partial class & method" support like in C#: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

**Comment by glantucan** [comment]
Mmm, yes, you are right I didn't have the whole picture in mind. Even if one could workaround all those cases, OOP in js is weird enough to come back at you and shoot you in the foot when you less expect it. 
That's one of the reasons I prefer a more "functional" approach in js, for me it's a pity that Phaser didn't choose that route.

Ok, I'll learn to live with it, ... for now, ... I don't guarantee I won't come back with some other funky idea ;P 
And thanks for taking the time to respond :)

**Comment by PhaserEditor2D** [comment]
Hehe, great, keep in contact.

**Comment by glantucan** [comment]
Quick update on my struggles... they are solved, I think...🤔 
You actually gave me an idea when mentioned partial classes.
We actually have something similar in javascript:
```js
const PartialDepthSort = {
  update() {
    this.gameObject.setDepth(this.gameObject.y);
  }
}

/* START OF COMPILED CODE */
class DepthSort extends UserComponent {
  constructor(gameObject) {
    super(gameObject);
    this.gameObject = gameObject;
    gameObject["__DepthSort"] = this;
  }
  static getComponent(gameObject) {
    return gameObject["__DepthSort"];
  }
  gameObject;
}
/* END OF COMPILED CODE */


Object.assign(DepthSort.prototype, PartialDepthSort);
```
This actually solves very well my needs and I can have the code most important to me at the top of the file and I can organize it as I want, using the programming paradigm I see fit, keeping separate from the generated code. 

AFAIK this is indistinguishable from having the `update`, or any other method in `PartialDepthSort` inside the  class, except perhaps for some browser optimizations that would not kick in because of my meddling  with the prototype, but I usually care more about code readability first and optimize at the end where and if needed.

**Comment by glantucan** [comment]
Of course that can't work, there is no easy way the editor can know ahead of time what I'm going to do with the prototypes. 
For me that is a small price to pay in exchange for my code to be easier to read and find. 
I know most programmers wouldn't agree with my tastes, I've had this kind of discussion many times. But at the end of the day I know I spend way more time reading code and thinking on how to fit the new feature in there than actually writing, and that's the reason I think code auto-completion, though a nice feature to have, is not that important in the long run and generally overrated. 
I'm weird, I know.

**Comment by PhaserEditor2D** [comment]
In typescript you can write something like:

```
interface PartialDepthSort extends DepthSort {
}
```

It says the compiler `PartialDepthSort` should include everything from `DepthSort`. But yet only the public features.

**Comment by glantucan** [comment]
Would that be like making a type annotation?
```js
/** @type {DepthSort} */
const DepthSortPartials = {
  update() {
    this.gameObject.setDepth(this.gameObject.y);
  },
};
```
At least this works for me. :)

**Comment by PhaserEditor2D** [comment]
Yes, like a type annotation!
