### ISSUE TITLE
Wongly formed constructor for PathFollower Prefabs

### ISSUE THREAD

**Issue by synnrocks** [PhaserEditor2D/PhaserEditor2D-v3#239]
## Version
* Phaser Editor 2D Version: v3.34.0

* Operating System: Windows

* Web Browser and version: Chrome Version 104.0.5112.102 (Build officiel) (64 bits)

## Description

1. In the scene editor, add an image
2. Right click the image > Prefabs > Create Prefab With Object
3. Set Super Class to "Phaser.GameObjects.PathFollower"
4. save /compile the prefab scene
5. Generated code does not include any path for the constructor or the call to the super constructor.

`class PrefabTest extends Phaser.GameObjects.PathFollower {`

	constructor(scene, x, y, texture, frame) {
		super(scene, x ?? 0, y ?? 0, texture || "yellow", frame);`

For PathFollower the second parameter is a path. Object is created but has no texture and wrong "x and y" parameter.
## Possible solution

Add a null parameter after the scene in super.
`super(scene, null, x ?? 0, y ?? 0, texture || "yellow", frame);`

**Comment by PhaserEditor2D** [comment]
The editor doesn't support `PathFollower` objects. I guess you created that prefab based on a `Sprite` or `Image`.

It is a good idea to support the `PathFollower` type in the editor. Please, can you open an issue about it?

**Comment by PhaserEditor2D** [comment]
Maybe, as a temporal solution, you can disable the code generation of the prefab. Just uncheck the Generate Code parameter. Then write the whole class yourself.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/12187299/191343825-cca01d90-5d47-4ca4-a259-a183cb315828.png">

**Comment by synnrocks** [comment]
Thanks for the tip and the super swift reply.

My current workaround is to modify the object in the create method, after the editorCreate execution of the scene using the prefab.
I believe another way would be to create a class from PathFollower and use this class as super class for the prefab. Then I can control the call to the constructor of PathFollower.

It allows to use all feature of the generated code.
