### ISSUE TITLE
Editor value update improvements

### ISSUE THREAD

**Issue by jrabek** [PhaserEditor2D/PhaserEditor2D-v3#243]
In Phaser Editor in order to see the result of updating a value in the inspector or the layout, the edit box must lose focus for the value to update.  That is the only way for it to happen.  For the layout tools loosing focus isn't sufficient, you must hit the ✔️ button which dismisses the tool.

One possible way to improve this would be to have any numerical input have a hover listener on its label that changes the cursor to a ↔️ icon and holding down left click would allow you to drag the value back and forth and have it instantly updated.  This could also apply to "font size" and just adjust the numerical value and keep the `px` if it is present.

Also for numerical values (or values in general) the update should occur on every edit.

Both of these changes allow for faster iteration when tweaking values.

**Comment by PhaserEditor2D** [comment]
Done. Will be ready in the next release. Thanks!
