### ISSUE TITLE
Editor should do automatically compile TS Code for Prefabs/Scenes ...

### ISSUE THREAD

**Issue by aallnneess** [PhaserEditor2D/PhaserEditor2D-v3#249]
Hello,

if you work with TypeScript you have to compile often manualy because the Editor do not automatically create TS Code for Prefabs/Scenes ...

This could increase the workflow for TS devs quite a bit.

Thanks so far,
matze

**Comment by PhaserEditor2D** [comment]
Done. This will be available for the next release.
