### ISSUE TITLE
Incorrect body (scaling) on scaled objects

### ISSUE THREAD

**Issue by aallnneess** [PhaserEditor2D/PhaserEditor2D-v3#250]
Hello,

If an object is scaled and a body is added afterwards - the dimensions of the body are incorrect and also cannot be scaled:

https://user-images.githubusercontent.com/73443724/200849819-81e7b168-b8d1-4a31-8510-ed47ee770ba7.mp4

This can be avoided if a body is assigned to the object when it is not scaled.

## Version

* Phaser Editor 2D Version: 3.36.0-alpha.1

* Operating System: Windows 10 64bit

* Web Browser and version: Edge

**Comment by PhaserEditor2D** [comment]
It is weird because it doesn't happen if you first add the body and later you scale the object. I'm working on it. By the way, please, update the editor to the latest version, you are using an alpha :)

**Comment by PhaserEditor2D** [comment]
Done. Keep an eye open because I will make a release soon.
