### ISSUE TITLE
Animation preview incorrectly displays spritesheet

### ISSUE THREAD

**Issue by aallnneess** [PhaserEditor2D/PhaserEditor2D-v3#251]
Hello,

animation preview incorrectly displays spritesheet:

Image Preview:
![image](https://user-images.githubusercontent.com/73443724/202478211-c0ba2e66-fe74-475a-9302-cea4065af3f4.png)

Animation Preview:
![image](https://user-images.githubusercontent.com/73443724/202478392-be7b1a6d-9e3e-413d-8563-1be5fa3543df.png)

## Version

* Phaser Editor 2D Version: v3.36.0

* Operating System: Windows 10 64bit
-->

[spritesheet-and-animation-json.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/10032649/spritesheet-and-animation-json.zip)

**Comment by PhaserEditor2D** [comment]
Done.

<img width="338" alt="Screenshot 4" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/12187299/21e1a957-e9b3-45ab-a40c-e7854354d20e">
