### ISSUE TITLE
Problem with building by master source - SyntaxError: Unexpected reserved word (await)

### ISSUE THREAD

**Issue by fiaful** [PhaserEditor2D/PhaserEditor2D-v3#252]
Hi everybody!

## Version

* Phaser Editor 2D Version: Current source version from Github (obtained with download the master version and not by clone - I can't clone in this moment)

* Operating System: Windows 7

* Web Browser and version: not relevant

## Description

following the steps to compile editor by source code:
1. npm install ==> ok without errors
2. npm run build ==> ok without errors
3. npm start ==> ok without errors (but I stop it to continue)
4. npx phasereditor2d-launcher -editor . -dev -disable-plugins phasereditor2d.code -project [every project I put here] ==> I got every time the same error (below - I've tried to reinstall phasereditor2d-launcher also):

```
file:///C:/Users/[my user path]/PhaserEditor2D-v3/source/editor/node_modules/phasereditor2d-launcher/cli.js:6
const execFile = await installEditor()
                 ^^^^^

SyntaxError: Unexpected reserved word
←[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)←[3
9m
←[90m    at async link (internal/modules/esm/module_job.js:37:21)←[39m
```

Any ideas?

**Comment by PhaserEditor2D** [comment]
Hi!

What's your npm/node version?

**Comment by fiaful** [comment]
> Hi!
> 
> What's your npm/node version?

Thanks for reply! My npm version below:

```
C:\Users\[my user path]>npm -version
6.14.4
```

**Comment by PhaserEditor2D** [comment]
Please try updating to the latest Node and NPM.

**Comment by fiaful** [comment]
Ok, I've updated nodejs/npm to the latest version supported (though unofficially) by my system (Windows 7), which are:
- nodejs : 15.8.0
- npm : 7.5.1

(if it should be useful to someone else, through the indications present here: (https://stackoverflow.com/questions/62212754/latest-nodejs-compatible-with-windows-7))

now i can complete the command

`npx phasereditor2d-launcher -editor . -dev -disable-plugins phasereditor2d.code -project [every project I put here]`

but shortly after it returns to the prompt without printing any error message.

after various tests, I decide to try to launch the executable PhaserEditor2D.exe directly (which is launched from C:\Users\[my user]\.phasereditor2d\installs\PhaserEditor2D-core-3.36.0-windows\PhaserEditor2D)

and apparently the executable is compiled for 64bit architecture (while my system is 32bit)

Is it possible to get the executable PhaserEditor2D.exe compiled for 32bit somewhere?

**Comment by PhaserEditor2D** [comment]
Oh, no, there isn't a 32-bit build.

**Comment by fiaful** [comment]
oh... ok... my tests die here...

**Comment by PhaserEditor2D** [comment]
Hi! You can try running it in the cloud: https://www.youtube.com/watch?v=lndU7UAjzgo
