### ISSUE TITLE
When launch a blank  white screen in phaser editor windows appear and not working.

### ISSUE THREAD

**Issue by kitecodingsrl** [PhaserEditor2D/PhaserEditor2D-v3#253]
## Version

* Phaser Editor 2D Version: <code>PhaserEditor2D-allInOne-3.36.0-linux

</code>

* Operating System: Ubuntu 20.04

* Web Browser and version:

## Description

[22366:1122/092317.546868:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

(node:22334) electron: Failed to load URL: http://127.0.0.1:4045/editor/ with error: ERR_UNSAFE_PORT

![blank_screen_allinone](https://user-images.githubusercontent.com/118822473/203321350-7389d5c4-7804-4306-9cf5-29f7245ad995.png)

**Comment by PhaserEditor2D** [comment]
Hi! Thanks for posting the issue.

It says that port 4045 is unsafe for Electron. I tested that port in my environment (macos) and it works. 

Maybe there is a configuration we can set in linux. I'm investigating. In the meantime, please, can you send me this file please?

```
/home/{your user}/.phasereditor2d/all-in-one/user-data.json
```

There are a map of the http ports and the projects. I want to change the port it is using.

**Comment by PhaserEditor2D** [comment]
Hum... I found chromium has a couple of ports labeled as unsafe, and 4045 is one of them:

https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/net/base/port_util.cc#96

I have to prevent using them in the all-in-one editor. In the meantime, please, send me the `user-data..json` file for fixing it in your setup.

**Comment by PhaserEditor2D** [comment]
By the way, I think but just deleting the `/home/{your user}/.phasereditor2d/all-in-one/user-data.json` file, the editor will take a new port for the server and should work.

Please can you confirm this temporal solution?

**Comment by kitecodingsrl** [comment]
deleting this its works just only for launch the program but when you open a directory of a game or project stay in blank screen.
<code>/home/{your user}/.phasereditor2d/all-in-one/user-data.json</code>

**Comment by PhaserEditor2D** [comment]
And it shows the same error in the terminal? I guess you are not using an antivirus.

You also can try Phaser Editor 2D Core https://help-v3.phasereditor2d.com/intro/core.html

**Comment by PhaserEditor2D** [comment]
Hi! Did you have any progress?

**Comment by kitecodingsrl** [comment]
not a all, i just used the core version with this command ./PhaserEditor2D  -project GameDirectory and run in a port number in Web browser.
Later I tried install the PhaserEditor2D-allInOne in directory /home/user/PhaserEditor2D-allInOne and run sh install.sh
and then I copied phasereditor2d-PhaserEditor2D.desktop to the Desktop and then allowed to launch in the Desktop and start working.

**Comment by PhaserEditor2D** [comment]
Sorry, I don't understand.

You say you tried with Core. Did it work?

And you say you tried again with allInOne. Did it work?

**Comment by kitecodingsrl** [comment]
yes both worked
