### ISSUE TITLE
Nine Patch Images render upside down in Phaser v3.60 beta 17

### ISSUE THREAD

**Issue by CodestarGames** [PhaserEditor2D/PhaserEditor2D-v3#256]
![image](https://user-images.githubusercontent.com/5861090/208229066-baf4f641-86f2-4db1-bda7-b576402e9e1a.png)

* Phaser Editor 2D Version:
    "phasereditor2d-launcher": "^3.33.2-beta.1"
    "phasereditor2d-ninepatch-plugin": "1.1.0-beta.1"
    
* Operating System: Windows 11

* Web Browser and version: Chrome

## Description
Nine Patch Images render upside down in Phaser v3.60 beta 17

**Comment by PhaserEditor2D** [comment]
+1

By the way, why `"phasereditor2d-launcher": "^3.33.2-beta.1"`? And `"phasereditor2d-ninepatch-plugin": "1.1.0-beta.1"`?
There is the newest version of both.

**Comment by PhaserEditor2D** [comment]
It works for me in the editor:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/12187299/208231040-c8bf8245-004c-427f-8335-08348852e4ad.png">

And works for me in the game:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/12187299/208231077-686c25ea-1ec6-4858-88af-f2323d49d292.png">

I used the `NinePatchImage` and `NinePatchContainer` objects. The NinePatch objects don't work with the editor & Phaser v3.60.

**Comment by CodestarGames** [comment]
I updated phaser editor, the ninepatch plugin, and regenerated the source files for the plugin. On phaser 3.6.0-beta 17 it is drawing both ninepatch images and ninepatch containers upside down.

![image](https://user-images.githubusercontent.com/5861090/208243256-5d68c37c-87fa-461c-882b-322ced7cb924.png)

In the editor they are correct, but I assume this is because the internals of the editor use an older version of phaser for rendering.

I'm on 
    "phasereditor2d-launcher": "^3.36.2",
    "phasereditor2d-ninepatch-plugin": "^1.2.0",

**Comment by PhaserEditor2D** [comment]
Is it possible to get the same assets and test it locally? I need to reproduce the error. You can send le ut in a private message.

**Comment by CodestarGames** [comment]
![window-nine](https://user-images.githubusercontent.com/5861090/208356672-3b3c73ed-1c02-49eb-a8a3-a20286d27a57.png)

Here's the asset I'm using for the ninePatchImage, it's a temp asset so  I can share it here.

**Comment by CodestarGames** [comment]
I fixed the issue. It looked like my own user error.
