### ISSUE TITLE
Cannot upload file [Windows 10]

### ISSUE THREAD

**Issue by tomclancyya** [PhaserEditor2D/PhaserEditor2D-v3#26]
Steps to reproduce:
1) launch `PhaserEditor2D.exe -desktop`
2) create new project
3) Rich-click on the assets folder and press the Upload Files option of the context menu.
4)  Click on the Browse button and select the image file in your computer.
5) Press the Upload button.

what expected:
The image is uploaded to the assets folder and shown in the Files view.

what I got:
Alert window: error sending file

Server logs:
```
2020/05/23 20:13:06 Starting in Desktop mode
2020/05/23 20:13:06 Loading workspace at C:\PhaserEditor2D_V3\workPlace
2020/05/23 20:13:06 Listening at http://127.0.0.1:1959/editor
2020/05/23 20:13:06 Opening browser at http://127.0.0.1:1959/editor
2020/05/23 20:13:19 Upload to project folder: Game/assets
2020/05/23 20:13:19 Copying file C:\Users\name\AppData\Local\Temp\phasereditor-upload-561477607.tmp to C:\PhaserEditor2D_V3\workPlace/Game/assets/planet.png
2020/05/23 20:13:19 rename C:\Users\name\AppData\Local\Temp\phasereditor-upload-561477607.tmp C:\PhaserEditor2D_V3\workPlace/Game/assets/planet.png: The process cannot access the file because it is being used by another process.
```

How I tried to fixed:

- turn off all antivirus
- run cmd in administrator mode
- change the workplace to c:\PhaserEditor2D_V3 to prevent any problems with path

PhaserEditor2d v3.0.1
GoogleChrome 83.0.4103.61

**Comment by PhaserEditor2D** [comment]
Thanks @tomclancyya for your detailed report.

**Comment by PhaserEditor2D** [comment]
I will work on this soon, in the meantime, you can copy the files directly in the folder, without the Upload dialog. When you click/focus on the IDE, it will look for changes in the filesystem and show the new files.

**Comment by tomclancyya** [comment]
Roger that, thanks!

**Comment by PhaserEditor2D** [comment]
Hi @tomclancyya 

The problem is that Windows does not allow the server to move the uploaded temporal file to the project folder.

I changed it and now it copies (not move) the file. Please, test this build and tell me if it works for you:

[PhaserEditor2D-3.0.1-fixes-upload.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/4672117/PhaserEditor2D-3.0.1-fixes-upload.zip)

**Comment by tomclancyya** [comment]
Hi @PhaserEditor2D 
Tested, It works like a charm now! 
Thanks for fixing!

**Comment by PhaserEditor2D** [comment]
Great! You are welcome.
We are going to release a new version in the few days.
