### ISSUE TITLE
When I Click "run"  a project, it didn't compile or build 

### ISSUE THREAD

**Issue by iwanglian** [PhaserEditor2D/PhaserEditor2D-v3#271]
## Version

* Phaser Editor 2D Version: 3.36.2

* Operating System: Apple M1 Pro.   13.1 (22C65)

* Web Browser and version: Chrome 110.0.5481.177（stable） (arm64)

## Description

When I Click "run"  a project, it didn't compile or build , but open browser with url "http://localhost:8080/", the web page was "ERR_CONNECTION_REFUSED"

**Comment by PhaserEditor2D** [comment]
Hi!

What template did you use for creating the project? If it is typescript or webpack, you first need to compile the project and run the webserver.

For the address you mention, I think you have a webpack project. So you need to do first:

```
npm install
npm update
npm start
```

**Comment by PhaserEditor2D** [comment]
Closing until get new info.
