### ISSUE TITLE
Lists : Ability to rearrange order of list items

### ISSUE THREAD

**Issue by SolSearcher** [PhaserEditor2D/PhaserEditor2D-v3#277]
Issue : 
- When working with lists, the order is set based on when new items are added in with them coming in at the bottom. To rearrange items in the list you need to remove the item and add it again for it to show up at the bottom of the list. If you want to iterate through the list in a specific order this makes it challenging.

Solution:
- Have a way to rearrange items in a list from the list view. Possibly using page up / page down like in the Outline window. It would appear in the window I'm screenshotting below. 

![image](https://user-images.githubusercontent.com/28418166/233697201-a092a04e-5d57-4352-b955-2cef188f248f.png)

- it could mirror this functionality with right click where you have different depth functions
![image](https://user-images.githubusercontent.com/28418166/233697509-52cc9941-c6d3-4ac5-8e2b-3969d47a7ecc.png)

**Comment by SolSearcher** [comment]
Excellent! That seems very intuitive. Thanks for addressing this issue

**Comment by PhaserEditor2D** [comment]
Like this? :)

<img width="274" alt="image" src="https://user-images.githubusercontent.com/12187299/235772264-4203e984-9e65-4324-8d8d-4316a34fc4e7.png">

**Comment by SolSearcher** [comment]
Awesome! Can't wait to try it out!! Hope this helps a lot of other people too

**Comment by PhaserEditor2D** [comment]
Done!

<img width="553" alt="image" src="https://user-images.githubusercontent.com/12187299/235813869-97cd928a-20ee-43bd-a9e7-0979c28693d5.png">
