### ISSUE TITLE
Can not set the offset of Arcade Physics Body Geometry

### ISSUE THREAD

**Issue by k206i** [PhaserEditor2D/PhaserEditor2D-v3#280]
## Version

* Phaser Editor 2D Version: 3.60.1

* Operating System: Windows 10

* Web Browser and version:Opera GX  LVL4 (core: 97.0.4719.89)

## Description

Offset of Arcade Physics Body Geometry not working.
I have seted some offset:
![image](https://user-images.githubusercontent.com/20324335/235357345-447c0134-7375-49c2-8c11-033af5817c0f.png)

But body has collide like offset was not set:
![image](https://user-images.githubusercontent.com/20324335/235357402-19fefbf7-551a-4e8c-928f-9839b7bf6f43.png)

**Comment by PhaserEditor2D** [comment]
Please can you enable the physics debug? In that way we can know what's going on. In the game config, set:

```
{
          physics: {
			default: "arcade",
			arcade: {
				debug: true				
			}
		}
}
```

**Comment by PhaserEditor2D** [comment]
BTW, is it scaled the platform object?

**Comment by PhaserEditor2D** [comment]
Please, try without scaling the platform. Or you have to call the `platform.body.updateFromGameObject()` method after you scale the platform.

**Comment by PhaserEditor2D** [comment]
BTW, I recommend you take a look at this tutorial. In this part it talks about refreshing the body after changing the scale: https://youtu.be/nMXOcrQU9cs?list=PLB8gI_5U0MvBiK7GExn8ONPk5jDPd2KlE&t=237

**Comment by k206i** [comment]
> Please, try without scaling the platform. Or you have to call the `platform.body.updateFromGameObject()` method after you scale the platform.

It works for me. Thank you!

**Comment by k206i** [comment]
> BTW, I recommend you take a look at this tutorial. In this part it talks about refreshing the body after changing the scale:

Thanks for your tutorials! They help a lot!
