### ISSUE TITLE
Font Size/Text enlarging feature

### ISSUE THREAD

**Issue by DriesVG-ui** [PhaserEditor2D/PhaserEditor2D-v3#281]
Hey there,

I have been using the editor for a while and I do have an issue with the basic small font size of the code text...

I'd like to see a feature/combination (like ctrl+ or sth) so you can enlarge the text/font-size.

Thanks

**Comment by PhaserEditor2D** [comment]
Agree.

Btw, you can create Text object prefabs with the desire font/size. Probably you have just a few combinations on your game so you have to set it once.

**Comment by PhaserEditor2D** [comment]
In the previous release, we implemented a way to inc/dec numeric values by using the mouse and the keyboard:

https://phasereditor2d.com/blog/2024/02/phaser-editor-2d-v3670-is-released

<img width="701" alt="Screenshot 2024-03-22 at 12 21 48 PM" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/12187299/f5a6212b-8173-4150-ab38-788daed3bef6">
