### ISSUE TITLE
Code Generator does not gen the path of nested prefabs

### ISSUE THREAD

**Issue by gregwoodsfrontier** [PhaserEditor2D/PhaserEditor2D-v3#282]
## Version 3.60

* Phaser Editor 2D Version:

* Operating System:

* Web Browser and version:

## Description
One thing about nested prefabs.
So I have a ScriptNode that needs to take a Sprite as argument in editor.
I have a PlayerContainer that contains that sprite and also hitboxs, hurtboxes.
I tried to make the player sprite nested prefab and pass that prefab as args to that node.
But the editor gens the code with error. Instead of "playerContainer.sprite" the editor gens "sprite"

I think that is a bug in editor that needs fixing.

Discord Message Link: 
https://discord.com/channels/692441121317715999/729142563273179186/1107659781373702236

## Possible solution
Make the code generator gen the path of the nested prefab.

**Comment by PhaserEditor2D** [comment]
It is not the code generator else the dialog for selecting the nested prefab one outputs `sprite` instead of `playerContainer.sprite`. I'm working on it.

**Comment by PhaserEditor2D** [comment]
Done.
