### ISSUE TITLE
unchangeable classes and Scenes 

### ISSUE THREAD

**Issue by DriesVG-ui** [PhaserEditor2D/PhaserEditor2D-v3#283]
Hey,

I have notices this before but sometimes it is really frustrating when you change something within your classes or scene file and when you edit something the editor erases everything that you wrote in that file...

Sure I understand how it works and I know it is not between the "// Write your code" tags but the issue where I am in is like this: 

I create a BaseScene file where I can put every function, method I want to use so I don't have to write this every time when I create a new Scene. So I change the first line of the scene like 
class Level2 extends **Phaser.Scene** 
into
class Level2 extends **BaseScene** 

It works...but the frustrating thing is that it changes back into class Level2 extends **Phaser.Scene** after the first thing I change into the scene...

Isn't there something you can do about this to keep your own code from overwriting? It would make my work  (and others)a lot easier.

**Comment by DriesVG-ui** [comment]
Edit: I just found an option where you can edit your super class...oh well...so maybe this problem is not as relevant.

**Comment by PhaserEditor2D** [comment]
Yes, you can set the super class parameter! Keep in contact!
