### ISSUE TITLE
v3.65.0 uploaded with a wrong release date in the title

### ISSUE THREAD

**Issue by dukemagus** [PhaserEditor2D/PhaserEditor2D-v3#300]
## Version

3.65.0

* Phaser Editor 2D Version:

* Operating System: N/A

* Web Browser and version: N/A

## Description
The release title says it will be released december 2024

https://github.com/PhaserEditor2D/PhaserEditor2D-v3/releases/tag/v3.65.0

## Possible solution
Edit the title

**Comment by PhaserEditor2D** [comment]
Getting older too fast! Hehe thanks!
