### ISSUE TITLE
Extending container not supported in editor

### ISSUE THREAD

**Issue by JernejHabjan** [PhaserEditor2D/PhaserEditor2D-v3#303]
Current setup:
![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/5eddb308-e92f-4342-9d0a-1906a57a52f0)

After drag-and-dropping another image in:
![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/11c057d7-174b-41cd-873f-1295ddc531f7)

It doesn't detect that the prefab already includes a container:
![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/7fcf3f67-66c3-4fae-a4bf-25a0733762a2)

Drag and dropping works normally if I use default Container object though, but not my extended one

**Comment by PhaserEditor2D** [comment]
Hi. I can't find the issues there. Please, can you give more details?

**Comment by PhaserEditor2D** [comment]
Hi @JernejHabjan are you still experiencing this issue?

**Comment by JernejHabjan** [comment]
Yes, but im using built in container now instead

**Comment by JernejHabjan** [comment]
provided an example (generated new typescript webpack project and added my `ActorContainer` scene to it:

[example_actor_container.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/13893757/example_actor_container.zip)

Steps to reproduce:
- Open `ContainerExtendingActorContainer.scene`
- change `ContainerExtendingActorContainer` which is now of type `Container` and holds 2 images to `ActorContainer`
  ![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/618ab780-6891-46fe-8405-50ce5d865432)
- note that all images on left side disappear
  ![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/82429e21-8b55-401a-8de9-9f6475f7be85)
- and when I try to add image back to this container, it just creates new container instead
  ![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/4598f4c6-7ba2-4f9f-b0e6-3be1a6cffb4f)
