### ISSUE TITLE
Set custom property to Phaser game object

### ISSUE THREAD

**Issue by JernejHabjan** [PhaserEditor2D/PhaserEditor2D-v3#304]
![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/e6db4752-7a51-4d06-8e8e-9b4b92d88cb9)

This image gameobject also has `z` coordinate, that I'd like to set in the editor, but it's not exposed in the inspector panel. Allow setting any custom property like for prefabs also to game objects like image, sprite

**Comment by PhaserEditor2D** [comment]
Hi, you can create a user component with additional user properties and add it to any game object in the scene.

https://help-v3.phasereditor2d.com/scene-editor/user-components.html#

**Comment by PhaserEditor2D** [comment]
Hi @JernejHabjan 

So you don't need a custom/user property, what you need is to add the Z property to the editor. It means, a new feature in the editor.

**Comment by JernejHabjan** [comment]
@PhaserEditor2D that's right. But I presume that most users won't need to see Z property in the panel. Could we have a button to "add" a property and it's value?

**Comment by PhaserEditor2D** [comment]
> Could we have a button to "add" a property and it's value?

Mmm... I don't know I have to think more about it. We have a button to add a user component :)

Btw, why do you need the Z property? What kind of stuff you are making? Maybe it is part of a bigger feature that I plan to implement.

**Comment by JernejHabjan** [comment]
I'd like to use Z axis to specify at which height the block / sprite is placed in isometric world, as I'd like to create multi-height isometric world.

![image](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/21958321/0d6b6418-e22e-4f5d-b9ef-64933ec0e850)

currently I'm writing this Z in custom prefab exposed property, but ideally I'd like to set it to Gameobject.Image as it's just terrain

**Comment by PhaserEditor2D** [comment]
Oh yes, I have to do more about isometrics. Like a sorting layer. It will help in the case of isometrics and also other kind of worlds.
