### ISSUE TITLE
Pasting multiple script nodes changes their ordering

### ISSUE THREAD

**Issue by tibimunteanu** [PhaserEditor2D/PhaserEditor2D-v3#314]
## Version

* Phaser Editor 2D Version: 3.67

* Operating System: Windows 11

* Web Browser and version: Chrome

## Description

When you select more than 1 consecutive sibling script nodes and paste them on another game object or script node, they are pasted with inverted ordering:

Ex:
GameObjectX
  ScriptA
  ScriptB

-- select both ScriptA and ScriptB and copy--
-- select GameObjectY and paste --

GameObjectY
  ScriptB
  ScriptA

**Comment by PhaserEditor2D** [comment]
Yes, and it happens also when you paste game objects into a container. I will work on this.

**Comment by PhaserEditor2D** [comment]
Done.
