### ISSUE TITLE
Cannot change property values of component

### ISSUE THREAD

**Issue by tomas-correia** [PhaserEditor2D/PhaserEditor2D-v3#316]
## Version

* Phaser Editor 2D Version: 3.66.0

* Operating System: Windows

* Web Browser and version: Firefox Developer Edition (unable to check version atm)

## Description

The editor won't let me edit the values of the properties of a component. This component is associated with a child of a prefab, which is nested inside another prefab. When having this last prefab open, I am able to see the component associated with the object in the Inspector, but it won't let me edit the values, as if they were locked.

## Possible solution

?

**Comment by tomas-correia** [comment]
> Please, can you test this build?
> 
> [PhaserEditor2D-core-3.68.0-beta-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/14841947/PhaserEditor2D-core-3.68.0-beta-windows.zip)
> 
> It is Phaser Editor 2D Core, so you have to run it from the CLI:
> 
> ```
> > PhaserEditor2D.exe -project path\to\project
> ```
> 
> Open the browser in `http://localhost:1959/`.

Yeah this build shows the padlocks near each property, allowing me to unlock them and change the values. It also compiles correctly. It works.

**Comment by PhaserEditor2D** [comment]
Great! Please, use the editor this way until I release the new version. It will be soon. Maybe during this week. Thanks!

**Comment by PhaserEditor2D** [comment]
Try this one!
 
[PhaserEditor2D-core-3.68.0-beta-windows.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/14845871/PhaserEditor2D-core-3.68.0-beta-windows.zip)

**Comment by tomas-correia** [comment]
Thanks! That fixed it.
