### ISSUE TITLE
In-App Update

### ISSUE THREAD

**Issue by NickChowHK** [PhaserEditor2D/PhaserEditor2D-v3#32]
May I know there is any plan of the In-App Update function like the Editor V2?

**Comment by PhaserEditor2D** [comment]
We don't plan to release a full in-app update function for now.
But an in-app notification (like VSCode does) is something that we will love to do. Maybe soon.

Another option we are thinking is to create an NPM package with the editor. As an alternative download and update channel.

**Comment by NickChowHK** [comment]
Thank you for your prompt reply. It sounds good to achieve this purpose with the NPM package and in-app notification.

**Comment by PhaserEditor2D** [comment]
Just implemented the "new version notification". The next release will look like this:

![image](https://user-images.githubusercontent.com/12187299/82841715-18239900-9ea5-11ea-83b0-bfc040db5b62.png)

**Comment by PhaserEditor2D** [comment]
Done.

In the next version you will be able to run:
```
$ PhaserEditor2D -update
```
It will download the latest version, unpack it, and replace the old files.

If you like, you can just download the latest version zip with:
```
$ PhaserEditor2D -download
```
