### ISSUE TITLE
Can't load game.js in Chrome with macOS Catalina

### ISSUE THREAD

**Issue by klattiation** [PhaserEditor2D/PhaserEditor2D-v3#37]
Hi, I've just downloaded the installer on macOS Catalina and started Phaser Editor 2D with the command line. The editor works well at http://127.0.0.1:1959/editor/ and I'm able to save files locally, but when I hit the "run" button, I just get a black screen. When I open the network tab in the Chrome dev tools, I can see that the game.js can't be loaded.

![image](https://user-images.githubusercontent.com/2530556/82816610-bf033780-9e9b-11ea-8ef2-d0d0081e4bc1.png)

**Comment by PhaserEditor2D** [comment]
Hi,

Did you create a TypeScript project or a JavaScript project?

If it is a TypeScript project you need to compile it first.

**Comment by klattiation** [comment]
Ah alright, yes it's a TypeScript project and compiling solved the issue :D
Thanks for your help!

**Comment by PhaserEditor2D** [comment]
Great! I will change the template config to open the README file when you create the project. Thanks.
