### ISSUE TITLE
Package whole application with electronjs

### ISSUE THREAD

**Issue by zackexplosion** [PhaserEditor2D/PhaserEditor2D-v3#43]
I think the Editor will be better if using the  [Electron.js](https://www.electronjs.org) to package whole application.

Just like VSCode, a real desktop app.

**Comment by PhaserEditor2D** [comment]
Hi @zackexplosion and  @jadbalout

In the latest release, we introduced some changes to improve the desktop-like experience with Phaser Editor.

Please, can you take a look at the release notes?

https://phasereditor2d.com/blog/2020/10/phaser-editor-2d-v380-released-welcome-tilemaps

With a minimum of configuration, you can run the editor with Chrome in application mode. Please, tell me if it works for you and if you find other advantages in an electron wrapper.

Thanks,
Arian.

**Comment by PhaserEditor2D** [comment]
Done in v3.9.0.
