### ISSUE TITLE
 get rid of the alert "missing index.html file at the root folder"

### ISSUE THREAD

**Issue by mikestonecodes** [PhaserEditor2D/PhaserEditor2D-v3#44]
I have loader that loads JavaScript files dynamically, so everytime I open a scene I get this popup up "missing index.html file at the root folder"

**Comment by PhaserEditor2D** [comment]
Done.

**Comment by PhaserEditor2D** [comment]
It is on `develop` branch. You can test it [following these steps](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/develop/BUILD.md).
