### ISSUE TITLE
option to remove javascript field declarations from compiled javascript 

### ISSUE THREAD

**Issue by mikestonecodes** [PhaserEditor2D/PhaserEditor2D-v3#45]
The newest version adds https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Field_declarations , which don't work in safari yet https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet .  I've been deleting them manually kind of annoying. maybe it would be cool to have some sort template system where you can choose what gets outputted to the JavaScript  / typescript file. another option would be to have a "hook", so a script that is run everytime a file is compiled in order to run babel to compile to es5  or webpack. having a compiled webpack'd bundle would be pretty sweet.

**Comment by PhaserEditor2D** [comment]
Done, will be included in the next release.

Now it looks like this:

```javascript
class Dragon extends Phaser.GameObjects.Sprite {
	
	constructor(scene, x, y, texture, frame) {
		super(scene, x, y, texture || "dragon", frame !== undefined && frame !== null ? frame : "dragon/Flaming_000");
		
		/** @type {number} */
		this.property1 = 10;
		/** @type {Phaser.GameObjects.Sprite} */
		this.property2;
	}
}
```

The changes are in the `develop` branch, you can test it following the [Build Guide](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/develop/BUILD.md).
