### ISSUE TITLE
pan tool

### ISSUE THREAD

**Issue by mikestonecodes** [PhaserEditor2D/PhaserEditor2D-v3#46]
in the same way you select the Translate tool,  add the option to select a Pan tool. Optionally including holding space and dragging to pan, and adding scroll bars

**Comment by PhaserEditor2D** [comment]
Done. With the `Space` key you can select the Pan tool.

![image](https://user-images.githubusercontent.com/12187299/90083056-7a8b7900-dcdf-11ea-85b7-f6ad15d9ebd9.png)

When it is activated, the cursor shows a "grab" icon, and when it is panning, it shows a "grabbing" icon.

![image](https://user-images.githubusercontent.com/12187299/90083095-a0188280-dcdf-11ea-9d4f-9a8e4da9880c.png)
