### ISSUE TITLE
pressing backspace or delete on tools or inspector should snap back to a default value

### ISSUE THREAD

**Issue by mikestonecodes** [PhaserEditor2D/PhaserEditor2D-v3#47]
pressing backspace or delete on origin tool should snap the origin to 0.5 0.5

pressing backspace or delete on translate tool should snap back to 1 1

pressing backspace or delete on rotate tool should snap back to 0

 when you clear origin X Y in inspector it should return to 0.5 instead of NaN

 when you clear angle inspector it should return to 0 instead of NaN

 when you clear scale inspector it should return to 0 instead of NaN
 
etc 

you can recreate the NaN bugs by selecting an item in the inspector , pressing delete until there is no text and then pressing enter

![Peek 2020-06-26 23-03](https://user-images.githubusercontent.com/1703689/85901066-462c2e00-b801-11ea-81e5-f7529b355bb0.gif)

**Comment by PhaserEditor2D** [comment]
Done. Now when you delete the value of a number field, it will set the default value of it. If the input uses an invalid format, like `oiuoi87`, then that input will be ignored.

This change is available in the `develop` branch.
