### ISSUE TITLE
 Moving objecst by the arrow key not updating transform panel in realtime.

### ISSUE THREAD

**Issue by zackexplosion** [PhaserEditor2D/PhaserEditor2D-v3#52]
## Version 

* Phaser Editor Version: 3.3.0

* Operating system: Macos

## Description
![ezgif com-optimize](https://user-images.githubusercontent.com/5180966/86363132-fc33c400-bca8-11ea-8a88-ed2815b312e8.gif)

**Comment by PhaserEditor2D** [comment]
Fixed.

You can test it following [these steps](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/master/BUILD.md).
