### ISSUE TITLE
Option to mark a scene as a preload scene

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#53]
It would be great if there was a checkbox to mark a scene as "Preload", which will move the generated sprite code over to the specified preload method instead of the create method. Currently, I have to manually write code to display sprites in my preload scene.

**Comment by PhaserEditor2D** [comment]
Please, can you write some code examples? I don't get what's your proposition.

**Comment by ItsGravix** [comment]
My proposition is to bring back this feature from Phaser Editor v1. Enabling the scene as a preloader will make it so all the sprites are created in the preload method.

```
preload() {
    this.add.sprite(0, 0, "phaser", "loading_dino");
};
```

https://help.phasereditor2d.com/v1/canvas.html?highlight=preload#preloader-state-configuration

**Comment by PhaserEditor2D** [comment]
You can do that!

Look in the **Compiler Scene Settings** you can change the name of the method to preload the assets and create the objects. So, you can say the editor to generate a `_preload` method and a `_create` method, then, you can write your scene like this:

```javascript

class Level extends Phaser.Scene {
	
	_preload() {
		// generated by the compiler

		this.load.pack(...)
	}

	_create() {
		// generated by the compiler

		this.add.image(...)
	}

	// start user code

	preload() {
		this._create();
		this._preload();
	}

	// end user code
}
```

**Comment by PhaserEditor2D** [comment]
BTW, I just fixed an issue with the dialog to select the asset pack files to preload. I think I will do a point release with this fix. In the meantime, you can test it following [these steps](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/develop/BUILD.md).

**Comment by PhaserEditor2D** [comment]
Hi @ItsGravix 

Is it find the solution I pointed in previous comments?

**Comment by ItsGravix** [comment]
@PhaserEditor2D Yes that solution works fine!

**Comment by PhaserEditor2D** [comment]
Great, I am closing this.
