### ISSUE TITLE
Pressing the delete button on an asset pack doesn't do anything

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#54]
When I press this delete button in an asset pack, nothing happens. I have to press the delete **key** for it to delete.

![image](https://user-images.githubusercontent.com/9307505/86527234-06052500-be6b-11ea-977f-afff3800c7f6.png)

**Comment by PhaserEditor2D** [comment]
Done.

You can test it following [these steps](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/blob/develop/BUILD.md).
