### ISSUE TITLE
Better refractoring in the editor

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#55]
When you rename a .scene file, it should change its corresponding .js file and possibly also rename the Scene Key. 
Make sure the scene is compiled so the .js file has an updated class name.

**Comment by PhaserEditor2D** [comment]
Also, it should update all asset pack files that reference the `.js` file.

This requires the implementation of a complete refactoring framework.

**Comment by PhaserEditor2D** [comment]
Thinking more about this... I think it is a complex issue because it also requires renaming the class generated by the editor and I'm not going to implement it :)
