### ISSUE TITLE
Option to exclude a directory in the project so it doesn't get indexed.

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#59]
### Option to exclude a directory in the project so it doesn't get indexed.
**I am working with many cosmetic assets that get loaded dynamically using code.** The problem is that I cannot include all the assets in my project because I quickly hit the max file limit. The current fix is to only have the assets in the production server, but this becomes hard to manage because I cannot include it in our GitHub repository.

**The solution to this problem** would be including a config file or menu that allows you to list all the directories that should be ignored by the editor and an option to increase the max file limit. Thank you!

**Comment by PhaserEditor2D** [comment]
Done.

If you create an empty `.skip` file, that folder will be ignored by the editor.

Yet I would like to keep the restriction on the number of files. I think it is not good for the editor to handle to so many files, and it forces the user to remove (or ignore) the unrelated files.
