### ISSUE TITLE
Playable Build Option - Single in-lined index.html

### ISSUE THREAD

**Issue by facecjf** [PhaserEditor2D/PhaserEditor2D-v3#6]
Digging the ease of use of the Phaser Editor. Would be nice if there were a build option to build the game in a single html file. (Data URI base 64 approach) Many, including myself, use phaser to create playable ads. One of the biggest challenges is that many of the ad networks have limitations in regards to html5/javascript playables. Facebook for example requires a single index.html file with a 2MB limit. Which Phaser and it's community has made possible - would be sweet if this could be done via the Phaser Editor.

**Comment by PhaserEditor2D** [comment]
I think the best is to make a plugin for a web bundler like webpack.
