### ISSUE TITLE
Creating phaser shapes trough the editor.

### ISSUE THREAD

**Issue by PyChaps** [PhaserEditor2D/PhaserEditor2D-v3#60]
When I'm creating games I create a lot of shapes for example: this.add.rectangle(options);
And I don't found this option of creating shapes in the editor so I've suggested this feature to you. Thanks

**Comment by PyChaps** [comment]
When I'm creating games I create a lot of shapes for example: this.add.rectangle(options);
And I don't found this option of creating shapes in the editor so I've suggested this feature to you. Thanks

**Comment by PhaserEditor2D** [comment]
Yes, this is something we want to do in the near future. Maybe after two or three releases. Thanks.

**Comment by PhaserEditor2D** [comment]
Implemented Rectangle, Ellipse, and Triangle shapes. It is available in the `develop` branch. 
![image](https://user-images.githubusercontent.com/12187299/98560448-c82f6780-2275-11eb-87e2-7912c5fb1f45.png)
