### ISSUE TITLE
Sort Items On Texture Selection Menu

### ISSUE THREAD

**Issue by Connor800** [PhaserEditor2D/PhaserEditor2D-v3#61]
Currently said menu displays items without any sorting whatsoever. Adding alphabetical sorting or at least an option to change how items are displayed would be helpful as it'd greatly speed up finding a certain texture quickly.

**Comment by PhaserEditor2D** [comment]
Done. Now all content shown in viewers is sorted.

![image](https://user-images.githubusercontent.com/12187299/90103992-75dfb880-dd11-11ea-8b41-b10c6aa172c7.png)
