### ISSUE TITLE
Sprite Prefab Not Passing Arguments To Super

### ISSUE THREAD

**Issue by Connor800** [PhaserEditor2D/PhaserEditor2D-v3#62]
## Version

* Phaser Editor 2D Version: v3.4.0

* Operating System: Windows 10 x64

* Web Browser and version: Microsoft Edge 84.0.522.52 (Official build) (64-bit)

## Description

When creating a prefab that extends a Sprite object with no texture, instances of this prefab that do have textures and possibly a frame (from multiatlases), the prefab code generated will not pass that frame argument to the super call.
### Prefab Sprite Properties
![image](https://user-images.githubusercontent.com/44991848/89639644-93c19f00-d873-11ea-8071-bb3820f01ffa.png)
### Prefab Generated Code
![image](https://user-images.githubusercontent.com/44991848/89639710-b3f15e00-d873-11ea-80a5-c9928bd46efa.png)
### Prefab Instance Using Frame
![image](https://user-images.githubusercontent.com/44991848/89639749-c370a700-d873-11ea-97ae-46013b7d916c.png)

## Possible solution

Add a texture with frame to the prefab Sprite. This is not desired as the texture used may not be available when an instance is created.

**Comment by PhaserEditor2D** [comment]
Done.

**Comment by Connor800** [comment]
Thank you!
