### ISSUE TITLE
Copied scenes and prefabs are not assigned a new scene ID

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#63]
## Version

* Phaser Editor 2D Version: v3.4.0

* Operating System: Windows 10 x64

* Web Browser and version: Google Chrome

## Description

When copying a .scene file, the scene identifier used by the editor remains the same, which causes many issues and the editor will not know what to do with two identical scenes.

![image](https://user-images.githubusercontent.com/9307505/89817478-313bfd80-db16-11ea-8b45-9754bd74275a.png)

## Possible solution

The solution to this problem would be to generate a new ID when a prefab is copied.

**Comment by PhaserEditor2D** [comment]
Now, when there is a duplicated scene file, it shows an error message:

![image](https://user-images.githubusercontent.com/12187299/89936027-14b8c780-dbe1-11ea-90db-c20c48c16cb6.png)

And you can run the **Fix Duplicated Scenes ID** command, to generate a new ID for the newer files. It means, the oldest file with the same ID will keep the ID, the other files will get a new ID.

Press `Ctrl+K` to open the commands dialod and select the **Fix...** command:

![image](https://user-images.githubusercontent.com/12187299/89936240-534e8200-dbe1-11ea-8438-4e205924a326.png)

Yet I have to create a command to duplicate a scene file.

**Comment by PhaserEditor2D** [comment]
Done, I added a **Duplicate Scene** command to the Scene Editor context menu:

You should use this option to safely duplicate a scene.

![image](https://user-images.githubusercontent.com/12187299/89941366-e8a14480-dbe8-11ea-94ac-2533bcdce38e.png)
