### ISSUE TITLE
Show tooltip on texture selection

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#64]
I have a problem where I sometimes can't tell which is the correct texture that I want to use.
It would be great to have a tooltip show the full frame name when you hover your mouse over it.

![image](https://user-images.githubusercontent.com/9307505/89843577-1e8dec80-db47-11ea-9f49-f83f150aa218.png)

**Comment by PhaserEditor2D** [comment]
Yes, in the meantime, you can zoom out and get the textures in a list layout:

![image](https://user-images.githubusercontent.com/12187299/89849755-2eadc800-db57-11ea-8e87-b3563ad550d6.png)

**Comment by PhaserEditor2D** [comment]
Hi @ItsGravix 

by the way, when you select a texture, it shows its key in the Inspector view. It is not better than a tooltip? I v1 of the editor I did a lot with the tooltips but I think that if we have an Inspector view we don't need the tooltips:

![image](https://user-images.githubusercontent.com/12187299/90086057-87ac6600-dce7-11ea-95ef-684bfc1d5da4.png)

**Comment by ItsGravix** [comment]
@PhaserEditor2D No, because every time I do that I have to keep guessing and searching until I click the correct one.

**Comment by PhaserEditor2D** [comment]
Instead of tooltips, we will use a Status bar (#68 ) and remember the zooming of viewers (#67)
