### ISSUE TITLE
Add Ability To Add Files Other Than Packs To Scene Preload

### ISSUE THREAD

**Issue by Connor800** [PhaserEditor2D/PhaserEditor2D-v3#69]
Currently you are able to add an asset pack to a scene for the editor to generate a preload method, file types other than asset packs could be allowed in the preload method as well.

**Comment by PhaserEditor2D** [comment]
I don't get it. If you like, you can write your `preload()` method in your "user code region".

**Comment by Connor800** [comment]
Yes, but any asset loaded manually won’t show up in the editor.

**Comment by PhaserEditor2D** [comment]
No, to show up in the editor it has to be in an asset pack file.

I don't understand what's your goal, but if you want to get the assets ready for the editor, you have to add it to an asset pack file, let's say, `editor-pack.json`. And that's all, you are not forced to load that file in the game, you can use it only for the editor. Then, you can write the preload method and load the assets in the way you need.

**Comment by PhaserEditor2D** [comment]
Hi @Connor800 

The solution I propose in the above comment works for you?

**Comment by Connor800** [comment]
Yes, that is what I currently use but if a scene loads a single asset, like a multi atlas file, wouldn’t an extra file (the asset pack) be redundant?

**Comment by PhaserEditor2D** [comment]
> Yes, that is what I currently use but if a scene loads a single asset, like a multi atlas file, wouldn’t an extra file (the asset pack) be redundant?

If you don't load the asset pack it is not redundant. You can remove that pack from the dist build. It is a pack just for designing the scenes.
