### ISSUE TITLE
Additional Parameters in constructor for prefabs

### ISSUE THREAD

**Issue by bfountaine** [PhaserEditor2D/PhaserEditor2D-v3#7]
I'm working with PhaserEditor 1.5.3.20181107 and would like to create a sprite prefab (and a group prefab) but want to be able to pass in extra parameters into my constructor. The generated code only has the default parameters. Essentially I'd like to be able to do what you can do in a state's init user-code but I'd like to be able to also do it in the constructors for all prefabs (if this is possible already please let me know how). I'm working in Typescript rather than javascript

**Comment by MerlinGoneSuperSaiyan** [comment]
> 
> 
> We just implemented User properties for prefabs: https://help.phasereditor2d.com/v3/scene-editor/prefab-user-properties.html
> 
> Yet, this is an interesting request. Maybe we can add a **Initialize in constructor** parameter to the properties so if you check it, the prefab constructor will be generated with arguments to init the properties.

I was directed here by the 3.2 update post that asked us to submit issues:

This is exactly what I was going to ask for.  Looking forward to 3.3.

Thanks!

**Comment by PhaserEditor2D** [comment]
Thanks @MerlinGoneSuperSaiyan !

Yes, but probably for v3.4.0 because we are going to do a release this week with some important bug fixes, so we move this issue for the other release. But please, keep in contact because it could be in less than a month!

**Comment by PhaserEditor2D** [comment]
For the moment I think this is a good solution: https://help.phasereditor2d.com/v3/scene-editor/user-components-start-update-methods.html

**Comment by PhaserEditor2D** [comment]
I think adding parameters to constructors adds an extra complexity that can be solved using properties and lifecycle events listeners.
