### ISSUE TITLE
Sort folders at the top

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#71]
Folders currently seem to be sorted alphabetically just like any other file.
The file explorer should give folders a priority so it's easier to find them at the top.

![image](https://user-images.githubusercontent.com/9307505/91108773-dee6fa80-e646-11ea-8499-fbd86b784bbb.png)

**Comment by PhaserEditor2D** [comment]
This is a regression of the last release!

**Comment by PhaserEditor2D** [comment]
Done. It is available in `develop`.
