### ISSUE TITLE
Physics Editor

### ISSUE THREAD

**Issue by NickChowHK** [PhaserEditor2D/PhaserEditor2D-v3#74]
Phaser provides two powerful physics systems: Arcade and Matter. 
However, it is not easy to create complex physics bodies composed of fixtures.
It would be pleasantly cool if it can create perfect collision shapes with only one click and check out the collision effect inside the scene editor.

**Comment by PhaserEditor2D** [comment]
Open again. Arcade Physics was implemented, but yet we need to implement Matter physics.

**Comment by PhaserEditor2D** [comment]
I close this since Arcade Physics is already implemented. Please, follow the issue about implementing #244 Matter Physics.
