### ISSUE TITLE
allow components to be imported outside current game folder

### ISSUE THREAD

**Issue by mikestonecodes** [PhaserEditor2D/PhaserEditor2D-v3#77]
I want to share components between projects. assets or other files would be cool too. currently I have a loader scene which loads other scenes into it.

**Comment by PhaserEditor2D** [comment]
Hi @mikestonecodes 

I don't understand. You need the generated JS files generated by the components compiler. How can we share it between projects? Please, can you propose something in more detail?

I am implementing components as something that you can share between projects. That's awesome that you plan to do it. But honestly, right now I don't have a clear idea of how to do it without copying the same components in every project.

**Comment by mikestonecodes** [comment]
how do you share them between projects without copy pasting? The system I am building is going to have over 100 games on it, so I would like a way to make sure there is no duplicated code between each game. Simply being able to reference the components outside the project would fix this. currently when you press "add component" it references all the components in the project.

**Comment by PhaserEditor2D** [comment]
I see two contexts here: development and execution.

In development, I think you can copy all the components in every project. At least, the `*.components` files. Or you can create a link to a "shared" folder with the components.

In runtime, you have all the options you have on web development. You host the components code in a CDN or in a single address and you load it with a script tag in your game (or with the Phaser `load.script()` method if you want to report progress).

I mean, the only thing that needs Phaser Editor is to know about the components, so you need to place the `*.components` files somewhere in the project. But the editor needs it only as metadata, it is not needed by the game when it is running. Only the generated code is needed but you will host it in another place, as a shared resource.

I think you can write some distribution scripts to help you with this.

**Comment by mikestonecodes** [comment]
ok I see now, so only need to copy paste the *.component file
