### ISSUE TITLE
Allow to load scripts in order (important!)

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#79]
**Important Feature Request**
I need to be able to load scripts in order so I can extend another class without having to worry about the extended class loading first.
![image](https://user-images.githubusercontent.com/9307505/93026490-448a2f00-f5d4-11ea-8952-31bdf0ffb196.png)

**Comment by PhaserEditor2D** [comment]
CC: @aleksei-tro 

Done. You can select now the **Scripts (Predictable Order)** in the Asset Pack Editor:

![image](https://user-images.githubusercontent.com/12187299/93243870-d1f58c80-f756-11ea-8bc3-d9a4e05e6f98.png)

And add the scripts and sort them in the Inspector view:

![image](https://user-images.githubusercontent.com/12187299/93243950-f5203c00-f756-11ea-9e8c-53bdad740269.png)

You can test it with this build:

macOS: https://drive.google.com/file/d/1dwkEwpcX6fpIabQ4tDKH66BcqP2bENrb/view?usp=sharing
Windows: https://drive.google.com/file/d/1vmflGjLUSniV4_nH1tyzXPExSzyMgIfo/view?usp=sharing

Please, re-open this issue if you have any problem.

**Comment by PhaserEditor2D** [comment]
By the way, remember to clear the browser cache to get the latest changes.
