### ISSUE TITLE
Tilemaps with JSON data

### ISSUE THREAD

**Issue by Tilmn** [PhaserEditor2D/PhaserEditor2D-v3#8]
Hi!

I successfully worked with tilemaps that are defined with a CSV file. But it does not work as expected with tilemaps whose data is in JSON format. Where the map should appear in the canvas editor only an empty rectangle with the text "Tilemap JSON" comes up.

I tried it in a new project using super_mario.json and super_mario.png from the Phaser example "Load Tilemap Json": https://phaser.io/examples/v2/loader/load-tilemap-json.

**Comment by PhaserEditor2D** [comment]
Done in v3.8.0.
