### ISSUE TITLE
Map browsers on Macs to use command+s for save instead of ctrl+s

### ISSUE THREAD

**Issue by aleksei-tro** [PhaserEditor2D/PhaserEditor2D-v3#80]
When working on macs, command+s for save is second nature but right now it brings up the browsers' `save page` dialog.
I know that some websites do override the default shortcuts, namely Google Docs, so there must be a way

**Comment by PhaserEditor2D** [comment]
Hi,

Please can you test this build? https://drive.google.com/file/d/14jp8YybKYJEX6TMKSym9Iz44UaBQn5d8/view?usp=sharing

The issue should be fixed there. It also allows you to use the Command key in all the other commands (as an alternative to the Ctrl key).

**Comment by aleksei-tro** [comment]
Sorry, I replied in discord but will repeat here. Works kirk a charm! Thank you for the quick  change!

**Comment by PhaserEditor2D** [comment]
Great, thanks.
