### ISSUE TITLE
Optimizing all pngs in the project

### ISSUE THREAD

**Issue by zombiestruck** [PhaserEditor2D/PhaserEditor2D-v3#81]
It would be awesome to be able to optimize all pngs in the project and/or filter files to pngs to select which ones you want to optimize.

**Comment by PhaserEditor2D** [comment]
Hi. I think we are not going to implement this. In v1 and v2 of the editor, this was possible, but our philosophy in this version 3 is to provide only features related to Phaser development. It is possible that later we develop another product for asset management. For example, with texture packers, audio sprite packers, image optimizer, etc...
