### ISSUE TITLE
Set origin shortcuts not working

### ISSUE THREAD

**Issue by aleksei-tro** [PhaserEditor2D/PhaserEditor2D-v3#82]
## Version

* Phaser Editor 2D Version: 3.6

* Operating System: MacOS catalina 10.15.6

* Web Browser and version:
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Same issue in Firefox and Safari

## Description
the shortcut `Shift 1-9` to set origin does not work. No errors in console either

**Comment by PhaserEditor2D** [comment]
If you try by executing the origin command, but using the Command Palette (`Cmd+K`), does it work?

**Comment by PhaserEditor2D** [comment]
Hi @aleksei-tro 

This is working to me in macOS with the Keyboard Viewer.
