### ISSUE TITLE
Geom Phaser Objects in menu "Add new Object"

### ISSUE THREAD

**Issue by Gavolot** [PhaserEditor2D/PhaserEditor2D-v3#83]
I would really like to be able to create "graphics" objects. 
It could help me to set different trigger zones, visually.

I'm not the biggest memory saver when it comes to static objects that create forms like this.

Now I have to put a sprite and scale it, which is a way out, but not so convenient and visual.

Then when I start the game, I delete the sprite and replace it with the "shape".
Ideally, you can also set up styles)
but I know how difficult it is to create tools similar to yours

Example:    
    graphics = this.add.graphics({ lineStyle: { width: 2, color: 0x00ff00 }, fillStyle: { color: 0xff0000 }});

    circle = new Phaser.Geom.Circle(400, 300, 200);

   and I want can check, with "graphics visual in game or invisible forms"

**Comment by PhaserEditor2D** [comment]
Implemented in previous versions, but missed to close this.
![image](https://user-images.githubusercontent.com/12187299/121488085-bb582b00-c9a0-11eb-987b-9359c8e970f8.png)
