### ISSUE TITLE
Ignore Given Directories or Files

### ISSUE THREAD

**Issue by Connor800** [PhaserEditor2D/PhaserEditor2D-v3#88]
Currently, the editor will read through all directories and files the project has, but this may not be desirable for projects that use a building process like webpack to copy assets onto a `dist` folder or similar as asset packs, for example, show twice for game assets.

Ignore rules inside a `.gitignore` file should be respected, or at least give an option for such too.

**Comment by PhaserEditor2D** [comment]
Hi!

I think this can help you: https://help.phasereditor2d.com/v3/misc/resources-filtering.html

Just create an empty `.skip` file in the directory you want to exclude from the Phaser Editor project.

Please, tell me if it works for you.

**Comment by Connor800** [comment]
It works great for folders :) but it does not work for files and there is a possibility that a folder that *should* be ignored is not shipped by default and thus doesn't contain the `.skip` file (in consequence of being `.gitignore`d perhaps), so I still believe a solution for this should be put in place. Let me know what you think 😃

**Comment by PhaserEditor2D** [comment]
Hi, please, it would be great if you write a small example because I don't see what's the problem.

We can implement something like a file `.skipfiles` with the name of the files to be excluded but yet I don't see why it is needed.

**Comment by Connor800** [comment]
The main thing I can think of is having files on the project root that are not going to be used. I'll go ahead and close this as my original issue has already been solved by `.skip` 🙂
