### ISSUE TITLE
Inspector does not show Scene properties if another object is selected in the 

### ISSUE THREAD

**Issue by osirisguitar** [PhaserEditor2D/PhaserEditor2D-v3#89]
## Version
* Phaser Editor 2D Version: 3.8.1
* Operating System: MacOS Catalina
* Web Browser and version: Chrome 86.0.4240.111

## Description
Reproduce:
1) Click on a Scene tab
2) Select any object or folder in the outline
3) Click the scene file in the file tree
4) Click open file in the inspector.
5) Scene properties/config is not shown as expected, instead properties from object selected in step 2 above is shown (or nothing if a folder was selected in step 2)

## Possible solution

Click an empty area in the outline to deselect the object from step 2 above.

**Comment by PhaserEditor2D** [comment]
Also, maybe we can add an option in the context menu to show the scene settings.

**Comment by PhaserEditor2D** [comment]
Done. Now the scene editor remembers the last selected objects. Including empty selection.
You can test this in the `develop` branch:  https://github.com/PhaserEditor2D/PhaserEditor2D-v3-build-develop
