### ISSUE TITLE
Keybind and right click menu to open Gameobject add dialog

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#90]
Sometimes I have to clear my search query in order to add a game object.
![image](https://user-images.githubusercontent.com/9307505/98452735-f3a03e00-211f-11eb-87bb-977c145e98d6.png)

**Comment by PhaserEditor2D** [comment]
Done.

Now you can add an object from the context menu:

![image](https://user-images.githubusercontent.com/12187299/108616069-23760780-73d8-11eb-9a33-56107a309966.png)

Or the Add Object dialog (open it with the `A` key):

![image](https://user-images.githubusercontent.com/12187299/108616076-40123f80-73d8-11eb-8923-17d5e5739493.png)
