### ISSUE TITLE
Create a new tab when you search something in the Blocks view

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#91]
Would be useful if when you searched something while in the Blocks tab, it creates a new tab for your current search. This would also solve the issue where I have to clear my search query in order to add a Game Object 👍 
![image](https://user-images.githubusercontent.com/9307505/98452794-850fb000-2120-11eb-97bf-6de12fe93227.png)

**Comment by PhaserEditor2D** [comment]
And what do you think if instead of saving the query you can label blocks?

Then you can filter by labels the Blocks view content.

**Comment by PhaserEditor2D** [comment]
I don't see the moment I can start working on this. I have some "great" ideas about this :)

**Comment by PhaserEditor2D** [comment]
Hi. How are you doing with the Blocks view? Is this feature request valid after implementing the sub-tabs?

**Comment by ItsGravix** [comment]
@PhaserEditor2D I think it's fine how it is right now.

**Comment by PhaserEditor2D** [comment]
Great thanks.
