### ISSUE TITLE
In addition to using `.skip`, being able to specify pattern for ignored files

### ISSUE THREAD

**Issue by aleksei-tro** [PhaserEditor2D/PhaserEditor2D-v3#93]
For example `*@3x-0.png` & `*@3x.json`
Maybe this can be combined with `.skip` files and you can specify the pattern inside it.
That way if the `.skip` file is empty, it can be treated as `*`

**Comment by PhaserEditor2D** [comment]
I like the idea of using the same `.skip` file. Thanks.

**Comment by PhaserEditor2D** [comment]
Done.

In this folder, there are the server binaries for Windows and macOS:

https://drive.google.com/drive/folders/1mQH7y9DK0MftVeqbXJouDRUVvVrwVC_4?usp=sharing

Now you can add glob patterns to the `.skip` files. The syntax of the patterns are documented here: https://github.com/bmatcuk/doublestar#patterns

These are some examples:


```
# you can write comments like this
# this pattern matches all
*
```

```
# matches all json files in this folder and sub-folders
**/*.json
```

```
# matches all txt files in this folder (sub-folders are not included)
*.txt


```
# matches all like img@2x.png, img@2x.json, ...
**/*@?x*
```

The `skip` files are nested. It means, the patterns of a skip file are applied to the container folder and all the sub-folders. It means, the patterns are inherited.
