### ISSUE TITLE
Default values not appearing in .scene's JSON data

### ISSUE THREAD

**Issue by ChristianTucker** [PhaserEditor2D/PhaserEditor2D-v3#97]
## Version
* Phaser Editor 2D Version: 3.10.0 FREE
* Operating System: Windows 10 PRO
* Web Browser and version: N/A

## Description

The JSON data generated in the `.scene` files is missing some information for default values, for example in the `Text` the `originX` is excluded from the `.scene` data when it's at 0.5 however the default originX in Phaser is 0. 

This issue also occurs with User Components that have a default value, it's not provided in the .scene file. This requires hard-coded defaults to be added during parsing of these files outside of the editor.

**Comment by PhaserEditor2D** [comment]
Regarding the User Components, the default values are defined in the component definition. When an object is serialized in a `.scene` file, properties with values equal to the default value are ignored. So, to know the exact value of a property you should look into the component definition.

**Comment by PhaserEditor2D** [comment]
Thinking again about this. A .scene file with all default values could be too big, and breaks the way locked/unlocked properties are coded. I think a detailed developer reference document with the default values is a better alternative.
