### ISSUE TITLE
Configure external code editor different to Visual Studio Code

### ISSUE THREAD

**Issue by falmic** [PhaserEditor2D/PhaserEditor2D-v3#98]
Hi, im using electron version of PE2D-v3 on macos.
i saw on hambuger menu option to run visual studio code.
any chance to change it for option "run editor" and manualy select what editor i wanna to run ?

regards
mike

**Comment by PhaserEditor2D** [comment]
Done, take a look to the release notes: https://phasereditor2d.com/blog/2021/01/phaser-editor-2d-v3102-released
