### ISSUE TITLE
Multi-line String Component Property

### ISSUE THREAD

**Issue by ItsGravix** [PhaserEditor2D/PhaserEditor2D-v3#99]
It would be great if I could create a component that supports a multi-line string like the one in the Text Content property:
![image](https://user-images.githubusercontent.com/9307505/104807644-61b35200-57ae-11eb-9c14-bc98e8ea83bb.png)

Currently I am using String but it can get annoying when I type long paragraphs like this:
![image](https://user-images.githubusercontent.com/9307505/104807654-77c11280-57ae-11eb-8666-7a2c1c39676f.png)

**Comment by PhaserEditor2D** [comment]
Is it fine if I add a button next to the text field? If you click the button it opens a dialog with a multiline field.

**Comment by ItsGravix** [comment]
Sounds good!

**Comment by PhaserEditor2D** [comment]
All string properties will be like this:

![image](https://user-images.githubusercontent.com/12187299/104823580-36b21800-5819-11eb-9e8b-7153319bbcf3.png)
